enjoy-digital/litex

- litex/soc/integration/cpu_interface.py
- litex/soc/software/bios/main.c
- litex/soc/software/libcompiler_rt/Makefile
The first two changes are from the timvideos fork of misoc at https://github.com/timvideos/misoc/commits/legacy
I'm guessing these changes should also be sent to upstream MiSoC too?
> Bunch of small fixes

- litex/build/sim/verilator.py
- litex/soc/software/bios/main.c
* Make it easier to understand the cause when verilator build fails.
* Make it easier to see what arch the BIOS is running on.
> More fixes.

- litex/build/tools.py
- litex/soc/integration/builder.py
You accidentally reverted this feature in the merge which meant the firmware was completely rebuilding every time (as csr.h was modified).
> Fixing accidental revert in merge commit.

- litex/soc/integration/soc_core.py
Missed as part of misoc merge at ff31959aea1e3815d95798996c3999f122314ae6.
> Fixing missing csr_constant/config support.

- litex/soc/cores/flash/spi_flash.py
I don't know why this works and your existing code doesn't......
> WIP: Adding working spi_flash driver

- litex/boards/platforms/mercury.py
I've been sitting on this commit for quite a while. I've simply been forgetting to send it! Self-explanatory commit message.
> Add Mercury development board (port from MiSoC)

- litex/soc/tools/remote/etherbone.py
Info comes from http://www.ohwr.org/attachments/1669/spec.pdf dated 24 July 2012
> More docs for etherbone packet fields.

- README
> Fix typo in README: experimental

- litex/build/xilinx/vivado.py
> Add tracelength report generation by default to help with board layout

- litex/boards/platforms/mercury.py
Self-explanatory, for feature parity w/ Migen/MiSoC.
> Add Mercury baseboard support from Migen, import fixes.

- litex/gen/fhdl/tracer.py
Self-explanatory, this commit ensures Python 3.6 works. I have not tested this, but it's a direct `cp` from my Migen and thus should work fine.  I don't know if/when Migen/MiSoC and LiteX will reunite, but I'll keep making PRs to LiteX for the important contributions.
Minor contributions of mine can be imported whenever you do a bulk merge.
> fhdl/tracer: Import Python 3.5/3.6 version guards from Migen.

- setup.py
> add pyserial to the package requirements

- litex/build/xilinx/common.py
This is needed if you want colors but are using pipes and similar.
> Support forcing colorama colors on.

- litex/boards/platforms/mimasv2.py
Self-explanatory, all I did was remove the SPI Flash-specific stuff. I'm mainly adding this platform for testing stuff w/ litesdcard.
> Add mimasv2 platform (pulled from litex-buildenv).

- litex/boards/platforms/arty_s7.py
Verified with the `simple` SoC target. I'll add the DDR3 controller in a few days.
> boards/platforms: Add Arty S7 Board.

- litex/boards/platforms/arty_s7.py
Thanks to @mhanuel26 for pointing this out.
> boards/arty_s7: Fix IOStandard on System Clock.

- litex/soc/integration/builder.py
Fix generating csr.csv file when no absolute path is given.
> Fix generating csr.csv file

- litex/build/lattice/icestorm.py
Self-explanatory, for `migen` parity.
> lattice/icestorm: Add nextpnr pnr as alternate pnr tool.

- litex/boards/platforms/tinyfpga_bx.py
- litex/build/lattice/programmer.py
Self-explanatory. If migen devs for the corresponding PR want changes, I'll also submit them here.
> build/platforms: Add TinyFPGA BX board and programmer.

- litex/soc/integration/builder.py
- litex/soc/software/bios/Makefile
- litex/soc/software/libbase/Makefile
- litex/soc/software/libbase/crt0-lm32.S
Per [discussion](https://github.com/fupy/micropython/pull/51#discussion_r219712088) on [PR 51](https://github.com/fupy/micropython/pull/51) of `fupy` with @ewenmcneill, I wanted to improve the variables, defines, and output file names.
> Improve XIP Support

- litex/boards/platforms/ulx3s.py
- litex/boards/targets/ulx3s.py
- litex/build/lattice/prjtrellis.py
ULX3S demo boots to BIOS; SDRAM not yet working though
> Switch Trellis build to use LPF constraints; working on ULX3S

- litex/boards/targets/versa_ecp5.py
- litex/build/lattice/trellis.py
See also enjoy-digital/litedram#76
Tested with YosysHQ/Yosys#794 and YosysHQ/nextpnr#219
> Add trellis build option to versa_ecp5 and bring trellis support up to date

- litex/build/lattice/common.py
Signed-off-by: David Shah <dave@ds0.me>
> lattice/common: Fix tristate buses with Trellis

- litex/build/xilinx/common.py
> build/xilinx: Update Yosys write_edif parameters

- litex/soc/tools/remote/__init__.py
- litex/soc/tools/remote/comm_usb.py
- litex/utils/litex_server.py
This adds preliminary support to `litex_server` for the new USB protocol.
> Litex usb server support

- litex/soc/integration/soc_core.py
A couple of tiny fixes for add_interrupt() !
> Fix interrupt_name in soc_core/add_interrupt

- litex/soc/software/bios/main.c
This adds a new command to BIOS CLI - *fw* (flash write) - that allows to write uint to flash having a simillar signature to the existing *mw* (memory write) command.
> fw (flash write) command

- litex/soc/software/libnet/tftp.c
Show some sign of progress during long TFTP downloads -- psychologically reassuring that stuff is still happening :)
> BIOS: TFTP: ASCII spinner progress indicator (cosmetic)

- MANIFEST.in
> Add verilog submodule from CPU cores to manifest

- .gitmodules
- litex_setup.py
Problem:
http makes the cloning fail.
> changing http to https

- litex/soc/integration/cpu_interface.py
- litex/soc/interconnect/csr.py
- test/test_csr.py
This is an experiment to add field and documentation support to CSR.
> soc/interconnect/csr: add CSRField/documentation support, do some simplification on CSRStorage

- litex/build/xilinx/programmer.py
Maintaining parity with https://github.com/enjoy-digital/litex/pull/170
> vivado just needs to be in the path for the programmer as well

- litex/soc/integration/soc_core.py
> soc/integration: ensure CSR constants are in uppercase

- litex/soc/cores/icap.py
> fix comments in icap.py

- README
Following my problems with the quick start guide (issue #273), I suggest a few modifications to have a "real" quick start guide.
> Update README (related to issue #273)

- litex/soc/cores/icap.py
This fixes fifo handling in `ICAPBitstream`
> Fix ICAPBitstream

- litex/soc/integration/soc_core.py
- litex/soc/software/bios/isr.c
- litex/soc/software/include/base/irq.h
this is (hopefully) non-controversial stuff I'd like to apply before posting a CSR accessor update RFC
> Misc. Rocket and CSR cleanup

- litex/soc/cores/uart.py
This version of the UART adds a second, compatible UART after
the first.  This maintians software compatibility, and allows a
program running on the other side of the litex bridge to act as
a terminal emulator by manually reading and writing the second
UART.
> uart: add BridgedUart

- litex/tools/litex_sim.py
litex_sim used a single predefined DRAM chip, with this it is now possible to specify which one to use with `--sdram-module` and also its data bus width can be set using `--sdram-data-width`.
Fixes #352
Fixes #353
> tools/litex_sim: specify dram chip and data width via commandline

- litex/tools/litex_sim.py
This PR will allow litex_sim to run simulations using other types of sdram memory (DDR, LPDDR, DDR2, DDR3) instead of being limited to SDR only
Closes #355
> tools/litex_sim: add support for other sdram types

- litex/soc/cores/i2s.py
- litex/soc/cores/spiopi.py
Request to merge I2S and SPIOPI cores. If you want me to split into two separate PR's, I can back this out and do that too.
> Request to merge I2S and SPIOPI cores

- litex/tools/litex_sim.py
This adds option to disable SDRAM timing verifier module and to enable verbose DFI logging which generates output similar to this:
```
[...]
[0000007561990000ps] P0 PRE
[0000007562020000ps] P0 REF
[0000007562310000ps] P0 B1 ACT
[0000007562342500ps] P1 B1 RD
[0000007563562500ps] P1 B1 RD
[0000007564782500ps] P1 B1 RD
[0000007566002500ps] P1 B1 RD
[0000007567222500ps] P1 B1 RD
[0000007568442500ps] P1 B1 RD
[0000007569662500ps] P1 B1 RD
[0000007569810000ps] P0 PRE
[0000007569840000ps] P0 REF
[...]
```
Depends on enjoy-digital/litedram#138
> tools/litex_sim: add cli options to control SDRAM timing checker

- litex/soc/interconnect/axi.py
- litex/soc/interconnect/wishbone.py
- litex/tools/litex_extract.py
This script allows to generate a minimal SoC with selected peripherals that has external Wishbone bus connection exposed. Such a SoC can then be for example attached to an existing design.
> Add a script that allows to generate standalone cores

- CONTRIBUTORS
- litex/soc/cores/cpu/lm32/core.py
- litex/soc/cores/cpu/mor1kx/core.py
- litex/soc/cores/cpu/picorv32/core.py
- litex/soc/cores/cpu/vexriscv/core.py
- litex/soc/integration/builder.py
- litex/soc/integration/export.py
- litex/soc/interconnect/axi.py
- litex/tools/litex_gen.py
- litex/tools/litex_sim.py
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
Signed-off-by: Mateusz Holenko <mholenko@antmicro.com>
> Fix copyrights

- litex/soc/cores/i2s.py
- litex/soc/cores/spi_opi.py
Fix some errors that were observed in the generated documentation of spi_opi and i2s.
> Core doc fixes

- litex/soc/cores/clock.py
Specific clkoutn_divide_range can now be provided by specialized XilinxClocking classes.
When provided, the specific range will be used. Floats are also now supported in the
range definition/iteration.
@bunnie: can you check this is ok and working for your use case?
> cores/clock: simplify Fractional Divide support on S7MMCM.

- litex/tools/litex_sim.py
This PR adds basic support for `hybrid` MAC mode enjoy-digital/liteeth#36, it might need some cleanup and probably UDP/IP core should be modified to also support this configuration so that it won't be necessary to manually instantiate all the cores (ARP, IP, etc.)
> litex_sim: add support for hybrid mac

- litex/soc/software/include/base/spisdcard.h
- litex/soc/software/libbase/spisdcard.c
Point raised that my use of unsigned int/long/short could potentially raise issues on various bit length setups.
Compiled and tested on de10nano.
> Use <stdint.h> to provide structure sizes

- litex/build/xilinx/vivado.py
A proposed fix to issue https://github.com/enjoy-digital/litedram/issues/176
> Fix timing constraints

- .travis.yml
- litex_setup.py
os.system doesn't report if any of the commands fail. This means that if something goes wrong it happily reports success making it hard to debug issues.
> litex_setup: Use subprocess so failures are noticed.

- .travis.yml
- litex_setup.py
The downloading got a little more complicated then I would have liked.
It also tells user to update path at the end now (fixes #449).
> Add GCC downloading via litex_setup.py

- .travis.yml
- litex_setup.py
This tests that the tooling also works on Mac and Windows.
Needs #452 to be merged first.
> Add multiple Python versions, Windows and Mac to Travis CI testing

- litex/soc/integration/soc_core.py
Include information about being a linker region.
> soc_core: Fix region type generation

- litex/tools/litex_sim.py
Requires https://github.com/enjoy-digital/litedram/pull/181.
> litex_sim: add option to create SDRAM module from SPD data

- litex/build/lattice/programmer.py
fstrings in this module breaks Litex for python3.5
If you could please take this patch it would save me a lot of headache updating python on my system and potentially upsetting other projects in maintenance....thank you!
> propose patch to not break litex for python 3.5

- litex/build/lattice/programmer.py
I don't know what I was thinking when I exposed the `erase` flag. There's no reason to set it to `False`
> Lattice OpenOCD JTAG programmer: removed erase flag and made progress output less noisy

- MANIFEST.in
> Add data dirs to manifest

- litex/build/lattice/diamond.py
> diamond: project generation improvements

- litex/soc/software/bios/commands/cmd_sdcard.c
- litex/soc/software/bios/sdcard.c
- litex/soc/software/bios/sdcard.h
This PR updates BIOS adapting it to changes in LiteSDCard introduced by https://github.com/enjoy-digital/litesdcard/pull/7.
It is tested on a modified arty platform with added LiteSDCard module. 
Modification of the platform is not part of this PR, but we plan to add it to linux-on-litex-vexriscv's platform. The current version (for testing purposes) is available at https://github.com/antmicro/linux-on-litex-vexriscv/tree/add_mmc_sdcard.
> Update Litex bios to handle updated litesdcard.

- litex/soc/integration/soc.py
- litex/soc/integration/soc_core.py
- litex/soc/interconnect/wishbone2csr.py
These are some improvements for the generation of standalone cores without CPUs such
as LiteDRAM
> Improve standalone cores

- litex/tools/litex_term.py
Specify the use of kernel address with flash flag.
> Update litex_term help

- litex/soc/cores/i2s.py
- test/test_i2s.py
This PR extends I2S module capabilities and adds `SoundSoC` configuration for Arty.
> Add I2S support to Arty

- litex/soc/software/liblitesdcard/sdcard.c
The additional (17th) byte returned via the response register was ignored by software (bios and kernel), so LiteSDCard was updated to only return the (original, useful) 128 bits.
This patch updates the LiteSDCard code in the LiteX bios to only expect those 128 bits, and to do so in a manner that's portable across CSR data widths and alignments.
NOTES:
1. Depends on https://github.com/enjoy-digital/litesdcard/pull/13
2. Tested on nexys4ddr with `(mor1kx, vexriscv, rocket) x (csr_data_with \in {8, 32})`
3. Side-steps issue #546 (which I'd still like us to agree upon one way or another, but is no longer "urgent" :))
> soc/software/litesdcard: update for response register back to 128 bits

- litex/soc/software/bios/boot.c
This allows to boot linux on mor1kx with an external device tree file and (optional) rootfs using netboot.
If the kernel file or the device tree are not found, it falls back to the `boot.bin` file.
> bios: boot: Boot linux on mor1kx with external device tree and rootfs

- litex/soc/cores/i2s.py
Not sure how they went missing...but just noticed them.
> wire up missing register bits.

- litex/tools/litex_gen.py
This PR aims to add option to generate Xilinx 7-series MMCM with dynamic reconfiguration port as a standalone core
> litex-gen: add mmcm core

- litex/soc/interconnect/axi.py
- test/test_axi_lite.py
This splits the down-converter read/write paths into to parallel converters and adds a basic up-converter with tests.
> Improve AXI Lite data width converters

- litex/tools/litex_server.py
The UART backend writes [read identifier, num_reads, addr] for every read request.
Etherbone packets are able to include multiple read requests.
Therefore, it is beneficial to merge sequential read requests to reduce writes (and possible latency overhead).
Benchmark:
A typical litescope fetch script with the following signals [ddrphy.dfi,cpu.ibus.cyc,cpu.ibus.stb] results in 1 read for the
data_valid register and 24 sequential reads for the scope data per timestamp.
Fetching data for a capture length of 512 over a 921600 baud UART (arty board) took:
```
205s (current master branch)
18s (with this merge function)
```
The proposed merger only merges read requests from one etherbone packet at a time and doesn't change the read order.
I didn't observe a speedup for UART over litex_server and …
> Merge sequential reads for the UART litex_server backend

- litex/tools/litex_json2dts.py
This PR extends the `litex_json2dts.py` script by adding support for the mor1kx CPU.
> litex_json2dts: Add support for mor1kx

- litex/soc/software/liblitesdcard/sdcard.c
With the way the clock divider is currently calculated, it is
possible for the effective sdcard clock to end up **higher** than
the requested `clk_freq` value.
With this PR, we instead calculate the divider starting with the `CONFIG_CLOCK_FREQUENCY/clk_freq`
ratio which is then rounded **up** to the nearest power-of-two, ensuring
that the resulting, effective clock frequency is <= to the requested
frequency.
@enjoy-digital: this is mostly just me wondering if there's any harm in setting the effective clock at a higher frequency than what's officially requested via the argument to `sdcard_set_clk_freq()`. If that's not a problem, please feel free to disregard this PR :)
> RFC: proper way to set sdcard clock?

- litex/tools/litex_server.py
- litex/tools/litex_sim.py
This should allow users (hopefully not just me) to use SimSoC in a more modular way.
> tools/{litex_sim, litex_server}.py: Minor clean-up

- litex/build/sim/core/modules/serial2tcp/serial2tcp.c
- litex/soc/cores/uart.py
Make serial2tcp play nicely with the Stream2Wishbone bridge.
This allows a verilator simulation to behave as virtual hardware and connect to litex_server in the same way as real hardware would.
Example of typical use case is here:
https://github.com/yetifrisstlama/litex_test_project/tree/master/verilator_test
> Fix stream2wishbone

- litex/build/gowin/common.py
- litex/build/gowin/gowin.py
- litex/build/gowin/platform.py
- litex/build/openfpgaloader.py
This PR aims to add support for Gowin FPGAs to LiteX.
Initially it only supports the vendor tools, but I'd really like to add support for Yosys+Apicula in the future.
At this point I can run a basic blinky, but stuff is likely missing and broken, so WIP. I'll try some more elaborate examples, and update as needed.
I just want to get this out here to get some feedback on dumb things I might be doing. I'm basically copying from the other build targets without fully understanding every little detail.
> Build support for Gowin

- litex/build/lattice/radiant.py
This for testing YosysHQ/yosys#2397 
It's a bit of a fudge because it doesn't actually skip Radiant's synthesis - to do that would require use of the map, par, trce, bitgen commands individually without using Tcl. I can change to that approach if it is preferred, but probably for Linux only.
> build/radiant: Allow synthesis with Yosys

- litex/boards/platforms/arty.py
- litex/boards/targets/arty.py
- litex/build/xilinx/symbiflow.py
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
This PR fixes the symbiflow build and removes the various workarounds that were needed to have symbiflow working.
> symbiflow: remove workarounds

- litex/soc/cores/cpu/zynq7000/core.py
`zynq7000` IP can be added using `xci` file (current solution), using a block design or by using `create_ip` (this PR).
With this way a preset, and/or list of custom CONFIG.xxx, is used to configure zynq IP. No more needs to store somewhere an `xci` file.
Board's preset are located in vivado directory (shipped with this tool for zedboard, zc706,... or manually installed for zybo). This file is not mandatory (and not available for redpitaya), the configuration can be done using a dict provided at the platform level (with the drawback to add many lines in this file).
To resume for using this approach:
- an variable called `ps7_preset` may be added at platform and provides preset name in `vivado`
- a dict pointed by `ps7_config` again at the platform level may be added to provides all …
> zynq7000: add tcl to create zynq IP based on board preset and custom configuration

- litex/soc/interconnect/axi.py
- connect_to_pads() used to be just in AXILiteInterface, but it can be used by AXIInterface just as well, so I moved it out of the AXILiteInterface class
- removed a bit of code duplication with getattr(bus, channel)
> soc/interconnect/axi: let connect_to_pads() be used by AXIInterface too

- litex/soc/cores/spi_opi.py
this is another tiny change, i will go ahead and merge it -- let me know if you prefer I let you review these
> another minor change - reveal STARTUPE2 block's ring oscillator

- litex/build/altera/quartus.py
> Quartus: handle vh and svh files

- litex/tools/litex_json2dts.py
This is needed as my initrd size is much larger than the default 8mb.
Also, sometimes the kernel I build is also large, so its good to be
able to move the initrd starting position.
Issue #748
> dts: Allow specifying initrd position and size via args

- litex/soc/software/bios/boot.c
- litex/soc/software/bios/cmds/cmd_bios.c
- litex/soc/software/bios/cmds/cmd_i2c.c
- litex/soc/software/bios/helpers.c
- litex/soc/software/bios/readline.c
- litex/soc/software/bios/readline.h
- litex/soc/software/include/base/inttypes.h
- litex/soc/software/include/base/lfsr.h
- litex/soc/software/include/base/limits.h
- litex/soc/software/include/base/stddef.h
- litex/soc/software/include/base/stdint.h
- litex/soc/software/include/base/stdio.h
- litex/soc/software/libbase/exception.c
- litex/soc/software/libbase/memtest.c
- litex/soc/software/libbase/progress.c
- litex/soc/software/libbase/vsnprintf.c
- litex/soc/software/liblitedram/bist.c
- litex/soc/software/liblitedram/sdram.c
- litex/soc/software/liblitesata/sata.c
- litex/soc/software/liblitesdcard/sdcard.c
This pull request fixes compiler warnings, and enables checking of printf()-style format strings
The first commit is also included in pull request #775.
> Compiler warning fixes

- litex/soc/cores/clock/lattice_ice40.py
Add missing AsyncResetSynchronizer import.
> cores/clock/lattice_ice40: add missing AsyncResetSynchronizer import.

- litex/soc/software/liblitedram/sdram.c
Described in corresponding litedram PR.
> software/liblitedram: selectable write leveling MR (for LPDDR4 support)

- litex/build/xilinx/symbiflow.py
Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>
> build/xilinx: add xc7a200t-sbg484-1 to symbiflow toolchain

- litex/soc/software/demo/demo.py
- litex/tools/litex_term.py
I spent about half an hour trying to figure out, how the demo creator is supposed to being
used and I hope this usage message will save others the time.
> demo: more helpful usage message / support Altera JTAG in litex_term

- litex/soc/software/demo/Makefile
- litex/soc/software/demo/helloc.c
- litex/soc/software/demo/hellocpp.cpp
- litex/soc/software/demo/main.c
brings a hello world C and C++ as a minor addition to the demo, might be of help to users since c++ wasn't in the Makefile
> demo with c++ HW example

- litex/soc/integration/soc.py
This comes handy for testing. I kept the method signature the same as
the video terminal so it could be swapped out easily for a test pattern.
> video: convenience method to add color bar pattern

- litex/soc/interconnect/axi.py
Downconverter should start on master's addr, not on aligned master's addr.
> interconnect/axi: Fix AXILiteDownverterWrite/Read base address.

- litex/soc/cores/cpu/vexriscv_smp/core.py
- litex/tools/litex_json2dts.py
It is already working, but do not merge yet ^^
Need https://github.com/litex-hub/pythondata-cpu-vexriscv_smp/pull/4 first
> cpu/vexriscv_smp add FPU support

- litex/tools/litex_json2dts.py
A few whitespace fixes, and 3 fixes for issues detected by dt-schema validation.
> Json2dts fixes

- litex/tools/litex_json2dts.py
2 fixes for issues detected by dt-schema validation after https://github.com/litex-hub/linux/pull/7
> Json2dts fixes2

- litex/soc/software/liblitedram/sdram.c
This implements write DQ-DQS training procedure. This is useful for LPDDR4 to achieve higher frequencies as noted in the datasheet:
> The device uses an unmatched DQS-DQ path to enable high-speed performance and
> save power. As a result, the DQS strobe must be trained to arrive at the DQ latch center-
> aligned with the data eye.
DQ-DQS training is enabled via the `SDRAM_PHY_WRITE_DQ_DQS_TRAINING_CAPABLE` preprocesor define. I'm also creating a PR to litedram which adds this define.
The training procedure performed separately for each module consists of 1. finding best bitslip for given module by performing read leveling scan and 2. scanning through all available DQ delays and finding the center of the valid window (similarily as when performing read leveling). In terms of speed it is …
> Write DQ-DQS training

- litex/build/lattice/programmer.py
In preparation for the iCESugar board.
Load and Flash tested: works.
> lattice/programmer.py: Add iCESugar programmer

- litex/soc/cores/video.py
> Add 1920x1200@60 RBv2 to LiteX video modes

- litex/tools/litex_json2dts.py
This commit adds support for enabling interupts in switches module.
Declaring switches as GPIOIn module with with_irq=True
will make dts generation add correct interrupt controller definition.
Also, if SWITCHES_NGPIO constant is defined it will be used to
specify correct number of gpios in dts.
example:
self.submodules.switches = GPIOIn(pads=switches_pads, with_irq=True)
self.add_csr("switches")
self.irq.add("switches", use_loc_if_exists=True)
self.add_constant("SWITCHES_NGPIO", len(switches_pads))
Linux driver related changes are in https://github.com/litex-hub/linux/pull/3
> dts: gpio: interrupt controller definition for switches

- litex/build/sim/verilator.py
- litex/tools/litex_sim.py
Let's GitHub Actions users specify the `interactive` mode.
Follow up to #881
> Expose non-interactive mode

- litex/soc/cores/cpu/blackparrot/bp_litex/bp2wb_convertor.v
- litex/soc/cores/cpu/blackparrot/bp_litex/fpga/ExampleBlackParrotSystem.v
- litex/soc/cores/cpu/blackparrot/bp_litex/simulation/ExampleBlackParrotSystem.v
> Blackparrot 32bit csr

- litex/build/sim/gtkwave.py
This is a small improvement for the GTKWave savefile generator to automatically handle Endpoint objects - signals will be sorted and colored automatically. The `.add()` method can also handle other objects from litex.soc.interconnect.stream. This will happen if an object contains sink/source attribute that is of type Endpoint, and the result will look like this:
This should be useful for pipelines of multiple stream modules.
> GTKWSave: improved support for Endpoint

- litex/soc/cores/cpu/blackparrot/core.py
BlackParrot's latest version brings support for floating point operations
> Update blackparrot imafd

- litex/soc/software/liblitespi/spiflash.c
This PR introduces a way to support QPI mode when using LiteSPI on the example of MX25L12833F. The chip-specific code is included when the SoC has the following constants defined:
```
soc.constants['FLASH_CHIP_MX25L12833F_QUAD'] = 1  # to use wp and hold as data lines
soc.constants['FLASH_CHIP_MX25L12833F_QPI'] = 1   # to also send commands using 4 lines
```
We'd probably want to put common instructions, i.e. `WREN`, into a separate header file + it'd be nice to have a separate header file per chip, but I'm not sure if that approach won't unnecessarily restrict us later.
This PR also depends on litex-hub/litespi#53.
> WIP: enable QPI mode in liblitespi

- litex/build/lattice/common.py
- litex/build/lattice/oxide.py
> build/lattice: work around lack of SDR I/O primitives in nextpnr

- litex/build/sim/common.py
Fix this syntax error https://github.com/enjoy-digital/litex/issues/1027
> fix: missing colon syntax error

- litex/build/xilinx/common.py
- litex/soc/integration/soc.py
- litex/soc/software/liblitespi/spiflash.c
- litex/tools/litex_sim.py
The PR is related to this changes: https://github.com/litex-hub/litespi/pull/57
So the LiteSPI PR should be merged before this one
> litex: adding litespi to simulation, making litespi compatible with new implementation

- litex/soc/cores/cpu/rocket/boot-helper.S
- litex/soc/cores/cpu/rocket/core.py
- litex/soc/cores/cpu/rocket/crt0.S
Works, ~~but needs a bit of clean-up and streamlining before being pulled.~~
> Rocket SMP support

- litex/soc/software/libc/Makefile
- litex/soc/software/libc/missing.c
A few minor updates to picolibc integration
> Picolibc updates

- README.md
In addition to meson I had to install ninja for the picolibc update.
Not sure if it was just an issue on my system but wanted to flag it.
> Add ninja to toolchain setup

- litex/soc/cores/cpu/ibex/core.py
- litex/soc/cores/cpu/ibex/crt0.S
- litex/soc/cores/cpu/ibex/csr-defs.h
- litex/soc/cores/cpu/ibex/irq.h
- litex/soc/cores/cpu/ibex/system.h
- litex/soc/software/bios/isr.c
Take care of the module change in instantiation of Ibex core.
> Fix the support for Ibex.

- litex/build/sim/core/modules/xgmii_ethernet/xgmii_ethernet.c
This PR fixes various things about the initial xgmii_ethernet simulator module. There are corresponding changes to be made on the LiteEth side, for which I will also release a PR. Until then this is a draft PR.
- sim/xgmii_ethernet: switch internal bus representation to 32 bits
The xgmii_ethernet module used to represent internal XGMII interface signals using 64-bit signals. While this is not incorrect per se, it makes a standards-compliant implementation of the XGMII significantly harder in the long run. This is because XGMII fundamentally is defined as a 32-bit bus, and thus has constraints in relation to that bus width. For example, it is specified that packets may only ever start on the XGMII lane 0, that is the first octet of a 32-bit XGMII bus word. Hence, to properly handle a XGMII …
> sim/xgmii_ethernet: fix XGMII start of frame char handling and RX IFG insertion (with optional DIC)

- litex/soc/cores/cpu/vexriscv/core.py
> Defer adding the CFU instance until cpu.do_finalize().

- .github/workflows/ci.yml
- litex_setup.py
The `amaranth-lang/amaranth` repository has a compatibility shim for the `nmigen` package, so downstream code like Minerva works without modification.
> litex_setup: nMigen has been renamed to Amaranth HDL

- litex/build/efinix/common.py
- litex/build/efinix/efinity.py
- litex/build/efinix/ifacewriter.py
- litex/build/efinix/platform.py
Several fixes to get HyperRAM Tristate bus to work
> Efinix titanium support

- litex/soc/cores/cpu/zynq7000/core.py
For zynq, **processing_system** IP may be configured using an **XCI** file, a preset shipped with vivado or an external TCL file.
This PR add support to use TCL file for boards without official preset (shipped with **vivado**).
This file may be produce using **block design**  -> **Customize block** -> **Presets** -> **Save Configuration**
> zynq7000: add TCL preset support

- litex/tools/litex_json2renode.py
This PR fixes a workaround applied earlier. Skipping all linker regions does break some configurations where e.g. regions have type `cached+linker`.
With these changes script will look at region base address and size, then if any region is included in another it will be skipped but if they overlap on each other script will be aborted since it's not supported by Renode.
FYI @mateusz-holenko
> tools/litex_json2renode: Add more restrictions to memory regions filter

- litex/soc/software/bios/boot.c
- litex/tools/litex_json2dts_linux.py
This helps fix most of openrisc/or1k_marocchino#23.  Linux now boots to userspace but crashes, from here is is likely not a litex issue.
> Or1k marocchino linux fixes

- litex/build/xilinx/platform.py
- litex/build/xilinx/yosys_nextpnr.py
requires a related PR: https://github.com/litex-hub/litex-boards/pull/338
> Add yosys+nextpnr toolchain support

- litex/soc/cores/clock/lattice_ecp5.py
Scans the delay value from zero to the required value every time .value signal changes.
Tested on a private design.
Looks like may be useful here https://github.com/enjoy-digital/versa_ecp5_ethernet/blob/master/ecp5rgmii.py ?
> clock/lattice_ecp5: add ECP5 dynamic delay DELAYF primitive support

- litex/build/xilinx/yosys_nextpnr.py
add xc7z010clg400-1 and xc7z400clg-1 devices
> litex/build/xilinx/yosys_nextpnr: adding zynq7 and xc7z010 & xc7z020 support

- litex/build/efinix/efinity.py
- litex/build/generic_platform.py
- litex/soc/integration/builder.py
Feel free to not merge it.
At least it won't get lost here.
> Copy files

- litex/soc/cores/video.py
I tested this only on one target. It should be tested with at least another one.
> video: align hsync and vsync generated by the vtg

- litex/soc/cores/cpu/zynqmp/core.py
this PR add:
- data_width for interface. ZynqMP AXI master may be configured in 32/64/128 bits
- the id interface is provided as parameter and no more deducted by axi list size. Some board may use by default LPD (**maxi_gp2**).
- fix **maxi_gp2** clock name: *LPD* instead of *FPD*
For *ZCU102* to be coherent with default configuration these modifications are required since **maxi_gp0** and **maxi_gp2** are enabled with a width of 128 and *alinx AXU2CGA* has, by default, only LPD (ie **maxi_gp2**) enabled.
Of course, for LiteX bios, these modifications may be less important: the PS configuration is done directly by the firmware. But when Linux is used in PS side, these configurations are done by FSBL (aka uboot SPL) and requires to export **psu_gpl_init.c**, updates uboot configuration, …
> zynqmp/core: allows users to select data_size and interface id

- litex/soc/cores/xadc.py
Although for 'standard' UltraScale+ just letting Vivado upgrade
SYSMONE1 to SYSMONE4 works, it doesn't for the Zynq because the
default SIM_DEVICE not matching up creates a fatal DRC when
creating bitstream.
So instead we add separate classes for UltraScale, UltraScale+ and
Zynq UltraScale+, each instanciating the right blocks, with the
right params. Also we only create the VCCPSINTLP//VCCPSINTFP/VCCPSAUX
for the Zynq UltraScale+.
> cores/xadc: Improve support for Zynq Ultrascale+

- litex/build/tools.py
- litex/soc/integration/soc.py
- there is "vp" file extension for encrypted Verilog
- there is no word "supporteds"
> Minor fixes

- litex/soc/cores/jtag.py
> cores/jtag/XilinxJTAG: Add support for Zynq UltraScale+

- litex/soc/cores/cpu/firev/__init__.py
- litex/soc/cores/cpu/firev/boot-helper.S
- litex/soc/cores/cpu/firev/core.py
- litex/soc/cores/cpu/firev/crt0.S
- litex/soc/cores/cpu/firev/irq.h
- litex/soc/cores/cpu/firev/system.h
This is adding the FireV CPU which is written in Silice and described in details here: https://github.com/sylefeb/Silice/blob/draft/projects/fire-v/doc/fire-v.md
> Silice FireV

- litex/build/gowin/gowin.py
- litex/build/gowin/programmer.py
1. update only target for Gowin platform and test with **sipeed_tang_nano_9k** target board.
2. test with **oss-cad-suite** (from yosysHQ) under **Powershell** and also **WSL** (ubuntu 20.04).
3. test with both Gowin **programmer_cli** and **openFPGALoader** programmer for **sipeed_tang_nano_9k** target board.
> for windows/(powershell and WSL) support

- litex/build/efinix/programmer.py
The original programmer only supports a single hexlified bitstream format, this one also supports binaries programming
> [enh] added efinix atmel programmer

- litex/soc/software/liblitedram/sdram.c
It depends on https://github.com/enjoy-digital/litedram/pull/300
> Make memtest work with 4x DQ / DQS ratio

- litex/soc/cores/cpu/blackparrot/core.py
Same issue as:
https://github.com/enjoy-digital/litex/pull/1245
> Fix demo.bin compilation for BlackParrot

- litex/soc/cores/video.py
Add a new parameter (drive_both), defaulting False, that will
drive data#_n as well as data#_p (and with the inverse of data#_p)
VideoHDMI10to1Serializer is similarly extended.
Existing users of these should be unaffected (tested that with
the Radiona ULX3S, which was not impacted).
> cores/video: VideoHDMIPHY: enable driving both + and - diff outs

- litex/soc/cores/cpu/cva6/__init__.py
- litex/soc/cores/cpu/cva6/boot-helper.S
- litex/soc/cores/cpu/cva6/core.py
- litex/soc/cores/cpu/cva6/crt0.S
- litex/soc/cores/cpu/cva6/csr-defs.h
- litex/soc/cores/cpu/cva6/irq.h
- litex/soc/cores/cpu/cva6/system.h
- litex_setup.py
- test/test_cpu.py
The CVA6 code is https://github.com/suppamax/pythondata-cpu-cva6.
I added a SystemVerilog wrapper around CVA6, to glue the CPU, PLIC, CLINT and debug module together.
> add cva6 cpu

- litex/build/lattice/oxide.py
Signed-off-by: gatecat <gatecat@ds0.me>
> oxide: Fix ES postfix on device name

- test/test_axi_lite.py
- rename test_wishbone2axi2wishbone to test_wishbone2axilite2wishbone for clarity
- extend it for 64b data width
- extend test_axilite2axi2mem for 64b data width
> Improve AXI Lite tests

- litex/build/xilinx/f4pga.py
This PR fixes F4PGA building flow for Xilinx target, which was broken after GenericToolchain introduction.
Signed-off-by: Rafal Kolucki <rkolucki@antmicro.com>
> build/xilinx: Fix F4PGA building flow

- litex/soc/cores/cpu/naxriscv/core.py
I found both options useful.
@Dolu1990
> Naxriscv: Add two more argparser options for devs

- litex/soc/cores/video.py
As mentionned in issue #1439 *blue* and *red* channels, for **DVI/HDMI**, are swapped.
This PR:
- replaces classes's `c2d` by a global dict to reduce code dupplicate.
- reorders colors
- the color iteration is done using the global dict and `items()` to directly have color and channel
- test  for *TMDS* with/without sync channels, is now based on channel id instead of color name.
Another PR will be opened ASAP for litex_boards if pn_swap must be updated accordingly.
> soc/cores/video: swap red and blue channel

- litex/tools/remote/comm_udp.py
Occasionally we see problems with litex_server failing when it misses a single EtherBone UDP packet.
This PR adds some retransmission logic, so we retry a couple of times before giving up.
> Added retransmission logic for EtherBone UDP reads.

- litex/soc/interconnect/axi/axi_full.py
> interconnect/axi/axi_full: Fix AXIDownConverter compilation.

- litex/build/vhd2v_converter.py
As of April 2022, GHDL can output Verilog directly without the use of yosys. This simplifies the build environment for flows that simply want to convert VHDL to Verilog.
Note that this removes some arguments from ghdl that are not required to synthesise ether Microwatt or neorv32.
> vhd2v: Use GHDL directly

- litex/soc/cores/cpu/openc906/core.py
The default ethmac section address conflicts with main_ram defined for openC906.
Add a custom position of ethmac to the memory map, which directly follows the internal APB.
Also fix the start address of checked IO region from 0xa0000000 to the full Region 1 in sysmap.h, and add plic and clint sections like other RISC-V CPU cores (although they're internal to the CPU and won't be usable by LiteX).
> cpu/openc906: add ethmac to memory map and misc changes

- litex/tools/remote/comm_udp.py
This commit fixes a bug where, retry after a timeout would send another request, but wouldn't discard a response that arrived after the timeout.
Retries worked, but only for dropped packets. If a response arrived, but `socker.recvfrom` timed out, the response would still be put in receive queue. Later, after sending another request, the client would try to read from the socket and would find a response. But this response would be for the old request.
This way, request/response pairs would get misaligned and stop working properly.
This commit adds read numbering (writes do not have responses). Numbering is achieved by utilizing the fact that responses to Etherbone reads are actually writes to an address specified in a request. This way, we don't need to extend Etherbone protocol, in fact …
> remote/comm_udp: Fix Etherbone timeout errors

- litex_setup.py
> litex_setup: Update Microwatt to latest

- .github/workflows/ci.yml
> github: Use distibution compilers for riscv and or1k

- litex/build/parser.py
With the new `LiteXArgumentParser` some of arguments are sent to`argparse.ArgumentParser` near `parse_args()` call.
When a targets uses set_defaults, these defaults values are lost. For example, `digilent_arty_z7` set `zynq7000` as the default *CPU* but when one didn't provides `--cpu-type=zynq7000` the default `vexriscv` is used instead.
This PR overrides `default_values` method, store locally dict containing defaults args/values. These are applied after parser completely filled but before `parse_args` call resulting to the correct behaviour.
> build/parser: overrides set_defaults and applying default values just before args_parse()

- litex/build/altera/quartus.py
This pull request fixes an issue where adding IP files causes an error when using the Quartus build platform.
> build/altera: Fix IP integration

- litex/soc/cores/clock/intel_stratix5.py
This pull request adds the `StratixVPLL` class. The parameters are referenced from the SV53001-4.1 datasheet.
> clock/intel: Add Stratix V PLL parameters

- test/test_cpu.py
They appear to be passing CI again.
> test: Reinstate microwatt and neorv32

- litex/soc/cores/clock/gowin_gw1n.py
The PLL configuration for **Gowin** FPGA search for the first combinaison of `IDIV`, `ODIV` and `FDIV` compatible with *VCO* limitations, and margin, to generate user's requested frequency. But for a `clkin` and `clkout` couple more than one set of parameters may respect criterions.
For example with a 27MHz input frequency and to generate a 96MHz these set are possible
| `IDIV` |  `ODIV` | `FDIV` | real freq (Hz) | difference (Hz) |
|---------|------------|----------|--------------------|---------------------|
|7         |  8          |   25     | 96428571.42857143 | 428571.4285714328 |
| 9        | 8           |   32     | 96000000.0               | 0.0                             |
As shown the best configuration isn't the first, so with current implementation the PLL produces a …
> soc/cores/clock/gowin_gw1n: improve VCO configuration

- .github/workflows/ci.yml
- MANIFEST.in
- setup.py
This PR does a few minor packaging changes:
- simplify MANIFEST.in
- Add readme information to setup.py
- Fix classifier for pypi / to pass twine check
And a few minor CI changes:
- grab python from standard action
> Small packaging and CI changes

- litex/soc/cores/pwm.py
Also do minor changes to PWM module to allow reuse.
> soc/cores/pwm: Add MultiChannelPWM core reusing PWM module.

- litex/soc/interconnect/avalon.py
- test/test_avalon.py
Opening this PR as a RFC.
Goal is to implement an AvalonMM Master to Wishbone slave Bridge.
> WIP AvalonMM interface and Avalon to Wishbone Bridge

- litex/soc/cores/video.py
for low spec/embedded systems.
> Add low res video modes

- litex/gen/fhdl/verilog.py
ASIC targets can't set a reg to a known value on boot, so for more accurate simulations it would be nice to have an option in the platform to specify generating the verilog without 'reg' initializers. The presence of these initializers can mask problems in simulations with X-prop that can lead to missing explicit reset conditions.
The PR is coded so this should have no effect on users who don't need this feature.
thanks!
> add an option to generate without reg initializers (asic targets)

- litex/tools/litex_json2dts_linux.py
> tools/litex_json2dts_linux: fix missed sdcard_ references

- litex/soc/interconnect/wishbone.py
When using VexRiscv-SMP with a 64-bit data bus (required by FPU) and keeping the system bus as 32 bit, burst information would previously get lost in the downconverter, leading to poor performance.
See also zeldin/litehyperram#1
> interconnect/wishbone: Add linear burst support to DownConverter

- litex/gen/fhdl/namer.py
- litex/gen/fhdl/verilog.py
- litex/gen/sim/vcd.py
- litex/soc/interconnect/stream.py
- Improve/Refactor namer.py.
- Use DUID in ClockDomainCrossing for deterministic generation.
> Verilog improvements.

- litex/soc/integration/soc.py
- litex/soc/interconnect/axi/axi_full.py
- litex/soc/interconnect/axi/axi_lite.py
This PR mainly adds code to propagate bus.address_width.
It also fix a multiple read to CSR
> Add AXI/AXILite 64 bus support

- litex/soc/cores/cpu/fazyrv/core.py
Hi,
Thank you for adding FazyRV support to LiteX. Really appreciate it. I'll keep you posted on any updates regarding the interrupt variants.
> FazyRV: Fix minor typo in path check 

- litex/soc/cores/spi/spi_mmap.py
- litex/soc/interconnect/wishbone.py
- test/test_spi_mmap.py
This PR contains:
* CSR adjustments to ease driver development
* new tests which demonstrate some issues and changes to fix them
* new features with tests: 24 bit slot support and a cs_wait timer
> SPIMMAP bug fixes and new features

- litex/build/xilinx/yosys_nextpnr.py
This was supposed to be a format string
> yosys+nextpnr: fix error message

- litex/soc/cores/cpu/naxriscv/core.py
See #1922.
Can be merged if it pass the regressions
> cpu/naxriscv update mBus to preserve memory accesses offset

- litex/build/efinix/ifacewriter.py
This adds low level support for the reconfiguration interface (sometimes also called remote update by Efinix)
> Add support for the Efinix reconfiguration interface

- litex/soc/interconnect/axi/axi_lite.py
This is a fix for the case when AWVALID and WVALID signals are not asserted at the same clock cycle (a valid case according to the AXI/ACE protocol specification, also for the Lite version). The problem was discovered with the use of Xilinx AXI Interconnect IP which asserts WVALID one cycle later after AWVALID assertion.
> The case when AWVALID and WVALID are not asserted at the same cycle

- litex/soc/cores/watchdog.py
- litex/soc/integration/soc.py
- litex/soc/integration/soc_core.py
- litex/tools/litex_json2dts_zephyr.py
add a watchdog feature for LiteX
driver for zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/74693
@m-byte
> core: add watchdog feature

- litex/build/openocd.py
- litex/soc/integration/soc.py
- litex/soc/software/bios/helpers.c
After https://github.com/litex-hub/litespi/pull/70 is merged, the function to add a spi ram should be added to soc.py.
> soc: add add_spi_ram function

- litex/soc/software/bios/boot.c
this fixes the warnings, when compiling.
> bios: boot.c: fix warnings

- litex/build/lattice/diamond.py
- litex/build/lattice/platform.py
- litex/soc/cores/jtag.py
Allows adding
- extra tcl commands
- extra strategy
- extra lattice's IPs file
Note: jtag modoification needs to be tested with nextpnr (not done now).
> Build diamond addition

- litex/build/efinix/ifacewriter.py
This enables instantiation of the Efinix single event upset interface.
> Add efinix SEU interface

- litex_setup.py
> Fix litex_setup.py OHCI clone

- litex/soc/cores/cpu/naxriscv/core.py
Hello,
Following discussions in #2182, here is the PR that could fix it.
Regards,
> Fix issue enjoy-digital#2182

- litex/build/efinix/programmer.py
add flash function for the efinix
programmer via jtag_bridge_new.
> build: efinix: programmer: add flash function

- litex/build/efinix/common.py
- litex/build/efinix/dbparser.py
- litex/build/efinix/ifacewriter.py
- litex/build/efinix/platform.py
- litex/soc/cores/jtag.py
> build: efinix: add Topaz support

- litex/soc/cores/uart.py
> cores: uart.py: slice data in fsm run

- litex/build/openfpgaloader.py
To implement `./litex_m2sdr.py --reset`
> OpenFPGALoader wrapper: add support for `reset` command

- litex/soc/interconnect/axi/axi_lite_to_wishbone.py
use axi bus one cycle earlier.
> axi: Wishbone2AXILite: increase speed by one cycle

- litex/build/colognechip/common.py
- litex/build/colognechip/platform.py
These are required for SD card interface and also Ethernet to work.
Note: Will create PR in litex-boards that is requiring these changes
> Gatemate: handle SDRInput, SDROutput and SDRTristate

- litex/soc/cores/cpu/naxriscv/core.py
- litex/tools/litex_json2dts_linux.py
- Add support for L1/L2 cache topology for NaxRiscv
- Fix DT naming for USB OHCI
- Fix L1$ size reporting for all configs
- Add L2 cache to DTS if present in config
- Add local MAC address to ethernet if given
> Various fixes to DTS generation script

- litex/soc/software/liblitesdcard/sdcard.c
the clock divider uses a counter, so we are no
longer limited to powers of 2.
also implement https://github.com/enjoy-digital/litesdcard/pull/39 in software to show the resulting value.
> software: litesdcard: remove limitations for clk divider

- litex/soc/software/liblitesdcard/sdcard.c
- litex/soc/software/liblitesdcard/sdcard.h
add support for x1, x4 and x8 modes.
in connection with https://github.com/enjoy-digital/litesdcard/pull/38
> software: litesdcard: add support for changing phy modes

- litex/soc/cores/cpu/vexiiriscv/core.py
set riscv extentions in arch based on VexiiRiscv.vexii_args
> cpu: vexiiriscv: set riscv extentions in arch based on VexiiRiscv.vexii_args

- litex/build/sim/core/modules/clocker/clocker.c
- litex/build/sim/core/modules/spdeeprom/spdeeprom.c
- litex/build/xilinx/vivado.py
- litex/soc/integration/soc_core.py
Hi,
This pull request contains a few miscellaneous fixes. Please review and apply.
Thanks,
Yousaf
> Fix a few small issues

- litex/soc/doc/__init__.py
- litex/soc/doc/csr.py
- litex/soc/integration/builder.py
- litex/soc/integration/export.py
- litex/soc/integration/soc.py
- litex/soc/software/bios/main.c
- litex/soc/software/include/hw/common.h
- litex/soc/software/liblitedram/sdram.c
- litex/soc/software/liblitesdcard/sdcard.c
> csr: fix and support ordering

- litex/soc/cores/video.py
With Gowin IDE using `ELVDS_OBUF` for true differential pins is fine and build end successfully.
But with `apicula` a `TLVDS_OBUF` must be used otherwise the build end with:
```bash
ValueError: Cannot place hdmi_data2_p_OBUF_O at IOB40A - it is a true lvds pin
```
This failure may be observed for the `sipeed_tang_nano_20k.py` target when `VideoGowinHDMIPHY` is enabled.
This PR adds an additional (and optional) CTOR's parameter to specify which type of primitive must be used:
- `ELVDS_OBUF` when `true_lvds == False` (default)
- `TLVDS_OBUF` when `true_lvds == True`
> soc/cores/video.py: VideoGowinHDMIPHY: allows to specify if _p/_n are true LVDS or if LVDS must be emulated

- litex/soc/software/liblitesdcard/sdcard.c
- litex/soc/software/liblitesdcard/sdcard.h
add support for cmd crc resp check
Needs: https://github.com/enjoy-digital/litesdcard/pull/47
> software: libsdcard: add support for cmd crc resp check
