enjoy-digital/litex

litex/soc/software/common.mak
Previously the flags were not actually set and the *.d files were never
actually generated.
=> soc/software/Makefile: Fix Makefile depend generation.

litex/soc/software/include/base/stdarg.h, litex/soc/software/libbase/console.c
Fixes #8.
```
int vprintf(const char *format, va_list ap);
The functions vprintf(), vfprintf(), vsprintf(), vsnprintf() are equivalent to
the functions printf(), fprintf(), sprintf(), snprintf(), respectively, except
that  they  are  called  with  a  va_list instead of a variable number of
arguments.
```
=> libbase: Adding missing vprintf function.

litex/soc/integration/soc_core.py, litex/soc/tools/remote/comm_udp.py, litex/soc/tools/remote/csr_builder.py, litex/soc/tools/remote/litex_client.py
* Provide the CSR data bus width in a constant.
* Allow the Etherbone objects to autocompleted in things like `IPython` and `bpython`.
=> Patches to make it easier to work with Etherbone

litex/build/tools.py, litex/soc/integration/builder.py, litex/soc/software/bios/Makefile
* Files are only modified when their contents change.
* Fix Makefile so bios is correctly rebuilt when dependencies change (but isn't otherwise).
=> Only require rebuild on actual changes

litex/soc/software/libbase/Makefile, litex/soc/software/libcompiler_rt/Makefile, litex/soc/software/libnet/Makefile
I previously fixed it for the bios, but not these libraries.
=> Fix Makefile dependency inclusion for other software.

litex/soc/tools/remote/csr_builder.py
=> Raise AttributeError.

litex/soc/cores/flash/spi_flash.py
Importing sb0's fix into litex.
=> WPI: -- spi_flash: fix bitbang with spi_width=1

litex/soc/integration/cpu_interface.py
* Using CLANG can set by using CLANG=1 or CLANG=0 in the environment.
* or1k continues to default to CLANG if environment is not net.
This change was clobbered by your merge in ff31959aea1e3815d95798996c3999f122314ae6
=> Allow using gcc for or1k.

litex/soc/integration/soc_core.py
So we can do a "soft reset" by jumping to this address.
Nothing currently provides this information. Discovered this when trying to use `reboot` on the MimasV2 which has a non-zero CPU_RESET_ADDR.
=> soc_core: Add CPU_RESET_ADDR as a constant.

litex/build/xilinx/vivado.py
The or1k doesn't have any verilog include paths added. This means the
code use to generate;
```tcl
synth_design -top top -part xc7a50t-csg325-2 -include_dirs {}
```
which causes Vivado to segfault with the following error;
```
Command: synth_design -top top -part xc7a50t-csg325-2 -include_dirs {}
Starting synth_design
Attempting to get a license for feature 'Synthesis' and/or device 'xc7a50t'
INFO: [Common 17-349] Got license for feature 'Synthesis' and/or device 'xc7a50t'
Abnormal program termination (11)
Please check 'build/netv2_base_or1k/gateware/hs_err_pid76959.log' for details
File "./make.py", line 82, in <module>
```
=> vivado: Fix segfault with or1k.

litex/boards/platforms/versaecp55g.py
This PR implements support for the [Lattice ECP5-5G Versa Development Kit](http://www.latticesemi.com/Products/DevelopmentBoardsAndKits/ECP55GVersaDevKit.aspx) platform.
I've not tested the code (especially pin mapping) apart from blinking one of the user_leds in a test module and running that on the board via .create_programmer(). DDR support and a proper SoC target might come in a future PR.
=> Add Versa ECP5-5G Platform.

README
Migen currently isn't a dependency for LiteX
=> remove Migen as requirement for LiteX from the quick start guide

litex/soc/software/libnet/tftp.c
Previously we would wait the same number of iterations as it took us to
receive the first data block after sending the request. When using the
build in tftp server in qemu, the first wait loop succeeds (and thus
breaks when 'i' is still 0.
Since the counter was never reset between the first and second data
block, under qemu the tftp_get call would fail before ever checking if
we have received the second block of data.
Now that we initialise 'i' to 12M, we ensure that we wait the same
amount of time for the second data block as it previously did for the
third (and subsequent) blocks.
=> Wait longer before giving up on the 2nd tftp block.

litex/soc/cores/cpu/lm32/core.py, litex/soc/cores/cpu/mor1kx/core.py, litex/soc/integration/soc_core.py
It is useful to support slightly different variants of the CPU
configurations. This adds a "cpu_variant" option.
For the mor1k we now have the default mor1k configuration and the
"linux" variant which enables the features needed for Linux support on
the mor1k.
Currently there are no variants for the lm32, but we will likely add a
"tiny" variant for usage on the iCE40.
=> cpu: Adding "variant" support.

litex/boards/platforms/kcu105.py, litex/soc/cores/xadc.py, litex/soc/tools/litex_term.py, litex/soc/tools/remote/litex_server.py
I ran a script that shouldn't have missed any tab in the python source files.
=> Fix all remaining indentation issues in python code

litex/soc/integration/cpu_interface.py
This was preventing constants from getting added to the csr.h header file.
=> cpu_interface: Fix indenting on constant generation.

litex/soc/integration/soc_core.py
This was preventing constants from getting added to the csr.h header file.
=> soc_core: Don't fail if name is the same.

litex/soc/software/bios/boot.c, litex/soc/software/bios/main.c
Only including those header files in the litex firmware is the first step to
move the firmware parts of liteeth to the liteeth tree.
=> Include the ethernet related header files conditionally

litex/soc/software/bios/Makefile, litex/soc/software/bios/boot.c, litex/soc/software/include/net/tftp.h, litex/soc/software/libnet/tftp.c
Change TFTP server port from hard coded `PORT_OUT` in `libnet/tftp.c` to being a function parameter, supplied by `bios/boot.c`; allow `TFTP_SERVER_PORT` to be defined from compile environment to specify an alternative TFTP server port to try; if TFTP from alternative server port fails, try UDP/69 anyway before giving up.
=> BIOS: Support alternate TFTP server port

litex/gen/fhdl/specials.py
This is needed to specify timing constraints on some Lattice Diamond library specials, like the EHXPLLL.
To keep backwards compatibility we allow the directive to still be a single string. If it's not, we assume it's an iterable.
=> Allow for multiple synthesis directives in specials.

litex/boards/platforms/arty.py
pmod definitions should be in 'connectors' section of platform definition for the ARTY board.
=> platform/arty.py: Move Pmod definitions to 'connectors' section.

litex/soc/software/bios/boot.c
Modified flashboot() to skip copy to main ram if there is no main
ram, and instead execute in place out of SPI flash.  (For this to
work the linker .ld will also need to redirect references to be
inside the SPI flash mapping.)
=> WIP - BIOS: Flashboot without main ram

litex/build/lattice/diamond.py, litex/build/sim/core/Makefile, litex/build/sim/verilator.py
When dealing with multiple Verilog sources in a design we must explicitly state which module is the top of the design. This change ensures such a selection is made when building designs using Verilator and Lattice Diamond.
While the changes have been tested to work, I am not sure if this is the right way to go about this. Please review carefully.
=> Top module selection (for Verilator and Diamond)

litex/soc/interconnect/axi.py
This change introduces an AXI4Lite to CSR bridge. Hopefully it will
become extended in the future with full AXI support and more structures
(Wishbone bridge, interconnect, ...). For now this will do.
The bridge has been simulated (and includes an FHDL testbench) and
tested in hardware (on a Zynq 7020).
=> Preliminary AXI4Lite support: CSR bridge

litex/boards/platforms/tinyfpga_b.py
Self-explanatory and bikeshedding.
As has been done in the past w/ Migen, users should _opt into_ using connectors/not-dedicated pins as `_io` using `add_extension`, rather than having non-dedicated pins assigned static functions by default. 
I prefer to add default pin assignments in the board namespace that users can assign to the board via `add_extension`. This permits maximum flexibility for users who need the I/O pins for something else, as well as providing default pins for those who want to use the first two I/O pins as a serial port.
=> platforms/tinyfpga_b: Move serial peripheral out of default I/O, make it

.travis-build-socs.sh, .travis.yml, README, environment.yml
This CL adds a simple "conda environment" example. It then tests this on Travis. This checks that all the targets at least compile. You can see [example output here](https://travis-ci.org/mithro/litex/builds/348804944) or below;
=> Adding conda environment and simple travis build

litex/soc/integration/soc_core.py
Before;
```
"/usr/local/lib/python3.5/dist-packages/litex-0.1-py3.5.egg/litex/soc/integration/soc_core.py",
line 258, in get_csr_dev_address
return self.csr_map[name]
KeyError: 'core'
```
Now;
```
File "XXXX/github/enjoy-digital/litex/litex/soc/integration/soc_core.py", line 259, in get_csr_dev_address
return self.csr_map[name]
KeyError: 'ddrphy'
The above exception was the direct cause of the following exception:
...
File "XXXX/github/enjoy-digital/litex/litex/soc/interconnect/csr_bus.py", line 199, in scan
mapaddr = self.address_map(name, None)
File "XXXX/github/enjoy-digital/litex/litex/soc/integration/soc_core.py", line 269, in get_csr_dev_address
) from e
RuntimeError: Unable to find ddrphy in your SoC's csr …
```
=> Improving error message when csr name is not found.

litex/boards/platforms/arty.py
The arty platform connectors weren't hooked up to the SOC, also they were in an incompatible syntax.
I've hooked them up, but lost the IOStandard field, as AFAICT thats not supported for connectors at this time.
=> Fix for missing connectors for arty boards

litex/soc/software/bios/Makefile
With this patch, litex is able to build the netv2-soc project on Windows.
Currently, the BIOS builds just fine on Windows, but afterwards tries to run
`chmod`.  This command does not exist on Windows, and is unnecessary.
Add a conditional guard to prevent this command from running on Windows.
=> soc: bios: fix windows build

litex/soc/cores/cpu/vexriscv/core.py, litex/soc/integration/soc_core.py
Enable debug support for the vexriscv.
The first patch pulls a newer version of vexriscv from upstream, which incldues a version of the verilog file with debug support enabled.
The second patch adds the CSRs to the CPU if instantiated with cpu_debugging=True.
The third patch adds cpu_debugging as an optional flag to SoCCore, allowing the user to instantiate a core with debug support enabled.
The final patch adds a reset line to the UART, which is needed when resetting the CPU.
=> Enable support for vexriscv debugging

litex/soc/tools/vexriscv_debug.py, setup.py
This patch adds a new tool: vexriscv_debug
This tool is used to go between the spinalhdl openocd branch (https://github.com/SpinalHDL/openocd_riscv/) and the wishbone bridge.
Documentation on how to use it is pending, but basically boils down to running this tool (and litex_server), then doing:
```sh
git clone https://github.com/SpinalHDL/openocd_riscv.git
cd openocd_riscv
./bootstrap
./configure --enable-dummy
make
./src/openocd -c 'set VEXRISCV_YAML [path-to-litex]/litex/soc/cores/cpu/vexriscv/verilog/cpu0.yaml' -f tcl/target/vexriscv_sim.cfg
```
=> Add Vexriscv debug bridge

litex/soc/cores/cpu/vexriscv/core.py
The REFRESH register accepts an 8-bit address and determines which
register to refresh.  Since there are only two addresses currently in
use, this register can be either 0x00 or 0x04.
A refactor replaced the compare with one that checked for any 0 bits.
Since both 0x00 and 0x04 have 0 bits, this check always evaluated as
true, causing the logic to always refresh the CORE register.
Replace this check with an explicit check for 0x00.
=> vexriscv: debug: fix reading DATA register

litex/soc/tools/vexriscv_debug.py
CSR access widths can be different from register widths.  8-bit
registers are common.
The runtime-generated `read()` and `write()` functions handle this
mapping correctly.  When direct register accesses are handled, this
mapping is lost.
Use the accessor functions rather than directly accessing the memory
addresses, so that we work on platforms other than 32-bit-wide.
=> vexriscv_debug: use csr read()/write() accessors

litex/soc/software/bios/boot.c
I assume this is an oversight, but without using `#ifdef L2_SIZE` to gate `flush_l2_cache()`, I would get undefined symbol errors when attempting to link a BIOS on systems without L2 Cache (such as `tinyfpga`). This commit fixes my issues.
=> software/bios: Gate flush_l2_cache() if L2 Cache isn't present.

litex/soc/cores/cpu/lm32/core.py, litex/soc/cores/cpu/lm32/verilog/config_lite/lm32_config.v, litex/soc/integration/builder.py, litex/soc/integration/cpu_interface.py, litex/soc/software/libcompiler_rt/Makefile
I have split the `lm32` `minimal` variant into 2 variants, called `lite` and `minimal`:
* Same as previous `minimal`, except now with 2kb I-cache (16 bytes per line, 128 lines). This is suitable for running a program from SPI flash without the CPU spending most time waiting for instructions. No data cache, so all RAM references are 2 cycles.
* Same as previous `minimal`, except multiply and divide disabled, barrel shift and sign extend still present. This reduces resources used for debugging purposes.
---
This also serves as a watered-down version of a [PR](https://github.com/mithro/litex/pull/2) on @mithro's litex branch; changing compiler/CPU flags based on variant is now supported!
I have confirmed both variants to boot to the BIOS by testing on tinyfpga.
---
`mulsi3.c` was compiled …
=> Add lm32 "lite" variant, remove mult/div from "minimal" and update compiler flags accordingly.

litex/soc/integration/builder.py
The `litex-buildenv` firmware linker script at present depends on `main_ram` being present, for example. This Makefile variable allows us to choose the proper linker script to use in case we boot from spi flash instead.
=> Add COPY_TO_MAIN_RAM generated Makefile variable to distinguish systems with/without "main_ram" region.

litex/soc/integration/cpu_interface.py, litex/soc/software/include/hw/common.h
This patchset replaces MMPTR() with csr_readl() and csr_writel().  These functions are defined as inline, unless `CSR_ACCESSORS_DEFINED` is defined when `csr.h` is included.
This name can be changed, if desired.
This can be used with `etherbone.c` available at https://github.com/xobs/wishbone-adapter/
An example of using this is to start up `litex_server` and build the following file in `dna.c`:
```c++
#define CSR_ACCESSORS_DEFINED
#include <stdio.h>
#include "csr.h"
#include "etherbone.h"
static struct eb_connection *g_eb;
void csr_writel(uint32_t value, uint32_t addr) {
eb_write32(g_eb, value, addr);
}
uint32_t csr_readl(uint32_t addr) {
return eb_read32(g_eb, addr);
}
int main(int argc, char **argv) {
g_eb = eb_connect("127.0.0.1", "1234", 0);
printf("DNA ID: %lld\n", dna_id_read()); …
```
=> Use csr accessors when generating `csr.h`

litex/boards/platforms/ice40_hx8k_b_evn.py
Adding a new board preemptively so that `litex-buildenv` platforms can [inherit](https://github.com/timvideos/litex-buildenv/issues/28) from `litex` platforms in the future.
=> build/platforms: Add ice40_hx8k_b_evn from Migen.

litex/build/sim/core/modules/serial2console/serial2console.c
This fixes an issue when running with the HDMI2USB firmware which
expects \r\n to come from the UART.  Since the verilator adapter
is just sending \n commands cannot be executed.
Also, one minor whitespace cleanup. (could remove if needed)
=> sim: serial: Send '\r\n' instead of just '\n'

litex/soc/cores/uart.py
On the iCE40 FPGA, adding buffering allows the SyncFIFO to be placed in
block RAM rather than consuming a large amount of resources.
=> uart: Enable buffering the FIFO.

litex/build/xilinx/vivado.py
When using Yosys for synthesis, still need Vivado for place and route.
=> litex/build: Always run Vivado.

litex/soc/cores/cpu/picorv32/core.py, litex/soc/software/libbase/crt0-picorv32.S
This PR adds the following features to the PicoRV32 core:
* Refactor PicoRV32's `core.py` file to support variants.
* Make sure IRQ vector is always located 16 bytes after the reset vector (was hardcoded to `0x00000010`).
* Clear `.bss` in `crt0` before running main program (required if using FPGA RAM that doesn't clear itself when a bitstream is loaded, such as up5k's `SPRAM`, or ASICs :))
* Emulate support for a relocatable `IRQ` vector; required for `fupy`. I use the `q2` register to hold the "true" IRQ vector location.
=> PicoRV32 Enhancements

litex/build/sim/core/Makefile
The --thread option must be provided with a value or the build will fail.
=> build/sim/verilator: don't use --threads when $(THREADS) is unset

litex/build/lattice/icestorm.py
Fixes the following error;
```
make[1]: Leaving directory `/home/travis/build/mithro/litex-buildenv/build/ice40_hx8k_b_evn_base_lm32.lite/software/stub'
File "./make.py", line 164, in <module>
main()
File "./make.py", line 148, in main
vns = builder.build(**dict(args.build_option))
File "/home/travis/build/mithro/litex-buildenv/third_party/litex/litex/soc/integration/builder.py", line 171, in build
toolchain_path=toolchain_path, **kwargs)
File "/home/travis/build/mithro/litex-buildenv/third_party/litex/litex/soc/integration/soc_core.py", line 389, in build
return self.platform.build(self, *args, **kwargs)
File "/home/travis/build/mithro/litex-buildenv/third_party/litex/litex/build/lattice/platform.py", line 29, in build
return self.toolchain.build(self, …
```
=> lattice/icestorm: Add toolchain_path so it doesn't end up kwargs.

litex/soc/software/libbase/crt0-picorv32.S
Self-explanatory, this mirrors PR #106 , except for `picorv32` :).
=> libbase/crt0-picorv32: Add support for .data sections.

litex/soc/interconnect/stream.py, litex/soc/interconnect/wishbone.py
* Allow wishbone.SRAM to support non-32bit wishbone widths.
* Pass extra arguments to Record when creating an Endpoint.
=> Two small fixes

litex/build/lattice/trellis.py
Before being able to program the board (e.g., with openocd), one
would have to convert the bitstream file to .svf using a python
script included with the source trellis distribution. However, the
trellis 'ecppack' utility can now generate .svf formatted bitstream
directly.
=> build/lattice/trellis: generate bitstream directly in svf format

litex/soc/interconnect/axi.py
Data width assertion should require AXI and Wishbone width to be
equal, regardless of the actual value (e.g., 32 or 64).
Also, use "axi.address_width" instead of hard-coded "32" for
_[read|write]_addr signals (since we already asserted that it
should be 32).
=> soc/interconnect/axi: address length cleanup

litex/soc/software/bios/main.c
Small boards like those with ice40s won't have main ram, so the bios fails to build.
=> Add ifdef check for MAIN_RAM_SIZE

litex/build/altera/common.py, litex/build/altera/quartus.py
Contributing to make support for Altera Cyclone V:
- added reset synchronizer;
- changes to make top level assigment in .qsf file with build name instead of always using "top"
=> Changes for litepcie support for Altera Cyclone V

litex/utils/litex_server.py
In some cases, it can be useful to bind to "0.0.0.0" instead of "localhost".
While adding bind address support, parameters passing has also been refactored to ease adding parameters in the future.
=> litex_server: refactor parameters and to allow setting bind address

litex/build/sim/core/sim.c, litex/build/sim/core/veril.cpp, litex/build/sim/core/veril.h
Required when DUT is using plusargs. Prevents Verilator simulation
from crashing with "Verilog called $test$plusargs or $value$plusargs
without testbench C first calling Verilated::commandArgs(argc,argv)".
=> build/sim/core: Initialize Verilator commandArgs

litex/soc/cores/cpu/vexriscv/core.py
This adds two additional variants of VexRiscv CPU: `full` and `full_debug` with CsrPlugin configured in 'all' mode, supporting ecall instruction.
=> Add full and full_debug CPU variant of VexRiscv

litex/tools/litex_server.py
Some flags are only available on certain platforms.  Verify these flags
exist prior to using them when opening a socket.
The latest patch doesn't work anymore on Windows.  This fixes that.
See
https://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t
for more information
=> litex_server: check socket flags exist before using them

litex_setup.py
When in development mode install the packages in the user directory using the
--user flag from pip. This allows to install and run without the need for root
access.
=> Install development packages in the user directory

doc/BIOS.md, doc/Firmware.md, doc/Soft-CPU.md, doc/pull-docs-from-buildenv-wiki.sh, litex/soc/cores/cpu/lm32/core.py, litex/soc/cores/cpu/minerva/core.py, litex/soc/cores/cpu/mor1kx/core.py, litex/soc/cores/cpu/picorv32/core.py, litex/soc/cores/cpu/vexriscv/core.py, litex/soc/integration/soc_core.py, test/test_targets.py
* Fixes #159
* [Documentation of Soft-CPU types and variants](https://github.com/mithro/litex/blob/cpu-docs/doc/Soft-CPU.md)
* [Documentation of Firmware types](https://github.com/mithro/litex/blob/cpu-docs/doc/Firmware.md)
The documentation is pulled from the [LiteX-BuildEnv Wiki](https://github.com/timvideos/litex-buildenv/wiki).
=> Standardizing `cpu_variants` and adding lots of documentation

litex/soc/software/bios/boot.c, litex/soc/software/bios/linker.ld, litex/soc/software/bios/main.c, litex/soc/software/include/hw/common.h
Enable future support for 64-bit CPU models: "unsigned long" matches the native architecture address size, unlike "unsigned int" which is fixed at 32 bits and therefore can't store a 64-bit address.
PS. Also bump tapcfg submodule after applying https://github.com/enjoy-digital/tapcfg/pull/1
=> software: use "unsigned long" for address values, also 8-byte alignment

litex/soc/cores/cpu/vexriscv/core.py
Yosys was optimising the 1'bx here very eagerly (but correctly) and breaking the CPU as these signals were floating. Tieing explicitly to 1'b0 fixes this.
=> vexriscv: Fix some floating signals

litex/soc/integration/cpu_interface.py, litex/soc/software/include/hw/common.h
When generating arch-specific include files (generated/[mem|csr].h)
ensure address literal defines are suffixed by 'L', denoting their
'unsigned long' type. This inhibits compiler warnings when values
computed based on these constants are cast to pointers.
Also ensure csr_[read|write][b|w|l]() function declarations have
'unsigned long' address arguments.
Finally, restore the correct (32-bit, (unsigned *)) expected
behavior of the MMPTR() macro, inadvertently converted to an
arch-specific sized access (unsigned long *) by commit 5c2b8685.
=> soc/integration/cpu_interface: more arch-specific address size fixes

litex/boards/targets/nexys4ddr.py
Commit 5f6e7874 added ethernet support, let's now also expose it via
the "--with-ethernet" command line argument.
=> boards/nexys4ddr: ethernet support fix-up

litex/tools/remote/comm_usb.py
The previous value -- 0xc0 -- is used by Windows to request WCID values, which causes the bridge to be completely unusable under Windows.  Furthermore, it breaks enumeration.  So we had to change it to 0x43/0xc3, which is not yet used.
This patchset also adds error printing when the user attempts to open a device when they don't have access to it.
=> Use 0x43/0xc3 for USB bridge magic packet

litex/tools/litex_sim.py
After LiteDRAM commit #50e1d478, an additional positional argument
('databits') is required by the PhySettings() constructor.
The value used here (32) will generate a 64MByte simulated SDRAM.
=> tools/litex_sim: restore functionality of '--with-sdram' option

.gitmodules, litex/boards/targets/nexys4ddr.py, litex/boards/targets/versa_ecp5.py, litex/build/sim/core/Makefile, litex/soc/cores/cpu/__init__.py, litex/soc/cores/cpu/rocket/__init__.py, litex/soc/cores/cpu/rocket/core.py, litex/soc/integration/soc_core.py, litex/soc/software/bios/boot-helper-rocket.S, litex/soc/software/bios/isr.c, litex/soc/software/bios/main.c, litex/soc/software/bios/sdram.c, litex/soc/software/include/base/irq.h, litex/soc/software/include/base/system.h, litex/soc/software/libbase/crt0-rocket.S, litex/soc/software/libbase/system.c
Attn: @enjoy-digital Currently the generated-verilog submodule is at https://github.com/gsomlo/rocket-litex-verilog, but I think it might be better if you take it over and host the authoritative repository. Not sure how I can become a "fork" of yours, or simply nuke my copy and send you PRs if/when necessary :)
If you agree, and decide to set up an authoritative https://github.com/enjoy-digital/rocket-litex-verilog repo, I'd be happy to force-push a new set of commits for this PR pointing at it instead.
=> Experimental Support for 64-bit RocketChip

litex/boards/targets/nexys4ddr.py, litex/boards/targets/versa_ecp5.py
Fix pep8 E101 "indentation contains mixed spaces and tab" error.
=> litex/boards/targets: don't use tab for indentation

litex/soc/software/include/base/stdint.h
needed for some third party libraries to compile
=> update stdint.h to include c99 types

litex/boards/platforms/de1soc.py, litex/boards/platforms/de2_115.py, litex/boards/targets/de1soc.py, litex/boards/targets/de2_115.py
Add support for [Terasic DE2-115](https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&CategoryNo=139&No=502&PartNo=1) and [Terasic DE1-SoC](https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&No=836) boards.
The IS42S16320D-7TL 32Mx16 512Mb SDRAM chips are used in Terasic DE1-SoC and Terasic DE2-115
FPGA development boards, so https://github.com/enjoy-digital/litedram/pull/84 has to be applied to litedram.
=> Add support for Terasic DE2-115 and Terasic DE1-SoC boards

litex/soc/software/include/base/stdint.h
sorry, I found an issue after porting the library where the "char" type apparently is unsigned unless you explicitly add the "signed" specifier. 
This PR fixes that oversight. The library works now, so this fix is tested.
=> fix signed char type to be explicitly signed

litex/soc/software/libbase/libc.c
Remove optimizations targeted specifically at rv32 architecture,
allowing memcpy to work on all word sizes.
Since this is "only" the BIOS, it is also arguably better to
optimize for size rather than performance, given that control
will be quickly handed over to some other program being loaded.
=> software/libbase: memcpy: simple, arch-width agnostic implementation

litex/soc/integration/builder.py, litex/soc/integration/cpu_interface.py
There is [a script in litex-buildenv](https://github.com/timvideos/litex-buildenv/blob/master/scripts/generate-renode-scripts.py) that generates [Renode](https://github.com/renode/renode) platform based on litex configuration from the csv file generated by LiteX. Unfortunatelly, the file does not contain all the necessary information.
This PR adds generation of `shadow_base` and `flash_boot_address` constants to the csv file.
Additionally, it adds generation of `SHADOW_BASE` define to `mem.h`. It is not necessary for the script, but I added it for the symmetry.
=> Extend generated headers & csv

litex/boards/platforms/arty.py
Avoids need for STARTUPE2.  Config pins tristate after download by default, alternate works well through R262.
=> boards/arty : Add directly connected spi clk pin 

litex/soc/software/bios/main.c
While testing my Ethernet DMA, I renamed the `ethmac` module to `ethmac_dma` so that it wouldn't be used from the BIOS, but I got an undefined reference to `eth_init` because `bios.c` checks different CSR defines than the code that defines `eth_init`.
=> bios: Fix build when ethphy is present but ethmac is not.

litex/tools/litex_sim.py
Initializing ROM and/or RAM content requires knowing the CPU
endianness before the SimSoC->SoCSDRAM->SoCCore constructor
sequence is invoked (before the SoC's self.cpu.endianness
could be accessed). Given that the majority of supported CPU
models use "little", set it as the new default, and override
only for the two models that use "big" endianness.
=> tools/litex_sim: fix default endianness for mem_init

litex/soc/cores/up5kspram.py
The ICE40UP5K has 128 kB of SPRAM that's designed to be used
as memory for a softcore.  This memory is actually 4 16-bit
chunks that we can gang together to give us either 64 kB or
128 kB.
Add a module that will allow us to use this memory in an ICE40.
=> soc: cores: add up5kspram module

litex/soc/integration/soc_core.py, litex/soc/software/bios/sdram.c, litex/soc/software/libbase/id.c
- Update a few additional places to use DFII_ADDR_SHIFT instead of
a hard-coded 4, which assumed 32-bit alignment.
- Force 64-bit alignment Rocket -- the only supported configuration!
This is a fixup for commit f4770219, tested on Rocket and 64bit Linux.
=> soc_core: additional csr_alignment follow-up fixes

litex/soc/cores/spi.py
Unless there is a reason not doing so, I would change CSR to CSRStorage (it is only used for writes anyway); this allows using the core in SoCs with csr_data_width=8. 
This is the way it actually works for me.
=> spi: change CSR to CSRStorage

litex/soc/integration/soc_core.py, litex/soc/software/bios/boot.c
This modifies the bios booting logic when running on a platform with VexRiscv in linux configuration.
It first tries to use separate kernel/rootfs/device tree/emulator images and when it fails, falls back to a single `boot.bin` image.
The layout of images in flash is also modified so it coresponds to the location in RAM (mind that images in flash still needs size/crc descriptor in the first 8 bytes).
=> Rework booting Linux on VexRiscv

litex/build/xilinx/vivado.py
Add an option to use read_checkpoint vivado tcl command.
Off by default. To turn it on use 'self.toolchain.incremental_implementation = True' in a platform.
=> support vivado incremental implementation

litex/build/lattice/trellis.py
Adding "-nowidelut -abc9" to the yosys command line allows significant
improvements in TRELLIS_SLICE utilization. E.g., when building 64-bit
capable "--with-ethernet --cpu-type rocket --cpu-variant linux", slice
utilization decreases from 127% of an ecp5-45k's capacity to a feasible
value of 98%.
=> build/lattice/trellis: use additional yosys optimization flags

litex/soc/interconnect/axi.py
Vivado (2019.1 and 2017.4) infers a DSP48 to perform the multiplication. It also complained about possible timing issues.
```
WARNING: [DRC DPIP-1] Input pipelining: DSP basesoc_basesoc_axi2wishbone_axi2axi_lite_beat_wrap input basesoc_basesoc_axi2wishbone_axi2axi_lite_beat_wrap/A[29:0] is not pipelined. Pipelining DSP48 input will improve performance.
```
This patch decreases readability, but Vivado does not infer DSP48 anymore
=> [fix] prevent Vivado from inferring DSP48 in AXIBurst2Beat

litex/build/xilinx/vivado.py
1) add directives to all vivado commands needing them - synth, place, route, opt
2) deprecate with_phys_opt -> should be replaced with  vivado_post_place_phys_opt_directive = 'AddRetime'
3) remove a bit of code duplication near 'if platform.verilog_include_paths:'
The default behaviour not changed (all directives set to defaults). with_phys_opt still works as before, but throws a warning.
Directive use example:     platform.toolchain.vivado_synth_directive = 'AreaOptimized_high'
=> build/xilinx/vivado: improve directive support

litex/soc/integration/cpu_interface.py, litex/soc/software/common.mak
LiteX rightfully assumes that most often the target software must
be cross-compiled from an x86 host platform. However, LiteX can be
also built on a 'linux-riscv64' platform (e.g. Fedora's riscv64
port), where the software for riscv64 targets should be compiled
using the native toolchain.
=> software: use native toolchain for same host, target architectures

litex/build/microsemi/libero_soc.py, litex/soc/cores/atlantic.py
there is also changed one property on PolarFire platform, Libero 12.x does only support enhanced constraint flow, but in generic the MicroSemi platform support needs much more work to be usable
=> atlantic JTAG UART working module

litex/build/tools.py
Otherwise `make` will always rebuild every file.
=> Only write file if contents will change.

litex/soc/cores/timer.py
Now that CSRs have documentation support, add documentation to the basic
`Timer` module.
=> timer: add documentation

litex/soc/interconnect/csr_eventmanager.py
Add `name` and `description` as optional arguments to the various
EventSource types.  These default to `None`, so this should be a
backwards-compatible change.
Use the same trick as CSRs, where we default the `name` to be the
instantiated object name as read from the Migen `get_obj_var_name()`
call.
=> csr_eventmanager: add `name` and `description` args

litex/soc/cores/spi_flash.py
Document the various fields present in the SPI flash bitbang interface.
This adds documentation for the Single and DualQuad modules.
=> spi_flash: document register fields

litex/boards/targets/arty.py, litex/boards/targets/genesys2.py, litex/boards/targets/kc705.py, litex/boards/targets/kcu105.py, litex/boards/targets/netv2.py, litex/boards/targets/nexys4ddr.py, litex/boards/targets/nexys_video.py, litex/boards/targets/simple.py, litex/boards/targets/versa_ecp5.py, litex/soc/integration/soc_core.py, litex/soc/software/bios/boot.c
This increases integrated ROM size to fit bios with ethernet for mork1x and adapts memory map for this CPU to enable mainline Linux.
=> Enable to run Linux on mork1x

litex/soc/cores/timer.py, litex/soc/integration/doc.py
This adds two new classes: `ModuleDoc` and `AutoDoc`.
`ModuleDoc` is used to document a section of a `Module`.  When derived as a subclass, such as what this patch does with `Timer`, it produces a documentation section such as https://doctest.xobs.io/timer0.html#timer
`AutoDoc` adds the ability to attach additional sections to a Module by adding them to `self`.  This gives the ability to have dynamic documentation based on runtime configuration.  For example, in https://github.com/xobs/spibone/blob/master/spibone.py#L122 we examine the `wires` argument and attach the appropriate documentation to `self`.  This results in accurate documentation as seen at https://doctest.xobs.io/spibone.html, reflecting the correct protocol and number of wires.
=> Add ModuleDoc and AutoDoc

litex/soc/cores/icap.py
This adds FIFO that can be used to send any
sequence of commands to the ICAP controller.
NOTE: This commit changes ICAP's CSRs breaking compatibilty with the older software.
=> soc: cores: support sending custom bitstream to ICAP

litex/boards/targets/versa_ecp5.py, litex/build/lattice/trellis.py
NOTE: this is a RFC, and probably should be re-spun as a more elegant, less
"hacky" modification to the ecp5versa trellis build harness. I think I'd like to gather
feedback and force-push this at least once more before it getting applied...
Thanks,
--Gabriel
Passing '-nowidelut' to yosys' synth_ecp5 command improves area utilization
to the point where a (linux variant) rocket-chip based design will fit on a
versa_ecp5 board. Usually '-nowidelut' incurs a timing penalty, but that is
then mitigated by using DSP inference (enabled by default from yosys commit
8474c5b3).
Off by default, this flag can be enabled by adding '--yosys-nowidelut=True'
to the litex/boards/targets/versa_ecp5.py command line.
=> RFC: optional '-nowidelut' flag for yosys synth_ecp5

litex/soc/integration/builder.py
Both the SoC and get_csr_header() have independently set defaults
for the value of 'shadow_base'. If the SoC's value was modified,
ensure that get_csr_header() uses the modified value instead of
its own default.
Signed-off-by: Gabriel Somlo <somlo@cmu.edu>
=> builder: use the SoC's existing shadow base with get_csr_header()

litex/soc/cores/cpu/rocket/core.py
The total size of RAM (main_mem) can be expected to vary significantly,
and often exceed the size needed for MMIO allocations by a large margin.
As such, place Rocket's MMIO (io regions) below 0x8000_0000, and start
the RAM (main_mem) at 0x8000_0000, with nothing above it to limit its
future growth.
Also, bump the pre-built Rocket verilog submodule to an updated version,
which also comes with matching changes to the way MMIO and RAM accesses
are mapped and routed to their respective AXI interfaces.
=> cpu/rocket: swap main_mem and io regions

litex/build/generic_platform.py, litex/build/tools.py, litex/build/xilinx/vivado.py
The actual Verilog version used by Vivado is 2001. This version doesn't support features like the `$bits` "system call" which has been added in Verilog 2005. To be able to use these nice features, Xilinx recommends to add these files as SystemVerilog files.
This PR adds the possibility to declare files as SystemVerilog files with `add_sources` and `add_source_dir` (new `language` parameter). The ".sv" file extension has also been added for inferred file type identification.
=> [feature] Add SystemVerilog support for the Vivado builder

litex/soc/cores/cpu/picorv32/core.py
The param p_ENABLE_COUNTERS was misspelled.
=> picorv32: Fix minimal variant params

litex/soc/software/bios/main.c
When writing multiple words using the "fw" command from bios, the address it wrote to wasn't incremented so the same address was just written to multiple times.
=> bios: Increment address when writing to flash

litex/soc/integration/common.py, litex/soc/integration/soc_core.py
Before;
```
ValueError: Memory region conflict between rom and main_ram
```
After;
```
ValueError: Memory region conflict between rom (<SoCMemRegion 0x10000000 0x10000 cached>) and main_ram (<SoCMemRegion 0x0 0x20000000 cached>)
```
Fixes #296.
=> Improve the error message on memory region conflict.

litex/soc/cores/cpu/rocket/core.py, litex/soc/integration/soc_sdram.py
Attn @enjoy-digital -- do not (immediately) pull into upstream LiteX, let's have a conversation and review first -- maybe it isn't even the right thing to do :) Please also see the related experiment regarding data width at https://github.com/enjoy-digital/litex/issues/299
Use a direct AXI point-to-point link between rocket's cached-ram axi port (mem_axi) and LiteDRAM, whenever the data width of the two ports matches.
For now, as a workaround, use Wishbone based data width conversion when the port widths are mismatched (which is rather inefficient). A future improvement might be to implement a native axi data-width converter.
Additionally, this series prepares Rocket's wrapper file to allow future variants with different, parameterized axi_mem data widths.
Finally, remove the limitation …
=> RFC: Direct link between Rocket/mem_axi <--> LiteDRAM dataport

litex/soc/software/bios/boot.c, litex/soc/software/bios/sfl.h, litex/tools/litex_term.py
=> adding support to flash an FBI image

litex/soc/interconnect/csr_bus.py
So regarding https://github.com/enjoy-digital/litex/issues/289 I suggest, at least for now, to demote the exception to a warning, because actually > 512 B memories work and are handled by the code just below this exception.
=> change >512 B CSR memory exception to a warning

litex/soc/integration/soc_sdram.py, litex/soc/software/bios/sdram.c
Read leveling tested with csr_data_width [8, 16, 32] on the
ecp5-versa5g and trellisboard (using yosys/trellis/nextpnr),
and on the nexys4ddr (using Vivado).
FIXME:
- Not tested sdrrdbuf(), sdrrderr(), and sdrwr();
- Still need to update write_level() routine!!!
=> soc_sdram, bios/sdram: support sdram init for csr_data_width <= 32

litex/soc/cores/clock.py
It was necessary to add drp_locked CSR for reading LOCK signal from
MMCM. Additionally, input signal RESET from MMCM was not driven by
any signal to do a proper reset of MMCM module thus it was impossible
to perform entirely correct dynamic clock reconfiguration.
=> soc/cores/clock: add lock reg and assign reset

litex/soc/cores/spi_flash.py
The SPI mode is actually mode3, since the output value is updated on the
falling edge of CLK and the input value is updated on the rising edge.
This also clarifies some of the documentation based on experience with
the core.
=> spi_flash: correct documentation on SPI mode

litex/build/xilinx/ise.py
These changes are needed due to recent better support introduced in Yosys specially regarding Spartan6 flow.
Tested this with https://github.com/mmicko/linux-on-litex-vexriscv/tree/spartan6 for creating Linux running on WaxWing Spartan6 board from Numato
=> Yosys - ISE flow fix

litex/soc/integration/soc_core.py
Since csr_data_width=64 has probably never worked properly, remove
it as one of the possible options (to be fixed and re-added later).
Add csr_data_width=16, which has been tested and does work.
Additionally, ensure csr_data_width <= csr_alignment (prevent subregister slices
wider than the CPU's native word size or XLen).
Note: somewhat related to Issue #314
=> soc_core: additional CSR safety assertions

litex/build/lattice/diamond.py, litex/gen/fhdl/verilog.py
Add integer attributes from Migen upstream (https://github.com/m-labs/migen/commit/811d13531171b5ca11ef394c161b9745d83ee7a5) and revert https://github.com/enjoy-digital/litex/commit/995bbfe3d69e40d688dad70e7ce376cb253f3c5c as discussed in https://github.com/m-labs/migen/pull/189.
=> Add integer attributes

litex/soc/cores/cpu/__init__.py, litex/soc/cores/cpu/rocket/core.py, litex/soc/integration/soc_sdram.py
Various development boards' native LiteDRAM ports may have
native data widths of either 64 (nexys4ddr), 128 (ecp5versa),
or 256 (trellisboard) bits. Add Rocket variants configured
with mem_axi ports of matching data widths, so that a point
to point connection between the CPU's memory port and LiteDRAM
can be accomplished without any additional data width conversion
gateware.
=> cpu/rocket: variants with double (128b) and quad (256b) wide mem_axi

litex/soc/software/bios/boot.c
the macro for RAM offsets are within the CSR_ETHMAC #ifdef blocked, which is trimmed when building the firmware for boards without ethernet.
This change or something similar would allow to build on such boards.
=> moving RAM offsets outside of CSR_ETHMAC define

litex/soc/cores/clock.py
If clocks and multipliers are planned well, we can have
a zero-error solution for clocks. Suggest to change < to <= in
margin comparison loop, so that a "perfect" solution is allowed
to converge.
=> add the possibility for a "precise" clock solution

litex/soc/cores/timer.py, litex/soc/integration/soc_core.py
This fixes documentation of `TIMER0` based on the output I've seen at https://rm.fomu.im/timer0.html.  With this patch, the lists format correctly: 
It also adds some documentation to `CTRL`.  I'm not sure what the fields are used for, so I took a guess.  `SCRATCH` appears largely unused, and nothing appears to actually use `RESET`.  If these descriptions are incorrect, I can change them to something that is correct.
=> Document CTRL and fix TIMER0 Documentation

litex/soc/interconnect/csr_bus.py, litex/soc/software/include/hw/common.h
Similarly to how CSRBank subregisters are aligned to the CPU word
width (see commit f4770219f), ensure SRAM word_bits are also aligned
to the CPU word width.
Additionally, fix the MMPTR() macro to access CSR subregisters as
CPU word (unsigned long) sized slices.
This fixes the functionality of the 'ident' bios command on 64-bit
CPUs (e.g., Rocket).
=> interconnect/csr_bus/SRAM: allow 64-bit alignment (on 64-bit CPUs)

litex/soc/cores/xadc.py
The design is backward-compatible in functionality for users
who don't want to use DRP. That is, on power on, the XADC will
scan the supply and temperature and store them in CSRs.
If drp_enable is set, the scanning stops, and the XADC is now
controlled by the DRP bus.
Wher drp_enable is reset, the XADC may return to an auto-sample
mode, but only if the internal registers are configured to do this.
If you return to drp_enable without, for example, turning on
the continuous sequence and setting which channels to check,
the results will be unpredictable (mostly either it'll scan just
once and stop, or it'll not scan all the channels, depending on
the register settings).
At this point, the backward compatibility was confirmed in testing,
the DRP API is still a work in progress as the …
=> WIP: add support for DRP on XADC

litex/soc/cores/spi_flash.py
This change keeps DQ2/DQ3 as outputs when bit-banging is enabled.
Current behaviour when (bitbang_en=1 & dir=1), all the DQ pins get tristated. However bit-banging currently only support SPI modes.
This can cause issues for unconfigured flash chips, which treat DQ2 as ~WP, DQ3 as ~HOLD. 
This results in no output or bad output when attempting to read any data from the FLASH in bitbang mode, specifically: JEDEC ID codes, and programming status bits.
=> soc/cores/spi_flash: Don't tristate DQ2/DQ3 when bitbanging

litex/soc/integration/export.py, litex/soc/software/bios/sdram.c, litex/soc/software/include/hw/common.h
Reimplement CSR accessors to be flexible w.r.t. alignment (i.e., CPU word width) and csr_data_width.
Implement additional accessors (targeted mainly at CSRs with total width > 64 bits) which transfer
arrays of standard C uintX_t types (8, 16, 32, and 64 bit uints supported).
Use CSR array accessors to clean up sdram initialization (@enjoy-digital, please test write leveling,
and all the other stuff that's not available on nexys4ddr, trellis, or ecp5versa before pulling).
This replaces PR #324 (which also contains a patch to the bios main() function testing the correctness
of all new accessors). I didn't want the actual test patch to be applied, but did want it to remain available publicly, hence this new PR.
=> CSR Improvements and Cleanup

litex/soc/integration/soc_core.py
Renaming the argument is a breaking change and might cause some user scripts to fail.
On the other hand this option is broken (wrong type), so I guess those scripts would fail anyway ;)
=> Fix sram size argument

litex/soc/cores/clock.py
Request to add a couple of extra clock buffer types to the MMCM module.
Gating requires an optional clock gate argument, maybe there is a better way to do it...
=> Add clk ce

litex/soc/software/bios/sdram.c
This change appears to fix this issue I've seen with some of my ECP5 based OrangeCrab boards https://github.com/enjoy-digital/litedram/issues/103
I'm not entirely sure why this fixes things. But I suspect strobing the DQSBUFM.PAUSE lines after all the delays have been set is getting things to work.
=> soc/software/bios/sdram: On ECP5 strobe dly_sel after read leveling

litex/tools/litex_sim.py
Requires enjoy-digital/litedram#115
I tried to run simulation with DDR4 chip specified and only needed modifications were the change in litedram and adding `PhySettings` support based on `usddrphy` used in KCU105 target.
With those changes it will be possible to use DDR4 memory in `litex_sim`.
=> tools/litex_sim: add ddr4 PhySettings

litex/soc/integration/export.py, litex/soc/software/include/hw/common.h
Expose a pair of `csr_[read|write]_sub()` subregister accessors, and
restore the way dedicated accessors are generated in "generated/csr.h"
to use hard-coded combinations of shifts and subregister accessor call.
This restores downstream ability to override CSR handling at the
subregister accessor level.
This is a followup to PR #339, and should hopefully address issue #365.
=> software, integration/export: (re-)expose CSR subregister accessors

litex/tools/litex_sim.py
Required by enjoy-digital/litedram#124
=> tools/litex_sim: use l2_reverse flag

litex/build/sim/core/Makefile, litex/build/sim/core/modules/variables.mak
There are use cases where additional flags should be added to CFLAGS or
LDFLAGS, e.g. when using Conda environment.
=> build/sim: allow to use environment's {C,LD}FLAGS

litex/soc/cores/cpu/__init__.py
Previously, only `0x00000000`-`0xefffffff` were usable as IO with `CPUNone`, in the spirit of b627a8fe71b55f1987a9cd5181da14cddd3203c1 ("all address range can be used as IO"), the entire address space is now usable.
This PR is only compatible with python>=3.6 due to the digit separators in the integer literal. That version was released over 3 years ago, is that enough backwards compatibility or should I stay on the safe side?
=> Allow all memory regions to be used as IO with CPUNone

litex/soc/integration/builder.py
All directories are now set as instance variables, allowing easy override using command-line arguments.
=> Unify output directory handling in builder

litex/soc/software/bios/boot.c
This is to allow loading bigger binaries for platforms with more flash space.
Another reason, and in fact the main one in my case, for this is to be able to define those offsets as a part of the platform so that they are generated to `csr.csv` (and headers). This, in turn, allows to automate generation of scripts preparing flash image without the need of hardcoding any offsets there.
At first I wanted to add generation of those offsets to the configuration in this repo. I noticed, however, that the whole `flashboot` part is guarded by `FLASH_BOOT_ADDRESS` define that is not generated in LiteX at all (but is generated in `linux-on-litex-vexriscv` and in `litex-buildenv`). As a result I didn't find any sutiable place to put the generation in python code in LiteX. As a workaround I decided …
=> bios/boot: allow to customize flash offsets of Linux images

litex/boards/targets/nexys4ddr.py, litex/soc/software/bios/Makefile, litex/soc/software/bios/main.c, litex/soc/software/bios/sdcard.c, litex/soc/software/bios/sdcard.h
Modify targets/nexys4ddr to facilitate easy selection of any combination of
'--with-ethernet', '--with-sdcard', both, or none, through the target builder
command line.
Import the current LiteSDCard demo's bios command-prompt initialization
and testing options into the "upstream" LiteX bios.
The idea is that, eventually, those initialization and test routines will morph
into the option to boot a kernel from microSD instead of (or in addition to)
TFTP over Ethernet.
=> Import LiteSDCard support in to LiteX, using nexys4ddr as the initial test target

litex/soc/software/include/hw/common.h
Through their use of the MMPTR() macro, the "classic"
csr_[read|write]simple() accsessors identify the MMIO
subregister with the 'volatile' qualifier.
Adjust the new, csr_[rd|wr]_uint[8|16|32|64]() accessors
to also utilize the 'volatile' qualifier. Since accesses
are implicit (a[i], where a is an 'unsigned long *'),
change 'a' to be a 'volatile unsigned long *' instead.
No difference was noticed in opcodes generated using the
gcc9 risc-v cross-compiler on x86_64 with standard LiteX
cflags (vexriscv and rocket were tested), but since
reports exist that 'volatile' matters on some combinations
of compilers and targets, add the 'volatile' qualifier just
to be on the safe side.
Signed-off-by: Gabriel Somlo <gsomlo@gmail.com
=> Add 'volatile' qualifier to new CSR accessors

litex/soc/cores/clock.py
See [ECP5 and ECP5-5G Family Data Sheet](https://www.latticesemi.com/view_document?document_id=50461), section 3.19 "sysCLOCK PLL Timing".
=> Fix ECP5PLL VCO frequency range

litex/soc/software/bios/Makefile, litex/soc/software/common.mak
It turned out that after merging https://github.com/enjoy-digital/litex/commit/ff2775c264cc452a05119dd895e25b559867dac2 to LiteX, `-flto` works fine with `-Os` and does not require `-lgcc` anymore. That's why we are going back to the simplest solution, originally proposed by @mithro and discussed in: https://github.com/enjoy-digital/litex/pull/253.
Note: enabling LTO in LiteX requires enabling it in linux-on-litex-vexriscv as well. We have a patch prepared and will create a PR shortly.
=> software: enable link time optimization (LTO)

litex/tools/litex_gen.py
These changes fix following error:
`raise ConstraintError("Resource not found: {}:{}".format(name, number))
litex.build.generic_platform.ConstraintError: Resource not found: serial:None`
When calling:
`python3 litex_gen.py --with-uart --no-compile-gateware --no-compile-software`
=> tools: litex_gen: fix missing UART pins

litex/soc/cores/cpu/blackparrot/core.py, litex/soc/cores/cpu/minerva/core.py, litex/soc/cores/cpu/picorv32/core.py, litex/soc/cores/cpu/rocket/core.py, litex/soc/cores/cpu/vexriscv/core.py
The AUR (Arch User Repository) [package](https://aur.archlinux.org/packages/riscv-sifive-elf-gcc/) for the sifive toolchain uses the triple `riscv-sifive-elf`. This PR adds this triple to the relevant cpu core.py files.
=> add riscv-sifive-elf triple

litex/boards/platforms/netv2.py
This PR adds `SDA_PU` and `SDA_PD` pins to NeTV2 platform and inverts `SCL` and `SDA` pins. With this and a small modification to LiteVideo it is possible to get EDID information from the board.
=> platform/netv2: add proper I2C pins for HDMI IN0

litex/boards/targets/nexys4ddr.py
Following the new clocker from https://github.com/enjoy-digital/litesdcard/commit/2d4230c5e439f114d4fcb0c64c828d996fb5cb20 this is my attempt to get the nexys4ddr to successfully build using `--with-sdcard` once again. Based on my experiments, one would now have to go with at least
```
sdclk 20
sdinit
sdtest 8
```
from the LiteX bios command line. Anything below 20 and initialization fails for me (rocket cpu at `sys_clk_freq=67e6` -- the maximum that will pass timing for rocket when `--with-ethernet` is also selected).
@enjoy-digital PTAL at the new `add_period_constraint()` statements in particular, as I'm not sure `period_ns(self.sys_clk_freq))` is the right value for the constraints (in fact I'm not sure I understand how that part works at all, so if you can explain or point me to …
=> targets/nexys4ddr: fix sdcard clocker initialization

litex/soc/software/bios/sdram.c
Keep CSR accesses independent of csr_data_width and csr_alignment.
@enjoy-digital Please test before applying -- I'm _guessing_ the assumption was that  alignment is 32 and csr-data-width is 8, but I'm not 100% sure :)
=> software/bios: fixup for Ultrascale SDRAM debug

litex/soc/integration/soc.py
Can't (yet) stop setting `self.map["ethmac"]` in Rocket, because doing so would break the build on targets _other_ than nexys4ddr (which don't yet use `LiteXSoC.add_ethernet()`).
But at least for now they're consistent across targets.
This (partially) fixes https://github.com/enjoy-digital/litex/issues/420.
=> integration/soc: add_ethernet: honor self.map["ethmac"], if present

litex/soc/integration/builder.py, litex/soc/integration/export.py
This file is used by rust embedded target pac crates.
It is essentially a linker file but has some specific entries needed by the rust runtime. So we are mostly reusing the linker script generator for this and adding a few of our own entries.
=> Add --mr-memory-x parameter to generate memory regions memory.x file

litex/soc/cores/clock.py
S7 MMCMs allow fractional divider on clock 0. Add a fallback
to try fractional values on clock 0 if a solution can't be found.
This is necessary for e.g. generating both a 100MHz and 48MHz
clock from a 12MHz source with margin=0
=> add fractional division options to clk0 config on PLL

litex/soc/doc/csr.py
In cases when each CSR bit has a name and we use CSR with more than 8
bits, the register diagram quickly becomes crowded and hard to read.
With this patch we split the register into multiple lanes of 8 bits
each.
The motivation for this patch is motivated by the [iCEBESOC documentation](https://icebreaker-fpga.github.io/icebreaker-litex-examples/leds.html#leds-out).
I might be missing some details here. Let me know if there is a better way of doing this. We might want to add a member variable to the CSR that will allow us to fine tune if we want the register to be split into 4 lanes or not. Maybe even a way to select if we want it to be split into 16bit lanes instead of 8bit.
@xobs your input is very much appreciated. :)
=> Make CSR documentation diagrams, with more than 8 bits, be split into multiple lanes.

litex/soc/software/bios/sdcard.c
Targets which lack an adjustable clocker will not expose the required
registers. Provide a stub sdclk_set_clk() routine for those situations.
=> bios/sdcard: provide sdclk_set_clk() stub for clocker-less targets

litex/soc/doc/csr.py
While at it also:
* Don't multilane for reg >= 8 bit width.
* Only check if we should switch to multilane after finding min field width.
=> Don't let python convert lane number to float.

litex/boards/platforms/nexys4ddr.py, litex/boards/targets/nexys4ddr.py, litex/soc/software/bios/boot.c, litex/soc/software/libbase/spisdcard.c
specifically targeted at (and successfully tested on) nexys4ddr, but should work on other boards as well
=> Support SPI-mode SDCard booting on Litex+Rocket (64bit) configuration

litex/soc/software/libbase/spisdcard.c
Depends upon https://github.com/enjoy-digital/litex/pull/435
After initialising the card, reclock the card, aiming for ~16MHz (divider is rounded up, as slower speed is safer), but a maximum of half of the processor speed.
Tested with the card being clocked to 12.5MHz on de10nano
=> Reclock spi sdcard access after initialisation

litex/soc/software/bios/boot.c, litex/soc/software/bios/sfl.h, litex/tools/litex_term.py
When using async FIFO 245 to `serialboot` the CPU, data was always corrupted.
- If there was a CRC error, sometimes lxterm would have already started sending the next frame, and the CPU got misaligned in reading frames. This PR fixes that by flushing the "bad" data from the RX buffer upon bad CRC.
- lxterm defined payload as the number of bytes from the upload file while `serialboot` defined payload length as the uploaded file byes _plus_ the address to write them to. Therefore, lxterm was sending 4 more bytes than the CPU was expecting. This PR fixes this by shrinking lxterm's file read by 4 bytes. I also renamed `frame.length` to `frame.payload_length` to avoid future confusion.
- Even with these fixes, the FIFO 245 data transfer is extremely slow, and I am not sure why yet. lxterm's …
=> flush rx buffer when bad crc and fix frame payload length

.gitmodules
This PR changes `compiler_rt`'s repo path to a github mirror as the original one is no more accessible.
LLVM project moved fully to GitHub, but unfortunatelly it officialy does not provide a separete `compiler_rt` repo anymore. The code is now part of https://github.com/llvm/llvm-project. 
What's more when we tried to clone the whole `llvm-project` repo and use `compier_rt` from there we encountered problems with TI mode emulation:
```
make[1]: Entering directory '/home/grey/linux-on-litex/update/litex-linux-on-litex-vexriscv/build/arty/software/libcompiler_rt'
CC       umodsi3.o
In file included from /home/grey/linux-on-litex/update/litex-linux-on-litex-vexriscv/litex/litex/soc/software/compiler_rt/lib/builtins/int_lib.h:89,
from …
```
=> Update removed llvm compiler-rt repo

litex/soc/software/bios/main.c, litex/soc/software/bios/sdcard.c, litex/soc/software/include/base/spisdcard.h, litex/soc/software/include/base/system.h, litex/soc/software/libbase/spisdcard.c, litex/soc/software/libbase/system.c, litex/soc/software/libnet/microudp.c
- ensure parameters representing a host address are `unsigned long` (rather than `uint32_t`) to work on 64-bit CPUs
- factor out `busy_wait()` so we can use the same one throughout the bios source tree
- use `busy_wait()` in SPI SDCard initialization loop to avoid running down the retry counter before card is ready (on some boards, e.g. trellisboard)
- finally, add `spisdcardboot()` to the bios `boot_sequence()`
=> SPI SDCard fixes and features

litex/boards/platforms/netv2.py, litex/boards/targets/netv2.py, litex/tools/litex_sim.py, litex_setup.py
This PR adds support for LiteSPI to litex_sim and to NeTV2 target
=> Add initial support for the new LiteSPI core

litex/soc/cores/cpu/blackparrot/core.py, litex/soc/cores/cpu/minerva/core.py, litex/soc/cores/cpu/picorv32/core.py, litex/soc/cores/cpu/rocket/core.py, litex/soc/cores/cpu/vexriscv/core.py
It's (one) of the embedded riscv toolchains in nixos: https://github.com/NixOS/nixpkgs/pull/65410, there's no other already supported toolchain available (afaik). 
Inspired by #405.
=> Add riscv64-none-elf triple

.travis.yml
* Use the `litex_setup.py` from the checked out code (rather than always downloading the head version).
* Run the Windows build but allow it to fail (it won't cause Travis to report failure if it fails).
=> Two small Travis-CI related patches

litex/boards/targets/ulx3s.py, litex/build/lattice/trellis.py
It's a minor change specific to trellis, so we can skip it if we decide that it's not that important. 
Update the help description for --device option for ulx3s
I've tested the changes on my ulx3s-12k board and it works.
=> Add support for ecp5 12k device in trellis.py 

litex/soc/software/bios/main.c, litex/soc/software/bios/sdram.c, litex/soc/software/bios/sdram.h
This PR extends BIOS to improve automatic SDRAM calibration. 
On some boards we needed to manually delay command lines to be able to properly write level the DRAM (as in https://github.com/litex-hub/litex-boards/issues/49#issuecomment-604297096). This PR extends write leveling process to run it for different cdly values and choose the best one.
Running write leveling for each possible value takes too much time (e.g. ~1 minute on Mercury XU5), so now `write_level` includes a simple algorithm which decreases the number of runs (in my tests it takes ~2sec). At the moment the algorithm tries to find such a cdly that write leveling results in dqs delays in the half of the available range, but we can change that value.
Example leveling on Mercury XU5:
```
--========== Initialization …
```
=> bios/sdram: add automatic cdly calibration during write leveling

litex/build/lattice/trellis.py
This enables Yosys to parse verilog files which contain potential invalid default parameters. 
As a verilog coding style, parameters are left with a value of 0 to force/ensure all instantiated modules fill these parameters with correct values.
This fixes an issue encountered when integrating the serv CPU. https://github.com/enjoy-digital/litex/issues/471#issuecomment-619569830
```
-defer
only read the abstract syntax tree and defer actual compilation
to a later 'hierarchy' command. Useful in cases where the default
parameters of modules yield invalid or not synthesizable code.
```
=> build/trellis: add verilog_read -defer option to yosys script

litex/soc/cores/cpu/__init__.py, litex/soc/cores/cpu/serv/__init__.py, litex/soc/cores/cpu/serv/core.py, litex/soc/integration/soc_core.py, litex/soc/software/bios/boot-helper-serv.S, litex/soc/software/bios/isr.c, litex/soc/software/bios/main.c, litex/soc/software/bios/sdram.c, litex/soc/software/include/base/irq.h, litex/soc/software/libbase/crt0-serv.S, litex/soc/software/libbase/system.c
SERV is a bit-serial RISC-V core that could be useful in some designs to replace a complex FSM by a CPU while still minimizing resource usage. This would be a perfect fit for LiteDRAM standalone core where the CPU is only doing the DRAM initialization.
=> Add SERV support (The SErial RISC-V CPU)

litex/soc/software/bios/Makefile, litex/soc/software/memusage.py
Print memory usage during the compilation of bios.elf.
Introduce a dependancy on pyelftools.
=> bios: print memory usage

litex/build/lattice/diamond.py
include paths given via tcl script need semicolon separators and forward slash as directory separator (even on windows)
=> diamond: fix include paths

litex/soc/software/libbase/spisdcard.c
When boot.bin is large, we fill several screens with cluster numbers. Instead, let's use `\r` and keep overwriting the same line until we're done loading clusters.
=> software: spisdcard: cosmetic: avoid filling screen with cluster numbers

litex/soc/cores/clock.py
FREQUENCY_PIN_CLKI should be given in mhz
=> diamond: quiet warning about missing clkin freq for EHXPLLL

litex/soc/integration/soc.py
I have a SoC with 32-bit wishbone bus; it has one Module with wishbone.Interface(data_width=8) connected by add_wb_slave(). It is silently broken (compiles but does not work) with the current implementation of add_adapter() because it does not respect master and slave argument order for wishbone.Converter() it uses. This commit fixes the problem by adding an argument is_master to add_adapter() and swapping arguments to wishbone.Converter() accordingly.
=> integration/soc: fix add_adapter for slaves

litex/soc/integration/soc.py
=> Enable 1x mode on SPI flash

litex/soc/cores/spi_flash.py
This adds support for memory mapped writes
in the same configuration as memory mapped reads
are currently supported.
It also adds support for accessing registers
and erasing sectors in non-bitbanged single SPI
mode.
Finally it fixes building spi_flash module in non-bitbanged mode.
=> Extended SPI flash support

litex/soc/software/bios/linker.ld
Small change to prevent LTO eating sections we don't want disappearing in our target image. 
I'm not comfortable that I understand the full detail of the software ecosystem here yet, but this
change should be conservative anyway as there aren't too many circumstances where you'd want
your bootstrap or ISRs disappearing.
=> Bios linker edits to prevent inappropriate optimisation

litex/soc/software/bios/boot.c, litex/soc/software/bios/commands/cmd_spi_flash.c
Hello,
for a project [(https://github.com/rprinz08/arty-s7-multinic)](https://github.com/rprinz08/arty-s7-multinic)
I needed the FPGA bitstream and the firmware in the SPI flash. The standard LiteX BIOS tries to 
load the firmware from flash address 0 which is already used by the FPGA bitstream. I did not find
a standard LiteX way to do this so I came up with this patch.
This patch allows the specification of an address offset in the Python SoC definition (e.g.
`add_constant("FLASH_BOOT_OFFSET", 0x800000)`) from which the BIOS tries to load (or
run when no RAM available) the firmware. So for the 16MB flash in this project the first half
is used by the FPGA bitstream and the second half by the firmware.
br
Richard
=> BIOS boot firmware from SPI with address offset

litex/soc/integration/soc.py
When there's only one master, one slave, and that slave is at 0
=> soc: Revive generation of a PointToPoint interconnect

litex/soc/integration/export.py, litex/soc/software/include/hw/common.h
Have all the new compound accessors be written in terms of the simple
ones and fix how CSR_ACCCESORS_DEFINED can be used to override the
simple ones but keep the definitions of the other ones around.
This *should* also also fix incorrect multiple accesses done
by  64-bit CPUs to 32-bit CSR busses, and make the accessors not
depend on CONFIG_CSR_ALIGNMENT being the same as sizeof(unsigned long)*8
Reviewed-by: Gabriel Somlo <gsomlo@gmail.com>
=> csr: Rework accessors

litex/soc/software/bios/boot.c
When trying to boot a firmware BOOT.BIN from SD-card using the Linux variant of the VexRiscv CPU, the BIOS tries to load a Linux Image - which is OK. But if it does not find one it gives up instead of trying to load a firmware BOOT.BIN instead (same as when booting from SPI flash).
This patch makes booting from SD-card behaving the same as from SPI flash.
br
Richard
=> Make booting from SD-Card to behave same as from SPI flash

litex/soc/software/bios/Makefile
move `-lbase-nofloat` (providing `busy_wait()` after `-lliteeth` and `-llitesdcard` (which *use* `busy_wait()` to avoid "undefined symbol" error from `$(LD)`.
=> software/bios: fix link order to avoid undefined symbol errors

litex/soc/software/libbase/exception.c
This fixes compilation on mor1kx.
=> libbase: Include missing uart header

litex/soc/cores/cpu/__init__.py, litex/soc/cores/cpu/cv32e40p/__init__.py, litex/soc/cores/cpu/cv32e40p/boot-helper.S, litex/soc/cores/cpu/cv32e40p/core.py, litex/soc/cores/cpu/cv32e40p/crt0.S, litex/soc/cores/cpu/cv32e40p/csr-defs.h, litex/soc/cores/cpu/cv32e40p/irq.h, litex/soc/cores/cpu/cv32e40p/system.h, litex/soc/software/bios/isr.c, litex_setup.py
This PR adds a [CV32E40P RISC-V CPU](https://github.com/openhwgroup/cv32e40p). It was tested on an Arty board target with lower clock frequency (core has timing issues on 100MHz but works fine at 50MHz):
```
(c) Copyright 2012-2020 Enjoy-Digital
BIOS built on May 20 2020 12:49:52
BIOS CRC passed (791d5d2b)
Migen git sha1: b1b2b29
LiteX git sha1: b49055d5
CPU:       CV32E40P @ 50MHz
ROM:       32KB
SRAM:      4KB
L2:        8KB
MAIN-RAM:  262144KB
--========== Initialization ============--
Initializing SDRAM...
SDRAM now under software control
Read leveling:
m0, b00: |00000000000000000000000000000000| …
```
=> Add support for the CV32E40P RISC-V CPU

litex/soc/cores/uart.py
So far, the startbit for UART is 1 cycle longer than all the other UART bits. With this PR, the startbit is written one cycle later.
VCD files for both scenarios are attached.
[uart_startbit_vcd.zip](https://github.com/enjoy-digital/litex/files/4673690/uart_startbit_vcd.zip)
=> Fix UART startbit: 1 cycle later

litex/build/sim/core/modules/Makefile, litex/build/sim/core/modules/spdeeprom/Makefile, litex/build/sim/core/modules/spdeeprom/spdeeprom.c, litex/soc/cores/bitbang.py, litex/tools/litex_sim.py
This adds a Verilator simulation module for SPD EEPROM as mentioned in https://github.com/enjoy-digital/litex/pull/541. It would probably be possible to use it to simulate some other EEPROMs with single-byte addressing. To implement I2C simulation I had to add `I2CMasterSim` module, which has separate `sda_in` and `sda_out` as I couldn't get Verilator to work properly with tristate pins.
=> litex/build/sim: add module for simulating SPD EEPROM

litex/soc/software/include/hw/common.h
MMPTR should always follow CSR alignment, NOT CSR data width.
(the latter merely indicates how many bits within a MMPTR are
actually populated).
Fixup for commit #4a5072a. Also fixes issue #544
=> csr: fix simple accessor alignment

litex/build/sim/core/modules/spdeeprom/spdeeprom.c, litex/soc/integration/soc.py, litex/soc/software/bios/cmds/cmd_litedram.c
This PR extents `spdread` to also verify that the EEPROM SPD data matches the one used during gateware generation. This is only available if `spd` memory exists, which is only added when generating `SDRAMModule` from SPD data (requires https://github.com/enjoy-digital/litedram/pull/201).
This verification is not automatic because reading EEPROM may require different procedure depending on the board used (as described in https://github.com/enjoy-digital/litex/pull/541). For this reason `spdread` just gets extended when we actually have the SPD data that we can verify.
Example output with error:
```
litex> spdread 0
Memory dump:
0x00000000  23 11 1c 03 45 21 00 08 00 60 00 03 02 03 00 00  #...E!...`......
0x00000010  00 00 06 0d f8 ff 01 00 6e 6e 6e 11 00 6e f0 0a  ........nnn..n.. …
```
=> bios/litedram: Add command to verify SPD contents with the one used during generation

litex/soc/software/liblitedram/sdram.c
This makes it twice as fast on 64-bit CPUs when using a 64-bit bus :-)
=> sdram: Use unsigned long for memory test

litex/boards/platforms/arty_symbiflow.py, litex/boards/targets/arty_symbiflow.py, litex/build/xilinx/platform.py, litex/build/xilinx/symbiflow.py, test/test_targets.py
Toolchain support + Arty/Symbiflow platform + minimal Arty/Symbiflow target.
In order to build bitstream, you'll need the toolchain:
```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p $PWD/miniconda
source "$PWD/miniconda/etc/profile.d/conda.sh"
hash -r
conda config --set always_yes yes --set changeps1 no
conda config --add channels conda-forge
conda config --add channels symbiflow
conda update -q conda
conda activate
conda install -c symbiflow yosys
conda install -c symbiflow yosys-plugins
conda install -c symbiflow vtr=8.0.0.rc2_3575_g253f75b6d
conda install lxml simplejson intervaltree python-constraint git pip
pip install git+https://github.com/symbiflow/fasm
wget …
```
=> Add Symbiflow toolchain support for Xilinx 7-series

litex/soc/software/liblitedram/sdram.c
This will allow the controller to default to HW control which means
the sim model can be used without specific initializations
=> sdram: Unconditionally switch to SW control before inits

litex/soc/software/liblitespi/spiflash.c
Depends on: https://github.com/litex-hub/litespi/pull/38
=> litex/soc/software/liblitespi: fix names associated with PHY CSRs

litex/build/sim/core/modules/clocker/clocker.c, litex/build/sim/core/modules/ethernet/ethernet.c, litex/build/sim/core/modules/serial2console/serial2console.c, litex/build/sim/core/modules/serial2tcp/serial2tcp.c, litex/build/sim/core/modules/spdeeprom/spdeeprom.c, litex/build/sim/core/modules/xgmii_ethernet/xgmii_ethernet.c
I had a problem with these modules not compiling because my default CC is clang 10 and it did not let these uninitialized return values and an empty if clause. Therefore these edits.
=> build/sim/core/modules: fix compilation warnings

litex/soc/cores/cpu/blackparrot/crt0.S, litex/soc/cores/cpu/cv32e40p/crt0.S, litex/soc/cores/cpu/lm32/crt0.S, litex/soc/cores/cpu/minerva/crt0.S, litex/soc/cores/cpu/picorv32/crt0.S, litex/soc/cores/cpu/rocket/crt0.S, litex/soc/cores/cpu/serv/crt0.S, litex/soc/cores/cpu/vexriscv/crt0.S, litex/soc/integration/soc_core.py, litex/soc/software/bios/helpers.c, litex/soc/software/bios/linker.ld
As per #566, `.data` section is currently located in rom, rendering it read-only. This PR moves `.data` to sram, leaving initial state in rom that needs to be copied to sram during startup. This means that every `crt0.S` needs to be updated to fix this.
* `vexriscv`: Updated and tested.
* `rocket`: Updated and tested.
* `serv`: Updated and tested.
* `blackparrot`: Identical to `rocket`, not tested.
* `cv32e40p`: Identical to `vexriscv`, not tested.
* `minerva`: Identical to `serv`, not tested.
* `picorv32`: Existing copy code updated, not tested.
* `lm32`: Existing copy code updated, not tested.
* `mor1kx`: Still needs to be updated.
* `microwatt`: Still needs to be updated. Seems to also miss `.bss` initialization.
Fixes #566.
=> bios/linker: Place .data in sram with initial copy in rom.

litex/soc/software/bios/boot.c, litex/soc/software/liblitesdcard/sdcard.c, litex/soc/software/liblitesdcard/spisdcard.c
- use `unsigned long` to represent addresses (needed on 64-bit CPUs)
- streamline `disk_initialize()`
NOTE @enjoy-digital: depends on PR #567  (i.e., apply that one ***first***)
=> post-FatFs cleanup

litex/soc/cores/cpu/mor1kx/crt0.S
I tested this in the simulator with the following test patch:
```
diff --git a/litex/soc/software/bios/main.c b/litex/soc/software/bios/main.c
index dd0989ab..93bc891c 100644
--- a/litex/soc/software/bios/main.c
+++ b/litex/soc/software/bios/main.c
@@ -69,6 +69,16 @@ static void boot_sequence(void)
}
}
+static int foo = 42; // testing .data writability
+
+static __attribute__((noinline)) int mod_foo(int bar) {
+       if (bar)
+               foo = 32;
+       else
+               foo = 52;
+       return foo;
+}
+
int main(int i, char **c)
{
char buffer[CMD_LINE_BUFFER_SIZE];
@@ -95,6 +105,11 @@ int main(int i, char **c)
printf(" (c) Copyright 2007-2015 M-Labs\n");
printf("\n");
printf(" BIOS built on "__DATE__" "__TIME__"\n");
+       printf(" testing .data write access, should be 42: …
```
=> cpu/mor1kx: fix .data initialization (follow-up to PR #567)

litex/soc/cores/cpu/microwatt/core.py, litex/soc/cores/cpu/microwatt/crt0.S, litex/soc/software/bios/linker.ld
This also makes us use the "small" memory model to avoid having to
use more complex constructs and adds the TOC to the linker script
=> software/microwatt: Fix copying data to RAM and clearing BSS

litex/soc/cores/i2s.py, litex/soc/cores/spi_opi.py
Master/slave deprecated in favor of controller/peripheral, per OSHWA recommendation.
http://oshwa.org/a-resolution-to-redefine-spi-signal-names
(post seems to be WIP, link should go live in the next couple days or so)
=> Deprecate slave terminology

litex/soc/software/bios/Makefile
Since libcompiler_rt provides functions for other
libraries (e.g., __muldiv3), it must be listed
at the end.
=> Fix ordering of libraries

litex/build/sim/core/Makefile
by asking verilator to split the C++ model into multiple files.
(copy pasted from the SpinalHDL verilator backend : https://github.com/SpinalHDL/SpinalHDL/blob/c9bd9dd06debf1466d3d45a3d9e12b22ba87e8d6/sim/src/main/scala/spinal/sim/VerilatorBackend.scala#L401)
=> Improve verilator compilation speed

litex/soc/software/liblitesdcard/sdcard.c
some indentation fixes to make things more legible, and an error code that should be moved *outside* of an `#ifdef DEBUG`.
=> Minor sdcard fixes

litex/soc/software/liblitesdcard/sdcard.c
Testing on nexys4ddr and rocket, approximately 12 iterations of the
timeout loop are needed to receive a "ready" response from the SDcard,
assuming a "warm" reset where the card has already been previously
initialized.
If the SDcard is ejected and re-inserted, or if the board is "cold-reset"
(e.g., reprogrammed via openocd vs. a simple push of the reset button),
it takes approximately 450 iterations before the SDCard responds with a
"ready" message.
In either case, a timeout of 10 is insufficient, so let's bump it to 1024.
This patch also adds some minor cosmetic improvements.
=> liblitesdcard/sdcard: adjust card-ready timeout

litex/soc/cores/cpu/__init__.py
This names are used by Arch Linux for eg.
Signed-off-by: Filipe Laíns <lains@archlinux.org>
=> cpu: add a few missing GCC toolchains

litex/soc/cores/cpu/mor1kx/core.py
The mor1kx core does not support `l.ror` instruction
by default, but gcc/clang flags allowed the
compiler to generate it.
=> mor1kx: Do not generate the ror instruction

litex/build/xilinx/symbiflow.py
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
This PR changes the symbiflow toolchain commands to have the `symbiflow` prefix.
This is related to a change in the toolchain wrappers name, so to avoid conflicts between the symbiflow related binaries and the system-related commands (e.g. `route` causes conflicts with the Unix homonym command).
=> symbiflow: changed toolchain command names in Makefile

litex/soc/integration/soc.py, litex/soc/interconnect/axi.py, test/test_axi.py
This is a part of https://github.com/enjoy-digital/litex/issues/590.
This PR adds a bridge from AXILite to CSR bus and an SRAM with AXILite interface.
Methods for adding RAM (`add_ram` and `add_rom`) accept additional `bus` parameter, and will use either `wishbone.SRAM` or `axi.AXILiteSRAM` depending on the bus type, defaulting to wishbone. The `add_adapter` method will perform conversion from AXILite to wishbone and do the data width conversion. For now `AXILiteConverter` is a dummy implementation that can connect only interfaces with the same width, and I am working on adding a proper converter.
I added tests for `AXILite2CSR` and `AXILiteSRAM` and I was also able to successfully test them in `litex_sim`.
=> Add AXILite components: AXILiteSRAM and AXILite2CSR

litex/soc/interconnect/axi.py, test/test_axi.py
Part of https://github.com/enjoy-digital/litex/issues/590.
This implements the down-converter for AXILite along with unit tests. It could probably be simplified a bit, and some transitions could be optimized not to waste cycles (1 in `IDLE` and probably 1 in `*-RESPONSE-MASTER`).
The up-converter has not been implemented yet, but maybe I should move on to the interconnect, as we don't have wishbone up-converter too, and then we could add the AXILite up-converter if needed? 
The `axi.py ` file gets longer and with more components from https://github.com/enjoy-digital/litex/issues/590 it may grow quite large, so I could probably split it into `axi.py`/`axi_lite.py`? The same with tests.
=> Add AXILiteDownConverter

litex/soc/interconnect/csr_bus.py
A recent edit broke it - making a minor fix.
=> interconnect/csr_bus: fix paged access warning

litex/soc/integration/soc.py
Fixes an issue with Vivado which crashes when building `litex-buildenv` at:
https://github.com/antmicro/litex-buildenv/commit/cc003bef3ac1407f9788ec8b7cc52d5981f8364a and `litex` bumped to https://github.com/enjoy-digital/litex/commit/2700ec3ce515670a388e2a46a2b87a5b602cc9c8, with the following options:
`export CPU=mor1kx; CPU_VARIANT=linux; export PLATFORM=arty; export FIRMWARE=linux; export TARGET=net`
When investigating the Verilog code, the only difference is that we avoid creating new `wishbone.Interface` and doing
`new_interface.connect(interface)` (this is what `wishbone.Converter` does when the data widths are the same). 
This shouldn't make any difference, but for some reason Vivado crashes with a stack trace.
I've tested it with Vivado v2018.3 and v2019.2. @mateusz-holenko …
=> Fix Vivado crash when using 1:1 wishbone.Converter

doc/socdoc.md
This adds documentation for `sphinx_extensions` which can be used to add
additional features to output.
=> doc: socdoc: document `sphinx_extensions` parameter

doc/socdoc.md, litex/soc/doc/__init__.py
This adds `sphinx_extra_config` to `generate_docs()` to support adding additional configuration parameters to the `conf.py`.
=> Socdoc extensions

litex/soc/interconnect/axi.py, test/test_axi_lite.py
The tests use `AXI2Wishbone` and `AXI2AXILite` and SRAMs to verify that `AXILite2AXI` works, which isn't the best, but was the most straightforward.
=> soc/interconnect/axi: add AXILite -> AXI converter

litex/build/openfpgaloader.py
Currently the ULX3S board uses the ujprog programmer, which is specific to this board, and does not have build system that works on my machine.
[OpenFPGALoader](https://github.com/trabucayre/openFPGALoader) is a well-written en maintained program that supports many FPGA boards, and this PR adds a simple class for it.
In a separate PR I'll update the ULX3S target to use this class.
=> Add openFPGALoader programmer

litex/soc/cores/cpu/rocket/core.py, litex/soc/integration/soc.py, litex/soc/interconnect/axi.py, litex/soc/interconnect/wishbone.py, litex/soc/software/liblitesdcard/sdcard.c
What the patch does:
- create a wrapper to convert Wishbone2AXI
- activate slave AXI port on Rocket, convert to wishbone, expose as `dma_bus`
- fix `dma_bus` routing by covering entire 4Gbyte region from 0 to `0x1_0000_0000`
- since rocket has a mmio uncached connection to the "main" wishbone system bus connecting to all slave peripherals, and
a memory point-to-point link connecting it directly to the DRAM, we need to route any and all dma master accesses through
the rocket chip so that devices can be reached at addresses below `0x8000_0000` (mmio w.r.t. rocket's memory map), and
above `0x8000_0000` (RAM as far as rocket-based litex soc is concerned).
- the `dma_bus` fix requires an extra bit to be added to the address width of the wishbone interconnect i.e. the `adr_width` of the
entire …
=> RFC: enable DMA with Rocket

litex/build/sim/config.py, litex/build/sim/core/modules.h, litex/build/sim/core/modules/clocker/clocker.c, litex/build/sim/core/modules/ethernet/ethernet.c, litex/build/sim/core/modules/jtagremote/jtagremote.c, litex/build/sim/core/modules/serial2console/serial2console.c, litex/build/sim/core/modules/serial2tcp/serial2tcp.c, litex/build/sim/core/modules/spdeeprom/spdeeprom.c, litex/build/sim/core/modules/xgmii_ethernet/xgmii_ethernet.c, litex/build/sim/core/parse.c, litex/build/sim/core/sim.c, litex/build/sim/core/veril.cpp, litex/build/sim/core/veril.h, litex/tools/litex_sim.py
Currently in `litex_sim` it is not possible to easily create clocks that have higher frequency than `sys_clk` or a different phase. This PR allows to create multiple `clocker` simulation modules based on `SimConfig`.
This update will be useful for simulating RPC DRAM https://github.com/enjoy-digital/litedram/issues/211, and similar changes were already needed and implemented for Mircon model simulations in https://github.com/enjoy-digital/litex/pull/536 by @mglb. This PR bases on that previous work and extracts only the part of configuring clocks in `litex_sim` and cleans it up.
The simulation now keeps track of the current time and modules' API has been updated to pass the current simulation time to each module's `tick()` method. The whole simulation uses a single timebase with …
=> Allow to define multiple simulation clocks

litex/tools/litex_json2dts.py
This moves the `json2dts.py` script (with some minor modifications) from `linux-on-litex-vexriscv`.
Having it in LiteX will allow other projects to generate the DT file for Linux much easier.
In the next step (after this is merged to master) I will remove the copy of the script from `linux-on-litex-vexriscv` and modify `soc_linux.py` and `sim.py` to use the one from LiteX (see: https://github.com/antmicro/linux-on-litex-vexriscv/commit/9692ac8105085fceff47ec93f49cf90819e67f49).
In the future I plan to extend this script to generate the DT file compatible with Zephyr.
=> Add Linux DT generation script

litex/boards/platforms/arty.py
This makes it compatible with the Arty A7 expansion board by Antmicro
(https://github.com/antmicro/arty-expansion-board).
=> arty: Change USB-uart and I2S Pmod configuration

litex/soc/cores/cpu/zynq7000/core.py
Most of hardware Zynq's peripherals may be connected to processor dedicated pins (PS_xxx) or, using EMIO mode, to FPGA dedicated pins (IO_xxx).
Corresponding group of pins, in processing_system module, are only present when the peripheral is configured in EMIO mode.
This PR allows to have both mode. Currently limited to ENET0 and SDIO0.
=> soc/cores/cpu/zynq7000: add enet0, enet0_mdio, sdio, sdio_cd and sdio_wp only when configured in EMIO mode

litex/soc/cores/dma.py, litex/soc/software/liblitesdcard/sdcard.c
Currently, the DMA base addresses use 32 bit registers, on the implicit assumption that physical address space is limited to 4GB. That's not true for LiteX SoC versions with 64bit CPUs, which may end up with physical RAM in excess of 4GB, requiring 64 bit address registers to cover all possible addresses that may be accessed by a DMA master.
This patch (tested with rocket and vexrisccv) bumps the DMA base address to 64 bit (length/size is left as a 32 bit register, since a 4GB limit per individual DMA transfer "should be enough for everyone" ;)
=> RFC: cores/dma, liblitesdcard/sdcard: use 64 bits for dma base address

litex/soc/cores/cpu/minerva/crt0.S, litex/soc/cores/cpu/serv/crt0.S
The startup code in `crt0.S` was incorrectly initialising the .data section.
The old code was copying from `_fdata` into `_fdata_rom`. 
This likely hasn't been an issue in the bios before, but with the changes to the command parser if the `.data` section isn't initialised then none of the commands work correctly, since they're stored in `.data`
```
--============= Console ================--
litex> [tab]o[tab]
o    o    o
o    o    o    o    o    o    o    
litex> help
Command not found
litex> 
```
=> crt0: fix .data section initialise on [Serv,Minerva]

litex/soc/integration/soc.py
`add_csr()` is defined by `SoCCore`, so won't work for any instances of `LiteXSoC` that aren't also `SoCCore`s. Also, use `use_loc_if_exists=True` so `SoCCore.csr_map` can be used without double allocation errors.
=> integration/soc: use csr.add() instead of add_csr()

litex/build/sim/core/veril.cpp, litex/build/sim/platform.py, litex/soc/software/bios/cmds/cmd_bios.c, litex/soc/software/include/base/sim_debug.h, litex/soc/software/libbase/Makefile, litex/soc/software/libbase/sim_debug.c, litex/tools/litex_sim.py
This adds some tools for better integration of simulation tracing. It allows for basic control of the simulator from withing the simulation: stop/start tracing, mark points in time, finish simulation.
The solution is to use a single `sim_trace` output pin from the design. The simulation can enable/disable signal tracing by changing the value of this pin. This way we can easily run a full simulation and enable tracing only in the interesting parts, which speeds up the simulation and avoids creating huge dumps. The time in the dump will still be correct, and the parts of simulation where tracing was disabled will visibly have no changes in signal values.
I also decided to make the simulator print `<DUMP ON>`/`<DUMP OFF>` when the tracing state changes so that it's easy to see when the dump …
=> Improve dynamic tracing support in the simulator

litex/soc/software/bios/cmds/cmd_litesdcard.c, litex/soc/software/liblitesdcard/sdcard.c
In liblitesdcard/sdcard.c, replace s/sector/block/ as the 512 byte sized
unit of data transfer to/from the sdcard.
In bios/cmds/cmd_litesdcard.c, do NOT multiply block numbers by 512,
allowing any "block" (a.k.a. "sector") on the sdcard to be addressed for
testing.
Before this patch, user-input "block numbers" were multiplied by 512 and
passed into sdcard_[read|write]() as "sector numbers", with the sdcard
logic internally treating these as 512-byte sized addressable units on
the card. This resulted in only every 512'th 512-byte sized "sector" being
accessible from the bios command line.
=> RFC: bios/sdcard: use (512 byte) blocks as the smallest addressable data unit

litex/soc/software/liblitedram/sdram.c
4f76656 rewrote how sdram_leveling() was called, leading
to linking problems for targets with sdram but with
write leveling disabled, e.g. ulx3s.
=> Fix build issue where sdram_leveling is not found

litex/soc/cores/cpu/__init__.py, litex/soc/software/common.mak
Add riscv*-unknown-linux-gnu triples to `soc/cores/cpu/__init__.py` and fix existing `riscv-linux-gnu` triple by removing incorrect `-gcc` suffix.
Also add `-fno-stack-protector` to software makefile to prevent undefined stack guard symbols from being referenced when using non-freestanding toolchains.
=> Add riscv*-unknown-linux-gnu triples and fix existing riscv-linux-gnu triple

litex/soc/cores/cpu/vexriscv/system.h
Generated soc.h says for example
#define CONFIG_CPU_TYPE_VEXRISCV
#define CONFIG_CPU_VARIANT_MINIMAL
#define CONFIG_CPU_HUMAN_NAME "VexRiscv_Min"
but code tested for CONFIG_CPU_VARIANT_MIN not MINIMAL.
Attempted to run instruction unknown to this CPU, most likely cause of hang.
This PR causes the code to correctly checks CONFIG_CPU_VARIANT_MINIMAL.
=> Fix SoC CPU crash on minimal variants on call to flush_cpu_dcache().

litex/build/xilinx/symbiflow.py
This PR adds `xc7a100tscg324-1` to a list of devices supported by the SymbiFlow toolchain. The configuration for that device can be found in the `symbiflow/xc7/install/share/symbiflow/arch/xc7a100t_test` directory of the SymbiFlow toolchain package:
```
wget https://storage.googleapis.com/symbiflow-arch-defs/artifacts/prod/foss-fpga-tools/symbiflow-arch-defs/continuous/install/66/20200914-111752/symbiflow-arch-defs-install-05d68df0.tar.xz
mkdir symbiflow 
tar -xJvf symbiflow-arch-defs-install-05d68df0.tar.xz --one-top-level=symbiflow/xc7/install
stat symbiflow/xc7/install/share/symbiflow/arch/xc7a100t_test
```
=> build/xilinx/symbiflow: Add xc7a100tscg324-1 to supported devices

litex/soc/software/bios/cmds/cmd_litesdcard.c
low priority, I just wanted to convince myself that this pin works in bare-metal, and figured now that I created the bios command, might as well share it. Feel free to ignore if it comes off as more "spammy" than useful :)
=> bios: add command returning card-detect pin status

litex/build/dfu.py
Unconditionally ask dfu-util to "Issue USB Reset signalling once we're finished".
Some host machines need it.
Else host machine does not detect the USB in the design, lxterm fails, etc.
Issuing -R here fixes everything.
If issuing -R always does not cause any trouble to anyone, then this PR is relevant.
=> Unconditionally ask dfu-util to "Issue USB Reset"

litex/soc/software/libbase/memtest.c
On mem_speed, confirm parameters on terminal output.
Show speeds in bytes per second.
Rationale:
* Forcing megabytes per second for everyone does not make sense and clamps less-than-1MB/s to zero.
* Showing bytes per second allows to distinguish between low performance and a performance measurement bug.
* Anyway previous code claims speeds were in MiB/s, they were not, actually MB/s.
=> More precise memory performance test.

litex/soc/cores/cpu/microwatt/core.py, litex/soc/cores/cpu/microwatt/crt0.S, litex/soc/cores/cpu/microwatt/irq.h, litex/soc/cores/cpu/microwatt/microwatt_wrapper.vhdl, litex/soc/cores/cpu/microwatt/xics_wrapper.vhdl, litex/soc/integration/soc_core.py, litex/soc/software/bios/isr.c
There is a conflict between the LiteX way of doing things and the POWER
way of handling interrupt tables.  LiteX expects to be able to put a ROM
at address 0 and load an application into RAM at a higher address; POWER
is architected to jump to exception handlers at 0x100...0x1000.
As a result of this, we have taken the approach of placing generic exception
handler entry / exit routines into ROM, and reserving a single pointer in
SRAM to determine the C ISR handler location.  If no application is loaded,
this pointer is set to the BIOS ROM ISR.  When an application loads, before
reenabling interrupts, it needs to set __rom_isr_address to the address of
the application's ISR, otherwise the BIOS ROM ISR will continue to be used.
Tested to operate with the built-in UART in IRQ mode, both in …
=> Add initial interrupt support for Microwatt in LiteX

litex/build/lattice/radiant.py
Otherwise [] is parsed as a Tcl command resulting in an error
=> radiant: Use {} string for bus port names

litex/soc/integration/export.py
The name was overwritten with one of the CSR region names
=> Fix SoC name in SVD generator

litex/soc/cores/cpu/zynq7000/core.py
Zynq HP AXI ports are slaves, not masters - see the lines right above.
=> cores/cpu/zynq7000: fix axi hp slave registration

litex/soc/cores/clock_nxpll.py
Adding support for the PLL blocks in the Lattice NX chips. Most of the work was in understanding how the analog parameters are calculated based on the Lattice IP Generator source which is published under their reference design license. The algorithms were reimplemented and results compared against the reference designs.
There seems to be some timing constraint issues with clocks generated through the PLL block. There's a workaround in the PLL code which creates new clocks on the PLL output pins instead of referencing the input clock, but I'm hoping that either Lattice responds to my inquiries on the matter, or the next release of Radiant either fixes the issues or provides more documentation on the matter.
=> Lattice NX PLL Support

litex/tools/remote/comm_udp.py
- Fix for some wrong named attribute checks: "tx_socket" should be "socket"
- commUDP blocks in socket receive in case of unreliable Ethernet connection. This patch introduces a timeout and error handling in case timeout occurs
=> Fix check for wrong named attributes

litex/tools/litex_json2dts.py
@enjoy-digital: please don't apply yet, let's discuss first.
@mateusz-holenko : This came up during my effort to get the dma-based litesdcard driver working on 64-bit rocket.
The `timebase-frequency` cell should ***NOT*** be used to indicate the raw CPU clock. That, instead, should be the `clock-frequency` cell attached to each `cpu@X` core.
On vexriscv we should probably set `clock-frequency`, and I'm not sure about whether we'd still want to set `timebase-frequency` to the raw `CONFIG_CLOCK_FREQUENCY` as well, since doing so is probably wrong.
In addition, or instead, we could set a `bus-frequency` cell on the `soc` node. @enjoy-digital -- this mostly depends on whether we're planning to share the same system clock (currently denoted by `CONFIG_CLOCK_FREQUENCY` in soc.h) for both the …
=> RFC: json2dts: set CPU clock-frequency and SoC bus-frequency

litex/soc/integration/soc_core.py
This allows enabling the uptime register in the timer core from the command line.
I've come to use the uptime feature quite frequently and having it available as a CLI parameter allows for easier CI integration.
=> Add SoC timer peripheral timer-uptime CLI parameter

litex/soc/cores/i2s.py, litex/soc/integration/export.py, litex/soc/interconnect/csr_eventmanager.py
Currently there is no way to communicate bit masks for an interrupt register defined using EventManager() into the firmware (that I know of). 
This PR proposes to add an option to EventManager where if `document_events` is set to `True`, instead of handing `soc.svd` a single multi-bit field with no definition of what each bit means, it automatically generates sub-fields that are named. 
This will help downstream software adjust more easily to changes in interrupt APIs without having to rely upon some manual mapping of bits on event fields. 
The API is turned off by default because turning it on breaks existing firmware, but I'd like the new firmware I'm developing to rely on register fields instead of hard-coded bitmasks.
=> Create EventManager option for documented bits

litex/soc/integration/soc.py, litex/soc/software/bios/main.c
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
The build time addition to the LiteX can be enabled with `with_build_time`.
The problem was that this functionality was not reflected in the BIOS source code, where the timestamp of the build time was added regardless of the `with_build_time` value.
This PR fixes this, allowing the user to disable the timestamp generation in the BIOS.
The main reason to do so is that the timestamp generates non-deterministic outputs, while in several cases, it is necessary to have stable and deterministic outputs, regardless of how small a difference is between two consecutive builds.
=> litex: soc: do not add the timestamp in the BIOS if it was disabled

litex/soc/cores/spi_opi.py
This is just exposing a signal to assist with SoC integration, the change should be neutral to all other designs so I'm going to go ahead and just merge it after making the request.
=> add a hook for activating the GSR inside the STARTUPE2 block for spi_opi

litex/soc/integration/soc.py
@xobs pointed out to me today that the doc note on the CTRL reset register is incorrect.
As implemented, writing *anything* to the register triggers a reset as it is kicked off of the `.re` signal, and not the actual data signal itself.
Rather than change the behavior of the block to match the docs (which could cause compatibility issues elsewhere), this PR just fixes the doc string. Should be an easy review but wanted to clear it with @enjoy-digital instead of just merging it.
=> correct the documentation for the ctrl reset register

litex/build/xilinx/symbiflow.py
Restore the  `add_false_path_constraint` method to fix SymbiflowToolchain class API.
This fixes the bitstream generation when the created SoC uses LiteEth. Otherwise the build will fail on:
```
File "/media/rwinkler/hdd/Projects/.direnv/conda/envs/xc7/lib/python3.9/site-packages/litex/build/xilinx/platform.py", line 66, in add_false_path_constraint
self.toolchain.add_false_path_constraint(self, from_, to)
AttributeError: 'SymbiflowToolchain' object has no attribute 'add_false_path_constraint'
```
=> symbiflow: restore add_false_path_constraint

litex/soc/cores/cpu/rocket/core.py
As both clock and async reset for the debug DFFs were 0, and there was no initial value on them, they were being validly optimised away by newer Yosys versions to 1'bx which was propagating into and breaking the core.
This fixes the problem by tying the async resets to the CPU reset signal.
Thus far only tested with my hacky post-early-synth simulation test, I'll have hardware results in half an hour or so -- edit, seems good on hardware too.
=> rocket: Fix UB due to optimised away DFFs

litex/tools/litex_term.py
- Don't wait for responses when loading
- Deprecate --no-crc flag
- Increase buffer size to match BIOS
=> lxterm: Speed up CRC checked uploads

litex/soc/cores/clock/lattice_nx.py
If this parameter isn't set to ENABLED; then the PLLRESET signal is ignored.
=> clock/lattice_nx: Set PLLRESET_ENA parameter

litex/build/generic_platform.py
When a Pins is defined at the platform level with only a size instead of one (or more) pad location resulting constraints file contains X instead of pad name.
Most of the time Pins have pad name, but with xc7z platforms when the zynq is used, PS signals (RAM, USB, clk and reset, ...) must be present at the top hdl level.
For this case xdc file contains LOC X and vivado produces critical warnings like:
```
CRITICAL WARNING: [Common 17-69] Command failed: 'X' is not a valid site or package pin name. [/somewhere/build/board/gateware/board.xdc:xxx]
```
Correct pad name for PS side are not required (and provided by another xdc produces by xci or create_ip).
This PR add a test to drop signals where pin name match 'X', so the xdc is not filled with them.
=> don't add pins without pad location in constraints file

litex/tools/litex_json2dts.py
This is a set of miscellaneous fixes and improvements for the
automatic generation of DTS from JSON:
- tools/litex_json2dts: Fix SPI bus #size-cells
- tools/litex_json2dts: Fix DTS indentation
- tools/litex_json2dts: Group tuples in liteeth reg property
The last change is untested, due to lack of liteeth hardware.
Thanks!
=> tools/litex_json2dts: Miscellaneous fixes and improvements

litex/soc/cores/spi_opi.py
should have no impact on normal operation, the path is
only for registering addresses that are correlated with
ECC errors as reported by the OPI device.
=> fix a timing error in the S7 OPI block

litex/soc/cores/cpu/vexriscv/core.py
The `VexRiscv_Secure` and `VexRiscv_SecureDebug` cores were added today in https://github.com/litex-hub/pythondata-cpu-vexriscv/pull/9.
=> Allow selection of VexRiscv_Secure* from lxsim CLI

litex/soc/interconnect/axi.py
This PR adds `get_ios` method for full AXI bus and also adds connections for `wlast` and `rlast` signals in `connect_to_pads`
=> Add get_ios for full AXI and add missing signals in connect_to_pads

litex/build/lattice/programmer.py
Useful for [Colorlight i5 extension board](https://github.com/wuxx/Colorlight-FPGA-Projects) as well as for other ECP5 boards with a separate external CMSIS-DAP compatible debug probe.
=> Add ECPDAP programmer

litex/soc/cores/cpu/mor1kx/core.py
My thought is that if we are running linux the FPGA should be able to
handle these extra instruction's footprint.  Also, since we are running
on linux there may be any kind of software running on the CPU, so allow
handling these instructions.
But really, I am running GLIBC tests and they run faster with this
enabled.
=> mor1kx: Enable rotate, fpu and sign extensions under linux

litex/tools/litex_json2dts.py
Having interrupts defined is better than falling back to polling.  However, I am not sure of any compatibility issues with this patch.
=> RFC dts: Support generating interrupt config

litex/tools/litex_json2dts.py
The version that landed upstream is spelt litex,soc-controller with a
dash instead of an underscore.
=> dts: Fix soc controller compatible

litex/soc/cores/cpu/picorv32/core.py
Self-explanatory. Can confirm a working CPU and BIOS on OrangeCrab using the following invocation in `litex-boards`:
```
python3 litex_boards/targets/orangecrab.py --cpu-type=picorv32 --l2-size=0 --integrated-main-ram-size=32768 --build
```
=> Use riscv32 gcc triples for picorv32- superset of riscv64 triples.

litex/soc/cores/ram/lattice_nx.py
Before, the code was using `log2_int(depth_cascading)+1`, which only works with exact powers of 2
=> Lattice NX: Allow up to 320KB of RAM

litex/tools/litex_term.py
* Avoid importing modules which don't exist on Windows.
* Set `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag when `litex_term` starts. This tells console processes which have not _already done so_ to interpret ANSI escape codes. Unfortunately it's inconsistent whether `ENABLE_VIRTUAL_TERMINAL_PROCESSING` is enabled on any given Windows console.
* `getch` works at a [lower level](https://wiki.osdev.org/PS/2_Keyboard) than other methods to capture the keyboard. While many chars can be passed to the serial port unmodified, some keys, such as those beginning `0xe0` are worth converting to ANSI equivalents such as "up", "down", "home", etc.
=> Windows fixes for `litex_term`

litex/soc/cores/cpu/vexriscv/core.py
This PR adds debug peripheral on a bus if the debug CPU variant is selected
=> CPU: Vex: add debug slave for dbg cpu variant

test/test_timer.py
I was debugging some issues I was having with the `Timer` core, and since I couldn't find any existing tests I wrote some to help understand the timer behavior. Thought I'd pass them along in case they're helpful!
I covered the 3 main timer use modes:
- One shot timer
- Periodic timer
- Interrupt driven timer
I'm still new to migen / Litex, so let me know if there's anything that needs some cleanup.
=> Add initial core test for Timer

litex/soc/cores/cpu/vexriscv_smp/core.py
- --without-out-of-order-decode: Disable out-of-order decoding, reducing resource usage but also performance.
- --with-wishbone-memory: Remove the direct memory path to LiteDRAM, reducing performance since accesses are done through the Peripheral Bus/L2 Cache but useful for boards without DRAM DM support (on some hardware, DM pins are grounded so can't be used).
=> soc/cpu/vexriscv-smp: add args to disable out of order or direct path to LiteDRAM

litex/soc/integration/export.py
If the environment variable TRIPLE is defined, use its value as the highest priority candidate.  Useful for testing new cross-compilers, or selecting among toolchains in a different priority than the built-in list.
=> integration/export: allow manually specifying toolchain triple.

litex/tools/litex_sim.py
The old name hasn't been updated to the new one: https://github.com/enjoy-digital/litedram/blob/master/litedram/common.py#L29
=> litex_sim: fix old name: get_cl_cw -> get_default_cl_cwl

litex/build/openfpgaloader.py
This is needed to support with generic_programmer usage (needed for linux-on-litex-vexriscv) + add offset/address support for firmware load:
https://github.com/litex-hub/linux-on-litex-vexriscv/issues/189
=> Add flash method to openFPGALoader class

litex/soc/cores/cpu/vexriscv_smp/core.py
When using a non-default VexRiscv cluster config, the netlist for that
config needs to be generated.  This requires sbt to be installed.
If sbt is missing, an error message is printed:
sh: 1: sbt: not found
This message may easily be lost in the noise, as the build continues, and fails
later with:
ERROR: Can't open input file `litex/pythondata-cpu-vexriscv-smp/pythondata_cpu_vexriscv_smp/verilog/VexRiscvLitexSmpCluster_Cc1_Iw32Is4096Iy1_Dw32Ds4096Dy1_Ood_Wm.v' for reading: No such file or directory
Make the root cause more visible by raising an OSError, and aborting the
build.
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
=> cpu/vexriscv_smp: Make sbt failures fatal

litex/soc/software/liblitedram/sdram.c
This a part of splitting features required for https://github.com/enjoy-digital/litedram/pull/224.
This PR adds support for more than 4 phases in software. I also added a compile time check that there are no more than 8 phases, because currently I was getting silent errors (was wrapping phase number to 4). Or maybe it would be better to generate these functions as a part of `sdram_phy.h`? Then we wouldn't have to hard-code the switch cases.
=> software/liblitedram: support PHYs with more than 4 DFI phases

litex/build/sim/gtkwave.py, litex/tools/litex_sim.py
Currently it happens sometimes that the signal names generated by Migen change from build to build due to some modification in code. When working with simulation it is often helpful to organize signals in groups and add colors, but any changes in the naming require recreating the layout (or modifying the `.gtkw` savefile in text editor). It also happens when a width of a signal changes. 
While working on LPDDR4 simulation I needed to change the signals often, so I added a class that allows to generate a savefile for a SoC from the signals we want to include. I thought it may be useful in general, so I extracted the code from https://github.com/enjoy-digital/litedram/pull/224. 
This PR adds `GTKWSave` class that can be used as show …
=> Add automatic generator of GTKWave savefiles

litex/build/sim/gtkwave.py, litex/tools/litex_sim.py
@enjoy-digital As you mentioned in https://github.com/enjoy-digital/litex/pull/795#issuecomment-771490085 I tested this with the [vermin](https://github.com/netromdk/vermin) tool and it was actually requiring Python 3.9 which seemed weird (I'm using 3.9 so I didn't notice). But it came out that it only required a minimal change to be compatible with older versions. I tested with Python 3.6 and it worked. It should probably also work with Python 3.5, but I haven't tested.
=> Fix gtkwave.py to be compatible with python 3.6

litex/soc/doc/__init__.py
When building the linux-on-litex-vexriscv documentation with Sphinx
v1.8.5:
Sphinx error:
master file linux-on-litex-vexriscv/build/orangecrab/doc/contents.rst not found
The default value of "master_doc" was changed from "contents" to "index"
in Sphinx v2[1].  As the LiteX doc system creates "index.rst", it thus
fails to build with Sphinx v1.x.
Explicitly configure "master_doc" to "index", to make it work with all
versions of Sphinx, regardless of the default.
[1] https://www.sphinx-doc.org/ca/latest/usage/configuration.html?highlight=master_doc
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
=> doc: Fix doc build with Sphinx v1.x

litex/build/xilinx/symbiflow.py
Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>
There was a change that was added mistakenly to xc7a200t support in the other PR. I reverted this change regarding bitstream_device and added a proper comment to avoid such mistake in future.
=> build/xilinx/symbiflow: fix bitstream_device select

litex/soc/cores/cpu/mor1kx/core.py
In order for mor1kx to run an SMP kernel shadow registers must be
enabled.  This patch adds two new variants:
- linux+smp - basic linux + smp support
- linux+smp+fpu - linux with FPU and smp support
=> cpu/mor1kx: Add initial SMP support to cpu core

litex/soc/software/demo/README.md
Change wording of demo README to make it more clear what the process is
and how things related.  This should help the newcomer and it still
usefull for the triained.
Change the command example to be more copy paste friendly.
Fixes #814
=> Change wording of demo README

litex/soc/software/bios/main.c
This allows to avoid a lot of unnecessary printing when running a Verilator simulation, saving a lot of time. It also omits the `crcbios()` check, which also seems unnecessary for simulation. It is useful for LPDDR4 simulation: https://github.com/antmicro/litedram/blob/9cb698360dc7f83f83a12eb64bed529d8802f973/litedram/phy/lpddr4/simsoc.py#L171
=> software/bios: add option to disable BIOS prompt

litex/soc/software/demo/README.md
Fixes: e7e28f2438c2b933 ("Change wording of demo README")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
=> software/demo: Drop bogus "the" in README

litex/soc/cores/gpio.py
This adds an easy way to add interrupts on specified pins in `GPIOIn`. This option doesn't affect `GPIOIn` without IRQ in any way. You can pass `irq` parameter with list of interrupts or ignore it.
=> Add support for interrupts on GPIOIn

litex/soc/cores/cpu/vexriscv/core.py
This is the Makefile that builds VexRiscv_Lite.v:   
https://github.com/litex-hub/pythondata-cpu-vexriscv/blob/master/pythondata_cpu_vexriscv/verilog/Makefile#L11
`--mulDiv true` is specified, so the "Lite" CPU supports the "m" extension.  Same with "LiteDebug".
We will pick up some free performance by enabling the compiler to generate "mul" instructions.
=> Vexriscv "lite" uses "--mulDiv true", so enable "mul" instructions.

litex/soc/integration/soc.py, litex/soc/software/liblitesdcard/sdcard.c
With the current sdcard clocking, when building a rocket-litex system at exactly 50 MHz, when 12.5 or 25 MHz are requested, it is possible to obtain those frequencies by using an exact power-of-two divisor for the sdclock (4 and 2, respectively). However, when driven at the full 25 MHz during `sdcardboot`, data transfer from the sdcard hangs. The first patch adds an additional halving of the sdclock frequency to ensure the sdclock frequency is never ***too*** fast for `sdcardboot`.
The second patch allows the current single-block-at-a-time (cmd17-only) Linux driver to avoid running into command timeouts when e.g., `dd`-ing a large file to `/dev/null` from the mounted sdcard. This doesn't help enable multi-block (cmd18) transfers without timeouts, but I will open a separate issue to keep …
=> fixes for boot and (single-block, cmd17-only) Linux driver

litex/build/xilinx/vivado.py
These tcl scripts tend to generate .xci's on the fly. The tcl script is typcially a set of commands from vivado ip generation software (found in vivado.jou, or the vivado console).
Perhaps should be made available upstream to (n)-migen at some point.
=> build/xilinx/vivado.py: Allow a tcl script to be added as ip

litex/soc/integration/export.py
Currently both the json and csv exports contain the soc constants, but the svd export does not. When you need this information it currently means you have to export to multiple formats (as svd also contains e.g. register fields, which are not found in the other formats), which is a slight inconvenience.
This patch adds a ```<constants>``` section to the ```<vendorExtensions>``` svd element. For my current board, this results in the following export:
```xml
</memoryRegions>
<constants>
<constant name="CONFIG_CLOCK_FREQUENCY" value="50000000" />
<constant name="CONFIG_CPU_HAS_INTERRUPT" value="None" />
<constant name="CONFIG_CPU_RESET_ADDR" value="0" />
<constant name="CONFIG_CPU_TYPE_VEXRISCV" value="None" />
<constant name="CONFIG_CPU_VARIANT_FULL" value="None" />
<constant …
```
=> soc/integration/export Add constants to SVD export

litex/soc/integration/soc.py, litex/soc/software/bios/boot.c, litex/soc/software/bios/boot.h, litex/soc/software/bios/cmds/cmd_liteeth.c, litex/soc/software/libliteeth/udp.c, litex/soc/software/libliteeth/udp.h
This is a companion PR to  litex-hub/litex-boards#177
This PR adds functions allowing to change the local IP, the remote IP and the MAC address in runtime using commands `local_ip`, `remote_ip` and `mac_addr`. Those options are only available if the parameter `configurable_ip` in integration/soc.py `add_ethernet` is set. 
The new functions in bios/boot are based on iterations as sscanf() is not defined in the bios stdio library. The new functions in libliteeth/udp only forward the changes.
=> software/bios: add an option to change ip and mac address in runtime

litex/soc/cores/cpu/vexriscv/core.py
The same memory map works not just for linux, but also other OS like NuttX and Zephyr (e.g. https://github.com/apache/incubator-nuttx/pull/2844). Maybe we can generalize it?
=> VexRiscv: More general mem_map

litex/soc/interconnect/stream.py
Fixes typo in core.stream.monitor
=> cores/stream/monitor: Fix typo

litex/soc/cores/cpu/microwatt/core.py, litex/soc/cores/cpu/microwatt/irq.h
The endianess swapping code caused the core to diverge from microwatt resulting in:
- The xics tests not working as-is: https://github.com/antonblanchard/microwatt/blob/master/tests/xics/xics.h
- byte writes writing to the incorrect byte
This removes endianswapping and minimizes the delta from upstream for the xics irq.h header.
=> xics: Disable endianness swapping

litex/soc/cores/cpu/__init__.py
Problem: xcompiler on Alpine 3.13 was not found 
Solution is to add "riscv-none-elf-gcc":
1. Add Edge to your repositories:
$ echo -e "http://dl-cdn.alpinelinux.org/alpine/edge/main\nhttp://dl-cdn.alpinelinux.org/alpine/edge/testing\nhttp://dl-cdn.alpine
linux.org/alpine/edge/community" >> /etc/apk/repositories
$ apk update
$ apk add gcc-riscv-none-elf
2. The xcompiler should be found at:
$ which riscv-none-elf-gcc
/usr/bin/riscv-none-elf-gcc
=> Add support for xcompiler on Alpine 3.13

litex/build/sim/gtkwave.py
This fixes an error when e.g. generating savefiles from LiteScope dumps, where prefix should be empty.
=> gtkwave: fix error when prefix is empty, make treeopen optional

litex/tools/litex_json2dts.py
Assuming "#[address|size]-cells = <1>", both of the following are
equivalent:
reg = <start1 size1>, <start2 size2>, ..., <startN sizeN>;
reg = <start1 size1 start2 size2 ... startN sizeN>;
The second form appears more widely used and popular, including in
the output of json2dts.py, with the exception of the mac0 node, which
uses the first form. This patch makes output generated for mac0
consistent with that for other DT nodes.
=> json2dts.py: fix mac0 reg property style for consistency

litex/soc/cores/video.py
Define a 640x480@60Hz option, VGA timings. Sync with no issue on my Iiyama E2573HS from a LiteX SoC on a Qmtech Wukong board.
=> 640x480@60Hz (lowest bandwidth option yet)

litex/build/lattice/icestorm.py, litex/build/lattice/oxide.py, litex/build/lattice/trellis.py
This is a fix for https://github.com/enjoy-digital/litex/issues/870 -- the generic map to create yosys commands generates an invalid command, `read_systemverilog` when importing SystemVerilog sources.  The correct command is `read_verilog -sv`.
=> Fix yosys read command for SystemVerilog sources

litex/build/lattice/common.py
tested with both Trellis and Diamond
=> [enh] ECP5 DIfferential input support

litex/soc/cores/timer.py
Not sure why nobody else saw this, but sometime in the last month's
patches sphinx started throwing an error when building docs for
the timer block. The problem is that the body and title are 'None'
and the doc code tries to invoke methods on None.
Changing the doc methodology to AutoDoc and explicitly creating the intro
section fixes this.
=> use AutoDoc for timer documentation

litex/soc/integration/export.py
This fixes issue #862.
The root cause is that with no description provided it simply would
not put out a description tag, which breaks compatibility with
other programs.
Insert a somewhat useful default description including a timestamp
and the words "LiteX SoC".
=> resolve issue #862 add description to soc.svd

litex/tools/litex_json2dts.py
It seems an overreaching 'interrupt-parent' caused trouble to interrupt routing
This moves 'interrupt-parent' to devices with interrupts only.
Symptoms are `plic` saying 'cpu%d: parent irq not available' and ethernet not working (and the interrupt not shown in /proc/interrupts).
This might solve https://github.com/litex-hub/linux-on-litex-vexriscv/issues/178 and https://github.com/enjoy-digital/liteeth/issues/62 as they look very similar to the issue I encountered -> mentioning @zguig52 @geertu @Chgavilana @enjoy-digital
=> Fix interrupt issue with ethernet on recent Linux-On-Litex-Vexriscv/SMP

litex/soc/software/liblitesdcard/sdcard.c, litex/soc/software/liblitesdcard/sdcard.h
Bit 2 of the command register now tells the controller to wait while
the card is indicating that it is busy (by pulling the DAT0 line low).
The card can do this for commands 7 and 12 and app command 41 (and
also for commands 20, 28, 29, 38 and 43, but we don't use those here.)
This sets bit 2 for those commands.
Signed-off-by: Paul Mackerras <paulus@ozlabs.org>
=> software/liblitesdcard: Tell the controller when to wait while the card is busy

litex/soc/integration/soc.py
This is useful for long-running commands generally and in particular
for those without any data transfer, such as erase.  It is a
level-sensitive interrupt because that makes it a little harder to
lose interrupts due to incorrect programming.
Signed-off-by: Paul Mackerras <paulus@ozlabs.org>
=> integration/soc/add_sdcard: Add an interrupt for command completion

litex/soc/software/bios/boot.c, litex/soc/software/bios/boot.h, litex/soc/software/bios/main.c
Combined with the dynamic IP configuration, this makes it possible to use a shared TFTP server, as every developer can use their own boot.json file.
```
litex> eth_remote_ip 192.168.8.13
Remote IP: 192.168.8.13
litex> eth_local_ip 192.168.8.254
Local IP: 192.168.8.254
litex> netboot jlu-boot.json
Booting from network...
Local IP: 192.168.8.254
Remote IP: 192.168.8.13
Booting from jlu-boot.json (JSON)...
Copying jlu-Image-ecpix5.bin to 0x40000000... (6903848 bytes)
Copying jlu-rv32.dtb to 0x40ef0000... (2401 bytes)
Copying jlu-ecpix5.cpio to 0x41000000... (6135296 bytes)
Copying jlu-fw_jump.bin to 0x40f00000... (49636 bytes)
Executing booted program at 0x40f00000
```
=> bios: support passing tftp filename to the 'netboot' command

litex/build/lattice/common.py
This PR fixes `IFD1P3BX` and `OFD1P3BX` black boxes instantiation for Lattice Crosslink NX flow. Both Yosys and Radiant define those as:
```
module OFD1P3BX (...);
parameter GSR = "ENABLED";
input D;
input SP;
input CK;
input PD;
output Q;
endmodule
module OFD1P3DX (...);
parameter GSR = "ENABLED";
input D;
input SP;
input CK;
input CD;
output Q;
endmodule
```
=> Lattice Crosslink NX: Fix clock port names in SDR{in/out} Impl

litex/soc/software/liblitedram/sdram.c
@enjoy-digital As discussed earlier, I tested with your fix applied and it looks like the 2nd iteration is now not needed. Or at least I haven't observed any improves when using 2 iterations now so this will speed up the training process.
=> software/liblitedram: use single iteration of dq-dqs training

litex/soc/software/bios/Makefile, litex/soc/software/demo/Makefile
The linker does not actually recognise -nodefaultlibs, that is a compiler
option.
Prior to binutils 2.36, ld treated -nodefaultlibs as a string of short
options and ignored them as unrecognised. Starting from binutils 2.36, it
reports an error instead:
riscv64-unknown-elf-ld: Error: unable to disambiguate: -nodefaultlibs (did you mean --nodefaultlibs ?)
See also: https://sourceware.org/bugzilla/show_bug.cgi?id=27050
Fixes #825.
=> soc/software: link with compiler instead of ld

litex/soc/integration/soc_core.py
With recent BIOS changes the default rom size on the mor1kx built just
passes over the 64k boundary and the build fails.  Since the 128K
default is a soft limit and the ROM gets resized to the actual ROM
requirements this should be relatively safe.
Note, that if a RW rom is configured the full 128kb will be allocated.
Fixes: #893
=> integration/soc_core: Increase default ROM size to 128K

litex/soc/integration/soc.py, litex/tools/litex_json2dts.py
I am working on testing out the patches from:
https://github.com/litex-hub/linux/pull/8
These linux patches take advantage of the sdcard interrupt to track when
transfers finish.  However, it seems the interrupt is not being
connected to the CPU.
This patch does that by allowing us to directly register an
EventManager module with the irq handler.
=> integration/soc: Wire up the sdirq to the CPU

litex/build/lattice/radiant.py
Lattice Radiant comes with two synthesis options, 'synplify' and 'lse'.
The LiteX Radiant toolchain uses 'synplify' by default, and allows it to be replaced with
'yosys' using option `--synth-mode 'yosys'`.   Since the `--synth-mode` option already exists, 
it seems to make sense to allow it to specify 'lse' as well, to give a third alternative.
=> Add 'lse' as a --synth-mode alternative with Radiant toolchain.

litex/soc/software/liblitespi/spiflash.c
Before this patch, the loop would finish with `lowest_div` either set to the first failing value
or 0 even if it succeeded with 0. Fix it so that if all tests pass, it’ll end up being -1 before
the incrementation.
This patch also skips retesting the original value. If the retest failed, `lowest_div` would be incremented past the original value and could potentially wrap around.
=> software/liblitespi: Fix speed test.

litex/soc/cores/cpu/vexriscv/core.py, litex/soc/integration/soc_core.py
Following issue #883 I've added `add_cfu()` function that provides support for [CfuPlugin](https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/plugin/CfuPlugin.scala) provided by SpinalHDL for VexRiscv CPU.
You can add CFU verilog filename via argument `--cfu-filename`. I have tested it on Arty A7 with software generated in [CFU-Playground](https://github.com/google/CFU-Playground/tree/main/proj/example_cfu_v) by executing `make software`.
=> Add CFU integration

litex/soc/software/include/base/memtest.h, litex/soc/software/libbase/memtest.c
This PR introduces some additional features to `memtest_data`.
These changes are required for the follow-up PR that adds utilities to help in debugging DRAM issues: https://github.com/enjoy-digital/litex/pull/917
**Config**
`memtest_data` can take an optional parameter with `struct memtest_config *`. When passing NULL `memtest_data` works as before. The config parameter allows to:
* disable progress using `config.show_progress=0`
* disable writing to memory and only read data (`config.read_only=1`), this can be useful when debugging memory issues to test whether errors occur when writing or when reading (reading multiple times we check if we always get the same errors
* allow arbitrary callback when an error is encountered
The callback can take a pointer to arbitrary state via …
=> Make memtest_data more configurable

litex/soc/software/liblitespi/spiflash.c, litex/soc/software/liblitespi/spiflash.h
An upcoming PR for https://github.com/litex-hub/litespi/issues/46 is adding automatic arbitration between MMIO and master cores, so the CSR for manual control is being removed.
In existing gateware, mode defaults to MMIO, so in most cases this check does not matter anyway.
=> software/liblitespi: Remove manual mode control.

litex/tools/litex_sim.py
**Describe the bug**
Running the https://github.com/enjoy-digital/litex/wiki/Use-LiteScope-To-Debug-A-SoC#use-the-analyzer tutorial from the wiki leads to errors on the most recent version of litex.
**To Reproduce**
Run `litex_sim --with-etherbone --with-analyzer` followed by `litex_server --udp --udp-ip=192.168.1.51` like the tutorial says.
**Expected behavior**
The litex server connects to the simulation.
**Log output**
```
litex_server --udp --udp-ip=192.168.1.51
[CommUDP] ip: 192.168.1.51 / port: 1234 / tcp port: 1234
File "/home/martin/coding/litex/litex/litex/tools/remote/comm_udp.py", line 48, in probe
datas, dummy = self.socket.recvfrom(8192)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback …
```
=> Use add_etherbone in simulation

litex/soc/software/libbase/memtest.c, litex/soc/software/liblitedram/sdram.c
Fix gcc warnings: use 'unsigned long' to represent memory addresses,
and remove 'static' from the definition of 'cdelay()', as it is called
from multiple C files.
=> software/lib*: address gcc warnings

litex/soc/integration/soc.py
I tried using rocket on the ulx3s which has a 16bit dram bus and therefore uses the adapter.
With the latest litex version this fails.
It's probably caused by https://github.com/litex-hub/litex-boards/commit/ba01776
**Log**
```
INFO:SoC:Converting MEM data width: 16 to 64 via Wishbone
File "../litex/litex-boards/litex_boards/targets/radiona_ulx3s.py", line 202, in <module>
main()
File "../litex/litex-boards/litex_boards/targets/radiona_ulx3s.py", line 171, in main
soc = BaseSoC(
File "../litex/litex-boards/litex_boards/targets/radiona_ulx3s.py", line 115, in __init__
self.add_sdram("sdram",
File "/home/martin/coding/litex/litex/litex/soc/integration/soc.py", line 1326, in add_sdram
self.submodules += LiteDRAMWishbone2Native(
File …
```
=> Fix base_address for LiteDRAMWishbone2Native

litex/tools/litex_sim.py
With this change the simulation will adjust automatically to the memory layout.
Rocket and Blackparrot main_ram starts at 0x80000000
Vexriscv main_ram starts at 0x40000000
=> Sync ROM_BOOT_ADDRESS with main_ram location

litex/build/xilinx/symbiflow.py
=> Force SymbiFlow 'make' to be non-parallel.

litex/compat/soc_sdram.py, litex/soc/integration/soc_core.py
The [inspect.getargspec](https://docs.python.org/3/library/inspect.html#inspect.getargspec) function has been deprecated since Python 3.0. For the use case in LiteX (referencing the .args part), [inspec.getfullargspec](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec) is a non-deprecated, drop-in replacement (shown by the source code [here](https://github.com/python/cpython/blob/3.9/Lib/inspect.py#L1120)).
=> Replace deprecated inspect.getargspec with inspect.getfullargspec.

litex/soc/integration/builder.py, litex/soc/software/bios/Makefile, litex/soc/software/bios/helpers.c, litex/soc/software/bios/helpers.h, litex/soc/software/bios/init.h, litex/soc/software/bios/linker.ld, litex/soc/software/bios/main.c
Hi, this is a set of two commits to allow external code to be linked into the BIOS, as a proposed starting point for #757.
The first commit modifies the builder and the BIOS Makefile to allow packages/libraries to be registered with the builder and passed through to the Makefile to get linked into the binary.
The second commit adds a registration mechanism for initialiation functions to the BIOS, following the same pattern used for command registration.
This has been successfully tested to link in hyperram initialization code without having to modify the litex repo.
=> Allow external software packages to be linked into the BIOS

litex/soc/cores/ram/lattice_nx.py
On designs which use Nexus parts without any external memory, it can be
difficult to fit an embedded ROM program larger than a few KiB. Radiant
cannot infer LRAM, and refuses to infer EBRAM under many circumstances
too, so large memories tend to just consume a huge number of LUTs.
This patch makes it possible to explicitly wire up an LRAM as a ROM,
populate its initial values with a program, and execute directly from
it. That lets us embed programs up to 64KiB.
This implementation is a bit ugly and is not consistent with regular Memory .init attribute, so I am open to suggestions of how to improve this.
Confirmed this produces the expected values in LRAM with Radiant.
=> soc/cores/ram: allow populating initial values in Nexus LRAM

litex/soc/cores/cpu/vexriscv_smp/core.py, litex/tools/litex_json2dts.py
Make the [ID]TLB size configurable from Litex ; expand the DTS to include cache/TLB/topology in CPUs & generate the required information for VexRiscv
Matching pull request for VexRiscv is https://github.com/SpinalHDL/VexRiscv/pull/182
This works for me on a quad-core with DTLB/ITLB at 8/4 and 16/8
=> Configurable [ID]TLB for VexRiscv & improved DTS

litex/build/dfu.py
Some targets have multiple alt settings for DFU for different zone
of the flash. Allowing to specify which one to flash and not
rebooting immediately allows to flash several of them at once.
=> build/DFUProg: Allow to specify alt interface and to not reboot

litex/soc/cores/clock/lattice_ecp5.py
I'd like to upstream this change by @gregdavill, extracted from https://github.com/gregdavill/DiVA-firmware/blob/main/gateware/rtl/ecp5_dynamic_pll.py.
=> cores/clock/ecp5: Add dynamic phase adjustment signals.

litex/soc/interconnect/axi.py
The code here https://github.com/enjoy-digital/litex/blob/master/litex/soc/interconnect/axi.py#L96 is obscure enough to disable the 'valid' signal when axi_full is False:
```
for name, width in (
[("valid", 1)] +
[("last",  1)] if (ch in ["w", "r"] and axi_full) else [] +
ch.description.payload_layout):
```
=> soc/interconnect/axi: fix valid signal in connect_to_pads for axi lite

litex/tools/litex_term.py
**Problems**
On macOS USB CDC ACM, which appears as `/dev/tty.usbmodem*`,
somehow `lxterm` keeps failing to send a payload.
**Solution**
Increase delay.
It's very unknown why to me, however, probably macOS USB CDC ACM
driver implementation issue.
**Testing**
Tested on MacBook Air (2020, M1) for OrangeCrab (rev.0.2) target
with Linux on LiteX SoC bitstream build from current commit and
load prebuild Linux On LiteX image.
=> Increase delay for `tty.usbmodem` on macOS.

litex/soc/integration/export.py
Related Issue:  #966
This PR implements the proposed change from the related issue, this allows the `generated/soc.h` file to be safely included in any assembly files.
It does change the layout of `soc.h` from the following:
```C
//--------------------------------------------------------------------------------
// Auto-generated by Migen (3ffd64c) & LiteX (8276857c) on 2021-07-09 10:46:33
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_CLOCK_FREQUENCY 24000000
static inline int config_clock_frequency_read(void) {
return 24000000;
}
#define CONFIG_CPU_HAS_INTERRUPT
#define CONFIG_CPU_RESET_ADDR 2147680256
static inline int config_cpu_reset_addr_read(void) {
return 2147680256;
}
...
#endif …
```
=> Make "generated/soc.h" able to be included in assembly files.

litex/build/openfpgaloader.py
Not all boards have an onboard cable (FTDI, DFU, CMSIS-DAP, ...) it's the case for instance for acorn CLE 215+ or colorlight 5A-75B.
In this situation `--cable` is required or default `ft2232` cable is used.
Without `--freq` the cable is configured with a 6MHz clock frequency. It's a good compromise between speed and stability but with current master branch we have demonstrate *openFPGALoader* is able with arty to work at 30MHz (max FT2232 clock frequency).
This PR add two optional constructor params to pass cable name and frequency and build cmd line accordingly.
=> openfpgaloader: add cable and freq options

litex/build/openfpgaloader.py
`freq` param may be a string, an int but in all cases it's usualy easier to use engineering notation to represent big number.
This PR add a conversion to float to avoid exception like:
`
ValueError: invalid literal for int() with base 10: '10e6'
`
=> openfpgaloader: improves freq conversion type

litex/soc/integration/soc.py
The current code only works for the default "read+write" mode.
This fixes the gateware for the "read" and "write" mode, but the bios doesn't build for mode "write" (sdcard init depends on read).
=> soc/add_sdcard: Fix IRQ code, only add IRQs depending on mode

litex/soc/cores/clock/lattice_ecp5.py, test/test_clock.py
Reimplement the configuration loop to allow all 4 outputs to be used by the user, if one of them is suitable for use as VCO feedback.
The new strategy is to first iterate over requested outputs to see if any of them can be used as a feedback source.  If one can, it is selected, and if no output is suitable, it attempts to instantiate one.  Once the feedback path is selected, the VCO frequency is known and it attempts to calculate the remaining outputs' settings.
In addition, this implementation now respects datasheet limits in two new ways:
- It respects the post-input-divider minimum frequency of 10MHz
- It respects the max output frequency of 400MHz for instantiated feedback outputs
I am slightly unhappy with the seemingly-repetitive for loops. However each one has slightly different …
=> ECP5PLL: implement 4-output solver

litex/soc/cores/cpu/vexriscv_smp/core.py
The current code only works with a memory bus because otherwise
"generate_cluster_name" doesn't get called.
Cluster_name is only needed in the finalize phase.
Therefore, the name will now be generated just before its usage.
Verifiable with: 
litex_sim --cpu-type vexriscv_smp (should be broken before this commit)
=> cores/vexriscv_smp: Fix vexriscv_smp doesn't build without a memory bus

litex/soc/cores/cpu/cv32e40p/crt0.S, litex/soc/cores/cpu/vexriscv/crt0.S, litex/soc/cores/cpu/vexriscv_smp/crt0.S, litex/soc/software/bios/linker.ld
RISC-V requires stack to be aligned to 16 bytes.
https://github.com/riscv/riscv-elf-psabi-doc/blob/1d5384e6690ea39b5395ddc6943882ed2830dbee/riscv-elf.md?plain=1#L183
Right now, in bios/linker.ld, `_fstack` is being set to 8 bytes before the end of sram region.
```
PROVIDE(_fstack = ORIGIN(sram) + LENGTH(sram) - 8);
```
Removing ` - 8` makes it aligned to 16.
Also there are changes in crt0.S for vexriscv, vexriscv_smp and cv32e40p.
Code that was setting up stack, was adding 4 to its address for some reason.
Removing it makes it aligned to 8 bytes, and with change in bios/linker.ld to 16 bytes.
It also fixes `printf` with long long integers on 32bit CPUs ([relevant issue](https://github.com/riscv/riscv-gcc/issues/63)).
Should close #322 and #910
=> Fix stack alignment

litex/soc/software/include/base/stdlib.h, litex/soc/software/libbase/libc.c
The vsnprintf() function would correctly interpret %lld and %llu
arguments as "long long" width, but the number() helper function only
accept "long" so the value would be truncated and then printed
incorrectly.
Widen the argument to number() to accommodate up to "long long".
=> software/libbase: fix %lld and %llu in printf functions

litex/soc/integration/export.py
Analyzing code, I found that it should be possible to use clang for compilation ([Makefile](https://github.com/enjoy-digital/litex/blob/9bec0ce7a28afb498c7b7eb79943c270225c061a/litex/soc/software/common.mak#L10)).
Turns out that after defining `CLANG=1` environmental variable, export.py script crashes trying to [concatenate `None` and `str`](https://github.com/enjoy-digital/litex/blob/master/litex/soc/integration/export.py#L81).
That's because `t` gets value of `triple`, which in turn is [`equal to cpu.clang_triple`](https://github.com/enjoy-digital/litex/blob/master/litex/soc/integration/export.py#L60).
And that should be ok, but only if `clang` python variable was `True`, which in this case is.
But why didn't [exception informing about not supporting …
=> Fix clang support detection

litex/build/lattice/programmer.py
Nicer than having to wrangle with openocd. It's a fork of iceprog
=> Add ecpprog-based programmer for ecp5

litex/soc/software/demo/linker.ld
Without this change, when `.data` section size wasn't multiple of word size, `data_loop` in crt0 was jumping over `_edata` and continued looping. As it works on words and right now 64 bit CPUs are biggest ones supported - alignment is now 8 bytes.
Also removed `- 4` from stack address, as it needs to be aligned to 16 bytes on RISC-V.
Should fix #856 and at least explain why #876 wasn't working.
=> Fix alignments in demo/linker.ld

litex/soc/software/liblitespi/spiflash.c
It's been found that the frequency initialization routine that is currently present in liblitespi can affect negatively the flashboot process when using `READ_4_4_4` commands.
Currently when the `spiflash_freq_init` function reads CRC data from SPI flash, it does so using the default read command, in our case `READ_4_4_4`. Because we didn't enter QPI mode before (which we need to do after each power up), we get bogus data back (only `0xcc` byte) and this makes the system to _cache_ these bytes in the beginning of the `spiflash` region. This causes flashboot to fail:
```
Booting from flash...
Error: Invalid image length 0xcccccccc
No boot medium found
```
Moving the invocation of `spiflash_freq_init` to the end of `spiflash_init` solves this issue.
=> liblitespi: perform frequency initialization after entering quad/qpi mode

litex/soc/software/bios/cmds/cmd_mem.c, litex/soc/software/include/base/memtest.h, litex/soc/software/libbase/memtest.c, litex/soc/software/liblitespi/spiflash.c
This PR add the `random_access` option to the `memspeed` function so that it allows the user to choose between sequential and random accesses when testing the memory speed.
There are minor cleanups still to be done.
=> Add random_access option to memspeed and perform mem_speed in liblitespi

litex/soc/software/liblitedram/sdram.c
This a fix described at the end of https://github.com/enjoy-digital/litedram/pull/258#issuecomment-882435501.
To my understanding this should be correct, but please check if you think it is. I've tested this on xilinx_zcu104, digilent_arty and antmicro_lpddr4_test_board and it worked correctly on these.
I also used the following script to verify the error counts:
```python
#!/usr/bin/env python
VERBOSE = False
def check_test_pattern_popcounts(module, *, nphases, dfii_pix_data_bytes, nmodules):
per_phase = []
for p in range(nphases):
this_phase = []
for i in range(dfii_pix_data_bytes):
j = p * dfii_pix_data_bytes + i
if j % nmodules == (nmodules - 1 - module):
this_phase.append(i)
per_phase.append(this_phase)
max_errors = sum(8*len(popcounts) for popcounts in per_phase)
xdr = 2 …
```
=> soc/software/liblitedram: fix pattern checking for low DFI databits

setup.py
This patch adds the static files needed for the documentation to the
`package_data` field in `setup.py`.
I ran into failures when generating documentation after installing litex
using pipenv which didn't copy these files which in turn caused the
documentation generation to fail.
This change causes all files in the `static` subfolder of the
litex.soc.doc module to be installed as well.
=> Add docs static files to package_data in setup.py

litex/soc/software/liblitedram/sdram.c
There is an error in READ_CHECK_TEST_PATTERN_MAX_ERRORS computation. It is being computed based on nphases and data rate (x1/x2), but this gives incorrect result when using DFIRateConverter which increases number of data bytes per phase. This may results in integer underflow when subtracting `(max_errors - errors)` and selecting wrong bitslip during read leveling.
With this change we make use of DFII_PIX_DATA_BYTES directly, which should be more reliable as sdram_write_read_check_test_pattern should always scan 1/SDRAM_PHY_MODULES of all data bytes on DFI. So max errors is nphases (outer for loop) times dfi data bytes (inner loop) divided by nmodules (scanning 1 module) times 8 bits in a byte ([relevant code](https://github.com/antmicro/litex/blob/f943092bb5a3aae1bfda08e2ffbe927d048e32be/l …
=> soc/software/liblitedram: fix max error count computation

litex/soc/cores/cpu/microwatt/core.py, litex/soc/software/common.mak
These fix building the BIOS for microwatt with the cross compilers in Debian unstable. The first two patches are required for any platform running a newer binutils.
$ powerpc64le-linux-gnu-ld --version
GNU ld (GNU Binutils for Debian) 2.37
$ powerpc64le-linux-gnu-gcc --version
powerpc64le-linux-gnu-gcc (Debian 11.2.0-2) 11.2.1 20210815
=> Binutils fixes

litex/soc/cores/cpu/vexriscv/core.py, litex/soc/cores/cpu/vexriscv/system.h
This change uses new explicit config flags CONFIG_CPU_NO_DCACHE and CONFIG_CPU_NO_ICACHE to control whether special instructions are emitted to flush these caches when present.
This makes it more convenient when adding new VexRiscv variants without one or both of the caches.   For example, currently we need to lie and set CONFIG_CPU_VARIANT_LITE to suppress the dcache flush instruction.
This change centralizes knowledge about the different variants into vexriscv/core.py.
=> Restructure config flags for dcache/icache presence in Vex.

litex/tools/litex_sim.py
litex_sim.py is edited to customize main ram size from command line arguments, if main_ram_size is set to zero then it won't show in generated SoC logs.
=> customize main ram size from command line argument

litex/build/io.py, litex/build/sim/common.py, litex/build/sim/verilog/iddr_verilog.v, litex/build/sim/verilog/oddr_verilog.v
Signed-off-by: Pawel Sagan <psagan@antmicro.com>
=> litex: Enable simulation of DDR IO by adding oddr/iddr/ddrtristate simulation models.

litex/soc/cores/clock/lattice_ecp5.py, test/test_clock.py
Two changes here:
- clock/lattice_ecp5/ECP5PLL: ensure feedback path selected before exiting search
The test case I added is the one I originally hit. The loop would initially select clkfb=1, see that all 4 outputs were correct, and exit the search. Then it would try to generate a feedback clock and fail because all were already allocated.
Fix this by adding the feedback path to the search success criteria.
- clock/lattice_ecp5/ECP5PLL: emit frequency annotations to help Diamond
Unlike nextpnr, Diamond appears not to infer the frequency of PLL outputs.  Emit the same attributes that Diamond's PLL tool does.
=> Fix premature selection of full PLL config with no feedback

litex/soc/software/demo/linker.ld
I found that in some cases, initialized global variables don't work with user libraries, so a little change to the linker that I use, taken from the demo file, seems to solve the problem. I think it makes more sense to put the global variables in sram and their initial values in the main_ram, similar to the bios linker.
=> Linker fix for initialized global variables

.gitignore, litex/tools/litex_client.py, litex/tools/litex_term.py
Add a command line option for lxterm to allow specification of the path to the CSR register CSV file, rather than just requiring csr.csv to be in the directory lxterm is executed from
Add a command line option to specify the base address of whatever addresses lxterm is sending to lxserver. In the case of PCIe, these are negative values (e.g. -0xF000_0000)
If the base address was not specified and the design uses PCIe, automatically remap the base address to the CSR start
```
./sqrl_acorn.py --with-pcie --build --driver --uart-name=crossover --csr-csv=build/sqrl_acorn/csr.csv
litex_server --pcie --pcie-bar 48:00.0 &
lxterm --csr-csv=build/sqrl_acorn/csr.csv bridge
```
=> Fixes to allow crossover uart over PCIe with lxterm and litex_server

litex/soc/cores/gpio.py, litex/tools/litex_sim.py
This changeset encompasses two distinct commits:
- litex/soc/cores/gpio: support external tristate buffer
Support exposing tristate GPIOs with tristate pads, by avoiding instantiation of tristate buffers directly in the module. This gives the developers more flexibility in how they want to implement their tristate IOs (for example with level shifters behind the IOs), and allows to use the GPIOTristate core in the Verilated simulation as Verilator does not support top-level inout signals.
- litex_sim: add optional GPIOTristate core
Adds a switch `--with-gpio`, which will add a 32 pin GPIOTristate core, with the GPIOTristate signals exposed on the top-level module. This can be used to add a custom GPIO module in the Verilated simulation.
Both of these changes combined have allowed me to …
=> litex_sim: optionally add GPIOTristate core

litex/soc/cores/cpu/vexriscv/core.py
The port has already been removed from VexRiscv (issue #1036).
=> Remove rsp_payload_response_ok from Vex/CFU hookup code.

litex/tools/litex_json2dts_linux.py
This is a series of 3 patches to allow setting up the DTS for booting from an sdcard.
1. We want to be able to disable the initrd loading from ram.  This also was pointed out by @shenki as being something that keeps him from using the dts generator as it means we cannot use kernels with built in rootfs. (option `--without-initrd`)
2. We want to be able to set a different root device, for my SD card I use `mmcblk0p3` (option `--root-device mmcblk0p3`)
3. I setup earlycon to use liteuart rather than the risc-v only `sbi`, no option, this is now the hard coded default.  This means we get console output right away rather than waiting for the console drive to be initialized (usually after loading initrd).
=> Json2dts sdcard booting

litex/soc/cores/cpu/vexriscv_smp/crt0.S
Also, no need to for non-boot cores to `call smp_slave`, it's the
immediately following instruction for them already.
***NOT*** tested, only following up on an email conversation to ensure we don't forget. @Dolu1990 @enjoy-digital please test and review -- thanks!
=> cpu/vexriscv_smp/crt0.S: only boot core should run data_init

litex/soc/cores/cpu/rocket/core.py, litex/soc/integration/soc.py
Previously, the SoCController was only reseting the CPU, which required adding
these ResetInserters. Now that the SoCController resets both CPU and peripherals
these ResetInserters are redundant and no longer useful.
=> cpu/rocket/core: Remove ResetInserter on adapters.

litex/soc/software/libc/Makefile
This PR fixes libc Makefile deps  - libc.a is required before we start building `stdio` and `missing`. Building `libc.a` also generates required headers.
=> software: libc: fix Makefile dependecies

litex_setup.py
This change was mistakenly merged in with picolibc changes. Its sole purpose was making testing PR easier as I didn't know about `litex_setup.py dev` option.
=> Revert litex_setup_url change

litex/soc/software/liblitesdcard/spisdcard.c
**Problem**
In commit 01a906add7cddcb63bc93813f30e3fd39336eec6, argument name is changed from `sector` to `block`, but not changed the one used in the code.
**Solution**
Use `block` instead.
=> FIX: arg name is changed.

litex/soc/software/bios/boot.c, litex/soc/software/liblitesdcard/sdcard.c, litex/soc/software/liblitesdcard/sdcard.h
Providing "uint32_t" to printf's "%ld" results in warnings on 64-bit
builds: use "unsigned long" instead.
This is a fixup on top of 77283d3d.
=> 64-bit follow-up for picolibc warning fixes

litex/soc/cores/cpu/rocket/crt0.S
This issue came up while investigating #1049. This PR does not completely fix the problem described there, but it's a step in the right direction.
The startup code accesses this data using `sd/ld` instructions, which require that the address being accessed is 8-byte aligned.
The `.dword` asm directive does NOT imply any alignment, so we need to force it using the `.align` directive.
=> cpu/rocket: naturally align data defined in crt0.S

litex/soc/cores/cpu/microwatt/core.py
In commit 061b89beffde ("cpu/picolibc: Add family property to CPUs and
directly use it for picolibc.") a family was added for meson cross
compilation, but this doesn't exist, leading to the following warning:
WARNING: Unknown CPU family powerpc, please report this at https://github.com/mesonbuild/meson/issues/new
Instead use ppc64. While this seems wrong for a ppc64le machine, it
appears to be what meson expects.
=> microwatt: Fix family property

litex/build/efinix/efinity.py, litex/build/efinix/platform.py
Current efinix support have an hardcoded 'C4' timing model. But this one is not available for all trion devices.
This PR add extraction of device and timing model from information provided by platform in litex-boards (*T120F324I4* instead of *T120F214* for instance)
=> efinix: don't hardcode timing model

litex/soc/software/common.mak, litex/soc/software/libc/Makefile
This also prevents meson from autodetecting `ccache` support automatically, which may be desirable if, for instance, `ccache` is actually slower (it happens!) or you use `sccache`. Otherwise, this is an opt-in feature for users.
On a Linux machine, I saw a clean build time go down by 50% after the first build. On Windows, there is no significant difference, possibly because the file I/O time dominates the compile times.
=> Add option in Makefile for (s)ccache support.

litex/build/sim/verilator.py
This was removed in
3b78fd9 fhdl/verilog: Remove blocking_assign (not used with LiteX).
(I had the wrong rev here in the initial pull request)
However that breaks `litedram_gen --sim` which passes regular_comb=False
to all toolchain builders
```
File "/home/matt/3rd/fpga/currvenv/bin/litedram_gen", line 11, in <module>
load_entry_point('litedram==0.0.0', 'console_scripts', 'litedram_gen')()
File "/home/matt/3rd/fpga/currvenv/lib/python3.9/site-packages/litedram-0.0.0-py3.9.egg/litedram/gen.py", line 834, in main
File "/home/matt/3rd/fpga/currvenv/lib/python3.9/site-packages/litex-0.0.0-py3.9.egg/litex/soc/integration/builder.py", line 330, in build
vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
File "/home/matt/3rd/fpga/currvenv/lib/python3.9/site-packages/litex-0.0.0-py3.9.eg …
```
=> litex_sim: Allow regular_comb=False argument

litex/soc/software/liblitedram/sdram.c
For targets that do not feature `SDRAM_PHY_WRITE_LEVELING_CAPABLE`  write latency procedure does not work properly. Use of `best_bitslip` was conditioned with value of `_sdram_write_leveling_bitslips[module]`. However, when `SDRAM_PHY_WRITE_LEVELING_CAPABLE` is not defined, this array is not filled with meaningful data. It makes the procedure ignore found `best_bitslip` value and in turn DDR calibration passes only when 0 is a valid bitslip. This PR ignores `_sdram_write_leveling_bitslips` value for targets not capable of write leveling.
=> liblitedram: Write latency calibration failure fix

litex/soc/cores/cpu/eos_s3/core.py, litex/soc/integration/soc.py
With EOS-S3 the Wishbone address bus is 8bits aligned, but all transaction are 32bits (or  WBs_BYTE_STB is used for 8 or 16 bits requests).
Anyway, in all cases the 2LSB are always 0.
In other hand, when data_width == 32, litex consider an address bus aligned (ie 2LSB are already discarded).
This patch fix alignment to fit litex requirement.
=> Eos s3 fix wb adr

litex/soc/cores/cpu/eos_s3/core.py
This PR updates eos_s3 core with:
- for all unused **qlal4s3b_cell_macro** a default 0 value or Open
- clocks signals are passed into a **gclkbuff**
=> Review eoss3 core

litex/soc/cores/cpu/microwatt/core.py
Use the technology specific multiplier implementation when building for a
Xilinx platform.
This isn't understood by yosys so we can't use it when yosys is used for
synthesis.
=> microwatt: Use Xilinx multiplier

litex/soc/integration/soc.py
This ensures that dual ranked memory appears with the correct capacity.
When testing butterstick configurations I noticed that the SoC always showed 1/2 the memory.
It looks like this calculation of sdram_size ignores dram ranks. Since the butterstick is dual rank this halves the memory reported/mapped to the SoC.
=> soc.intergration.dram: Use nranks in capacity calc

litex/build/altera/quartus.py
Testing for a file existing is slightly different
between bash and .bat files which caused the batch
file to error out.
=> build/altera: fix rbf generation on windows

litex/soc/software/libfatfs/ff.h
When working with the litesdcard I noticed that if the FatFs sector buffers were not aligned FatFs would fail, I suspect this is due to the DMA in litesdcard that's copying data into the buffer only performing 32bit writes.
In the FatFs header we can tell GCC to ensure that these buffers always fall on a word boundary.
=> software.fatfs: Align fatfs sector buffers

litex/soc/cores/prbs.py
If enabled, then the error count wraps around when it
reaches the limit of the 32b counter instead of saturating
to a max value.
Software can then detect the wrap and act accordingly.
=> cores/prbs: Add a 'wrap' option to PRBSRX

litex/tools/litex_json2dts_linux.py
replace `soc/bus-frequency` with a dedicated `clocks` section containing a `litex_sys_clk` node.
update `mmc` node with `reg-names` property, and add a reference to the above-mentioned `sys_clk` -- the upstream driver can't rely on there being a cpu with the exact required frequency, and needs a local reference to the clock it should use as the source to be divided in order to obtain `sd_clk`.
@geertu -- PTAL as well -- thanks!
=> clock, mmc updates for json2dts_linux

litex/tools/litex_json2dts_linux.py
A string with a {{ was missing the .format call, generating some broken dts
=> tools/litex_json2dts_linux.py fix double {{

litex/soc/interconnect/wishbone.py, litex/soc/software/bios/cmds/cmd_mem.c
soc/software/bios/cmds/cmd_mem.c: 
The required number parameters is at least 2.
litex/soc/interconnect/wishbone.py: 
When using a 64-bit wishbone interface, the higher 4-byte of the data will not be transferred as the default width of the ['shared'](https://github.com/enjoy-digital/litex/blob/8ac3fbc0391b133775cbb6f12db89a27d7b18bd4/litex/soc/interconnect/wishbone.py#L203) interface is 32-bit. Add this parameter to make the 64bit wishbone bus work.
=> soc/software/bios/cmds/cmd_mem.c: fix number of required params

litex/soc/cores/cpu/zynq7000/boot-helper.S, litex/soc/cores/cpu/zynq7000/core.py, litex/soc/cores/cpu/zynq7000/irq.h, litex/soc/cores/cpu/zynq7000/system.h, litex/soc/integration/builder.py, litex/soc/integration/soc.py, litex/soc/software/bios/Makefile, litex/soc/software/bios/linker-zynq.ld, litex/soc/software/common.mak, litex/soc/software/libc/Makefile, litex/soc/software/libc/stdio.c, litex/soc/software/libcompiler_rt/Makefile, litex/soc/software/libxil/Makefile
This changeset enables **minimal** LiteX BIOS support on Zynq7000 ARM hard core.
linker-zynq.ld is adapted from Xilinx examples so has a copyright banner.
libxil/Makefile targets out-of tree sources in https://github.com/Xilinx/embeddedsw - [here](https://github.com/litex-hub/litex-boards/pull/314) is an example of their use.
Exceptions are disabled for all ARM CPUs because I did not find a way to compile them properly yet (are they used anywhere anyway?).
Picolibc needs this patch: https://github.com/picolibc/picolibc/pull/226
=> Zynq7000 ARM BIOS support

litex/soc/integration/soc.py
We could also print a warning and discard the cache configuration of this Region
=> soc: raise an error if adding a SoCRegion with incoherent cache configuration

litex/soc/software/bios/cmds/cmd_mem.c
Add mem_cmp function. Compare the memory content starting from two addresses.
=> litex/soc/software/bios/cmds/cmd_mem.c: add mem_cmp

litex/tools/litex_json2dts_linux.py
Add MMC voltage regulator, and reference it from the mmc node.
For now, all boards we know of provide a 3.3V fixed voltage to
their SDCard receptacles, either directly or via PMOD.
=> tools/litex_json2dts_linux.py: add mmc voltage regulator

litex/soc/cores/cpu/__init__.py, litex/soc/cores/cpu/marocchino/__init__.py, litex/soc/cores/cpu/marocchino/boot-helper.S, litex/soc/cores/cpu/marocchino/core.py, litex/soc/cores/cpu/marocchino/crt0.S, litex/soc/cores/cpu/marocchino/irq.h, litex/soc/cores/cpu/marocchino/spr-defs.h, litex/soc/cores/cpu/marocchino/system.h
The Marocchino is a superscaler OpenRISC implementation which has
advanced features including 64-bit double FPU support.
Much of the python module here is copied form mor1kx like the *.S
and *.h files.
=> marocchino: Add initial support for new OpenRISC core

litex/soc/software/bios/boot.c, litex/soc/software/libfatfs/diskio.h, litex/soc/software/libfatfs/ff.c, litex/soc/software/liblitesata/sata.c, litex/soc/software/liblitesata/sata.h, litex/soc/software/liblitesdcard/sdcard.c, litex/soc/software/liblitesdcard/sdcard.h, litex/soc/software/liblitesdcard/spisdcard.c, litex/soc/software/liblitesdcard/spisdcard.h
At the moment, sata and [spi]sdcard fatfs disk access methods
are mutually exclusive, as their names collide with each other.
Implement a DISKOPS structure with media-specific disk access
methods, and a way for the boot code to specifiy which media
type's methods to use when loading files into RAM at boot time.
This (together with https://github.com/litex-hub/litex-boards/pull/325) allows me to build both sdcard and sata support for rocket on nexys_video like so:
```
litex-boards/litex_boards/targets/digilent_nexys_video.py --build \
--cpu-type rocket --cpu-variant full4d --sys-clk-freq 50e6 \
--with-ethernet \
--with-sdcard \
--with-sata --sata-gen 1
```
NOTE 1: I haven't actually ***run*** it yet, but so far this allows the build process …
=> RFC: software/fatfs: allow sata, [spi]sdcard disk ops to co-exist

litex/soc/cores/cpu/zynq7000/boot-helper.S, litex/soc/cores/cpu/zynq7000/boot-helper.c, litex/soc/cores/cpu/zynq7000/core.py, litex/soc/integration/soc.py
This makes the memory map valid from the CPU point of view, enables software compilation for Zynq and adds a boot helper (this one not tested yet, but something like this should work).
=> Fix Zynq software support

litex/build/gowin/gowin.py
Some Gowin FPGAs has copackaged "PSRAM" instead of "HyperRAM". They're
in fact also HyperRAM, but named differently and because of this needs
slightly changed hack.
Add hack for PSRAM too. In case of two PSRAM chips are used, the bus is
wider so the needed definition is already in place, so the bus width
hack is not needed.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
=> gowin: add hack for copackaged PSRAM

litex/soc/cores/bitbang.py
* otherwise might block the I2C bus on reset
=> bitbang.py: initialize SCL / SDA lines to high on reset

litex/soc/cores/clock/xilinx_common.py
for Xilinx devices, when *yosys* is used for synthesis, as mentionned in this [issue](https://github.com/YosysHQ/yosys/issues/1583), FD primitive is not supported and this step fails with
```
ERROR: Module `\FD' referenced in module `\digilent_arty_z7' in cell `\FD_7' is not part of the design
```
This PR replace `FD` by `FDSE` with same behaviour.
=> litex/soc/cores/clock/xilinx_common: fix yosys synth: replace FD by FDCE

litex_setup.py
On Windows, default Python 3.x installation uses just `python` command. Therefore, `litex_setup.py` fails:
```
$ python .\litex_setup.py --init --install
```
...
```
[  65.500] Installing Git repositories...
[  65.500] ------------------------------
[  65.500] Installing migen Git repository...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
File "C:\Users\ben\litex\litex_setup.py", line 363, in <module>
main()
File "C:\Users\ben\litex\litex_setup.py", line 349, in main
litex_setup_install_repos(config=args.config, user_mode=args.user)
File "C:\Users\ben\litex\litex_setup.py", line 225, in litex_setup_install_repos
subprocess.check_call("python3 …
```
=> litex_setup.py on Windows: Change install "python3" to current interpreter

litex/soc/integration/builder.py, litex/soc/integration/export.py, litex/soc/integration/soc_core.py, litex/soc/software/bios/main.c, litex/soc/software/libbase/i2c.c, litex/soc/software/libbase/i2c.h
The BIOS can now initialize I2C peripherals during the boot.
The add_i2c_init_table method of the soc speficy parameters:
self.submodules.i2c = I2CMaster(pads)
self.add_i2c_init_table("i2c", i2c_addr=0x4c, table=it6263_i2c_hdmi_tx)
it6263_i2c_hdmi_tx = [
(0x05, 0x40),
(0x04, 0x3D),
(0x04, 0x1D)
...
The table is a list of tupple as (address, value).
=> i2c: automatic device init by the BIOS

litex/soc/cores/bitbang.py, litex/soc/integration/builder.py, litex/soc/integration/export.py, litex/soc/integration/soc.py, litex/soc/integration/soc_core.py, litex/soc/software/bios/cmds/cmd_i2c.c, litex/soc/software/bios/cmds/cmd_litedram.c, litex/soc/software/bios/main.c, litex/soc/software/libbase/i2c.c, litex/soc/software/libbase/i2c.h
A new command is introduced: "i2c_dev".
With this command you can list i2c devices and choose on to be active.
=> i2c: handle multiple i2c controllers in the BIOS

litex/build/efinix/common.py
This fixes cases where:
- i is None,
- o is only 1 bit wide
=> efinix: fix EfinixTristateImpl

litex/soc/cores/cpu/zynqmp/__init__.py, litex/soc/cores/cpu/zynqmp/boot-helper.c, litex/soc/cores/cpu/zynqmp/core.py, litex/soc/cores/cpu/zynqmp/irq.h, litex/soc/cores/cpu/zynqmp/system.h, litex/soc/integration/soc_core.py, litex/soc/software/bios/Makefile, litex/soc/software/bios/linker-zynqmp.ld, litex/soc/software/libxil/Makefile
This enables ZynqMP processing system instantiation, its connection to AXI slaves (works with SoC CSR bus) and BIOS compilation for Cortex-A53 64-bit cores.
Similar in many aspects to Zynq7000, reusing few pieces like libxil.
I'm preparing another PR into litex-boards demonstrating this on Kria KV260.
=> cores/cpu: add ZynqMP (UltraScale+ MPSoC) support

litex/soc/cores/cpu/microwatt/core.py, litex_setup.py
The microwatt version has renamed countbits to countzero. Update to the
latest and update the file list.
=> microwatt: Move to latest and add countzero module

litex/soc/cores/cpu/cv32e41p/__init__.py, litex/soc/cores/cpu/cv32e41p/boot-helper.S, litex/soc/cores/cpu/cv32e41p/core.py, litex/soc/cores/cpu/cv32e41p/crt0.S, litex/soc/cores/cpu/cv32e41p/csr-defs.h, litex/soc/cores/cpu/cv32e41p/irq.h, litex/soc/cores/cpu/cv32e41p/system.h, litex/soc/software/bios/isr.c, litex_setup.py
Worked in simulation and on a board (Nexys4-DDR). Mostly inspired by the CV32E40P PR https://github.com/enjoy-digital/litex/pull/535
```
(c) Copyright 2012-2022 Enjoy-Digital
BIOS built on Feb 14 2022 22:39:52
BIOS CRC passed (3f045d30)
Migen git sha1: ac70301
LiteX git sha1: d506b441
CPU:		CV32E41P @ 1MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR:		32-bit data
ROM:		128KiB
SRAM:		8KiB
--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
Timeout
No boot medium found
--============= Console ================--
litex> mem_list
Available memory …
```
=> Add support for the CV32E41P RISC-V CPU

litex/soc/cores/cpu/eos_s3/core.py, litex/soc/cores/cpu/zynq7000/core.py, litex/soc/cores/cpu/zynqmp/core.py, litex/soc/integration/soc.py
As mentioned in issue #1154 some hard CPUs may have address translated before fabric or a second time when AXI is converted to wishbone:
- **eos s3** use absolute adress in CPU but relative address is exported to eFPGA side;
- **zynq7000** and **zynqMP** have, currently, two adress decoding (one in [SoCRegion](https://github.com/enjoy-digital/litex/blob/master/litex/soc/integration/soc.py#L87), a second in [AXILite2Wishbone](https://github.com/enjoy-digital/litex/blob/0d2183062d14d8babf444fe196c84a48d099586d/litex/soc/interconnect/axi.py#L542)
In all case, these decoding are not required and communication CPU<->FPGA fails due to mismatch addresses.
This PR (inspired by @sergachev [commit](https://github.com/sergachev/litex/commit/197a6353d597a4e06bab7d2af4e3e9dde31fabdd):
- adds …
=> Cpu fix csr decoding

litex/soc/software/libbase/memtest.c
Done by 
- manualy unrolling 4 times
- Using a do while instead of a for loop
On digilent video, at 100 Mhz got : 
nax :
Write speed: 124.6MiB/s
Read speed: 136.4MiB/s
vex smp : 
Write speed: 166.5MiB/s
Read speed: 85.9MiB/s
Which make sense, vex has the advantage of being write through, boosting its performances at the cost of more transactions for litedram to manage.
The read speed difference is likely mostly due to Nax having a better branch prediction (btb)
=> Improve bios memspeed performances

litex/build/sim/core/modules/Makefile, litex/build/sim/core/modules/rules.mak, litex/build/sim/verilator.py
If a project needs a custom verilator module, it can now
specifies the path where the module's directory is.
SimPlatform can now look for extra modules:
builder.build(
extra_mods = ["mymodule1", "mymodule2"],
extra_mods_path = os.path.abspath(os.getcwd()) + "/modules",
sim_config=sim_config
)
Modules must be subdirectories of extra_mods_path:
.
├── modules
│   ├── mymodule1
│   ├── mymodule2
│   ├── ...
=> sim: allow custom modules to be in custom path

litex/build/efinix/efinity.py, litex/build/efinix/ifacewriter.py
Sometimes the Python API of the interface designer produce a wrong XML
file. Values can be changed in the XML file with this new list.
For example:
fix_pll = [
("comp_output_clock", "mipi_clk",             [("out_divider", "20")]),
("comp_output_clock", "mipi_tx_clk_fastclk",  [("out_divider", "4"), ("phase_setting", "3")]),
("comp_output_clock", "mipi_tx_data_fastclk", [("out_divider", "4"), ("phase_setting", "1")]),
("comp_output_clock", "mipi_tx_slowclk",      [("out_divider", "16")])
]
platform.toolchain.ifacewriter.fix_xml += fix_pll
=> efinix: add a list of values to fix in xml

litex/build/altera/quartus.py, litex/build/efinix/efinity.py, litex/build/lattice/diamond.py, litex/build/lattice/icestorm.py, litex/build/lattice/oxide.py, litex/build/lattice/radiant.py, litex/build/lattice/trellis.py, litex/build/microsemi/libero_soc.py, litex/build/sim/verilator.py, litex/build/xilinx/common.py, litex/build/xilinx/ise.py, litex/build/xilinx/vivado.py
If the Builder class is not used to build the projet, platform sources
is still a list of tupples with 4 elements.
For now, we don't handle file copy when Builder is not used but at least
it won't crash.
=> platform: fix add_sources

litex/build/efinix/dbparser.py, litex/build/efinix/ifacewriter.py, litex/soc/cores/clock/efinix.py
get_gpio_instance_from_pin returned the pad name.
It now returns the gpio block name.
To get the pad name, there is now get_pad_name_from_pin.
=> efinix:dbparser: add get_pad_name_from_pin and use it

litex/build/lattice/trellis.py
Can we turn on bitstream compression as a default option?
Are there any reasons people can think of as to why this should default to disabled?
=> build/trelis: Compress bitstream by default

litex/soc/software/libbase/memtest.c
I get a warning when building the bios (for rocket, 64-bit) -- so I believe that cast is missing a `*` to make it a pointer. @dolu, LMK what you think -- thanks!
=> bios/memtest: fix cast warning

litex_setup.py
fixes: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
=> litex_setup: change to installing with pip

litex/soc/interconnect/axi.py
When using  connect_to_pads on full AXI interface the "last" pin was not connected because of this typo.
=> Fix missing "last" pin connection when using connect_to_pads

litex/soc/integration/export.py
software/include/generated/csr.h:110:2: warning: integer overflow in expression '-2147483648 - 1' of type 'int' results in '2147483647' [-Woverflow]
uint32_t mask = ((1 << 31)-1);
^~~~~~~~
=> export: fix mask for field size 31

CONTRIBUTORS, litex/soc/cores/led.py, test/test_led.py
Started this when I had some newer model WS2812 LEDs for which the current timing didn't work.
So I added a test bench that validates everything according to the WS2812 datasheets for the old and new hardware revision.
As I was digging down into that rabbit hole I found a bunch of issues with the current FSM implementation causing timings to be off due to extra cycles spent in the low states. This doesn't matter much at higher clock speeds - but at lower clock speeds it can break the timing constraints.
Happy for feedback - this is my first PR towards LiteX so I did my best to try to make everything fit into the structure.
=> Improve WS2812 timings and add different hardware revision support

litex/soc/integration/soc.py, litex/soc/integration/soc_core.py, litex/soc/interconnect/axi.py, litex/soc/interconnect/wishbone.py, test/test_wishbone.py
This pull request adds support for incrementing address burst cycles to SRAM module. Both linear and wrapped increments are supported.
Because for some designs burst might be unnecessary (e.g. no cache in CPU core), it is disabled by default. It can be turned on by passing parameter `burst=True` in `SoCCore.add_ram()` function, with shortcut available for integrated *RAM/ROM modules in the form of `integrated_{rom,sram,main_ram}_burst` parameters in `SoCCore` class.
Implementation was tested by writing a test suite and an example SoC for measuring speed difference: https://github.com/antmicro/wishbone-interconnect-burst-mode-benchmark (README contains results and instructions how to run tests).
Wishbone burst cycle documentation: …
=> soc/interconnect/wishbone: Add incrementing address burst mode to SRAM

litex/soc/cores/uart.py
With default behaviour, when address_width != data_width, address may be corrupted. This is due to the same bytes counter and done signal.
This PR add a dedicated counter + done for address with size accordingly.
=> Uart fix stream2 wishbone v2

litex/soc/software/bios/boot.c
sdcardboot_from_bin assumes that the MAIN_RAM_BASE is set which is not always
the case. This commit deactivates the sdcardboot_from_bin support for targets
without main-ram. In those cases, the boot_from_json method can still be used.
=> software/bios: Fix build error for targets with sdcard but without main_ram_base

litex/soc/software/liblitedram/bist.c
With decent burst length, fast RAM and fast clock rate,
the intermediate result can easily overflow 32 bits.
=> fix overflow in BIST

litex/soc/cores/i2s.py, litex/soc/cores/ram/xilinx_fifo_sync_macro.py, test/test_fifosyncmacro.py
This PR adds LiteX equivalent of Xilinx `FIFO_SYNC_MACRO` which is used in few SoC cores. It is also replaced in I2S core if there is passed toolchain different than `vivado`. This provides support for I2S to toolchains different than Vivado. It has been tested with F4PGA and Vivado on Arty A7 and it works fine on both configurations.
=> Add LiteX equivalent of Xilinx FIFO_SYNC_MACRO to I2S

litex/soc/cores/cpu/vexriscv/crt0.S, litex/soc/cores/cpu/vexriscv_smp/crt0.S
The csrw opcode is no longer part of the "I" instruction set but has
been moved to a separate extension.  Enable that extension in crt0.S.
=> cpu/vexriscv: Fix compilation of crt0.S with new binutils.

litex/gen/fhdl/memory.py, litex/gen/fhdl/namer.py, litex/gen/fhdl/verilog.py, litex/soc/integration/soc.py, litex/soc/interconnect/axi.py, litex/soc/interconnect/wishbone.py
Memory` .init `files were using generic mem_x names, which made them difficult to re-integrate in Super SoCs and to figure out contents:
Previously generated gateware:
```
litex_soc.v
mem.init (ROM contents)
mem_1.init (SRAM contents) 
```
This PR adds `build_name` as prefix to the memory `.init` files and also use name parameter of Memory to pass information from SoC.
The generated gateware is now:
```
litex_soc.v
litex_soc_rom.init (ROM contents).
litex_soc_sram.init (SRAM contents).
```
Which should be easier to re-integrate and figure out contents.
=> FHDL Namer integration and memory .init naming improvements.

litex_setup.py
the python binary is stored in the "Program Files" directory.  without
delimiting the path the calls to the binary will fail on Windows hosts.
=> litex_setup: fix path reference for python3 binary on non-Linux hosts

litex/build/generic_platform.py
Improve error reporting on `request_all()`.
This allows me to grab a few LEDs for debugging purposes with `platform.request()` and pass the rest to `LedChaser` with `platform.request_remaining()` instead of `request_all` (which fails) so I still get the handy "proof of life" indicator for the overall design.
=> Add request_remaining("name") that returns unallocated pins.

litex/build/altera/common.py
This makes debugging e.g. conflicting drivers easier since the errors will display the clock domain name.
Would you like me to attempt to make this change across all families?
=> AlteraAsyncResetSynchronizer: prettify instance names

litex/soc/cores/clock/intel_common.py
Before fix:
```
->  % ./terasic_deca.py --sys-clk-freq 200e6 --build --load 
INFO:Max10PLL:Creating Max10PLL, speedgrade -6.
INFO:Max10PLL:Registering Single Ended ClkIn of 50.00MHz.
INFO:Max10PLL:Creating ClkOut0 sys of 200.00MHz (+-10000.00ppm).
INFO:Max10PLL:Creating ClkOut1 hdmi of 40.00MHz (+-10000.00ppm).
...
INFO:SoC:System clock: 200.000MHz.
INFO:Max10PLL:Config:
n          : 1
clk1_freq  : 40.32MHz
clk1_divide: 31
clk1_phase : 0.00°
vco        : 1250.00MHz
m          : 25
...
File "/home/jevin/code/eda/max10-usb/litex/litex/soc/cores/clock/intel_common.py", line 104, in do_finalize
clk_phase_ps = int((1e12/config["clk{}_freq".format(n)])*config["clk{}_phase".format(n)]/360)
KeyError: 'clk0_freq'
```
After fix:
```
n          : 1
clk1_freq  : …
```
=> Intel Clocking: compute_config() fix indent causing PLL config error

litex/soc/cores/clock/gowin_gw1n.py
GW2A has the same PLL primitive with GW1N.
Add support for it to GW1NPLL.
=> GW1NPLL: add GW2A

litex/soc/software/liblitesata/sata.c
uint32_t is treated as `unsigned int` by the 64-bit compiler, and
as `long unsigned int` by the 32-bit compiler. As such, we'll get
a warning on one or the other regardless of whether we use "%ld"
or "%d" with printf:
on 64-bit (rocket, using "%ld"):
./litex/litex/soc/software/liblitesata/sata.c: In function 'sata_init':
./litex/litex/soc/software/liblitesata/sata.c:87:45:
warning: format '%ld' expects argument of type 'long int', but
argument 2 has type 'uint32_t' {aka 'unsigned int'} [-Wformat=]
87 |     printf("Capacity: %ldGB\n", capacity);
|                       ~~^       ~~~~~~~~
|                         |       |
|                         |       uint32_t {aka unsigned int}
|                         long int
|                       %d
on 32-bit (vexriscv, using "%d"): …
=> software/liblitesata: address printf int size warning

litex/soc/cores/cpu/vexriscv/core.py, litex/soc/cores/cpu/vexriscv/crt0.S, litex/soc/cores/cpu/vexriscv_smp/core.py, litex/soc/cores/cpu/vexriscv_smp/crt0.S
Instead of enabling the zicsr extension in crt0.S, change -march to
specify that VexRISCV implements version 2.0 of I, rather than the
latest (2.1).  In 2.0 the csr instructions were still part of I.
This approach has two advantages:
* It is compatible with older versions of binutils, since they do not
need to know about the new zicsr extension
* By modifying the -march in CFLAGS, csr instructions can be used in any
code (for example by the inline functions in irq.h), not just in crt0.S.
=> cpu/vexriscv: Redo csr instruction fix

litex/soc/cores/jtag.py
This is for supporting the JTAG-UART for the XEM8320 AU25P litex-board (to be PR later).
=> adding JTAG support for the xcau, Xilinx Artix UltraScale+

litex/build/altera/quartus.py, litex/soc/cores/clock/intel_common.py
This PR contains two small fixes to Altera/Intel PLL support, one is fixing N multiplier is ignored when generating ALTPLL instance, another is adding `derive_pll_clocks` to SDC to allow PLLs to be analyzed by TimeQuest.
=> Misc fixes to Altera PLL support

litex/build/openocd.py
In latest OpenOCD version (0.11.0, 2022-03-25) when using `litex_server` in JTAG mode a noisy warning is issued by OpenOCD saying that form of `expr` use is deprecated. This PR fixes use of `expr` in generated `stream.cfg` file.
=> Updated OpenOCD stream for expr use 

litex/build/altera/quartus.py, litex/soc/cores/clock/intel_common.py, litex/soc/cores/cpu/openc906/__init__.py, litex/soc/cores/cpu/openc906/boot-helper.S, litex/soc/cores/cpu/openc906/core.py, litex/soc/cores/cpu/openc906/crt0.S, litex/soc/cores/cpu/openc906/csr-defs.h, litex/soc/cores/cpu/openc906/irq.h, litex/soc/cores/cpu/openc906/system.h, litex/soc/software/libbase/isr.c
It's only boot tested in sim and build tested in Vivado now, and it
requires a FPGA > 100k LUT4 (XC7A100T currently does not fit).
The ISR code is based on Rocket one.
These Python code depends on a forked version of OpenC906 at [1].
[1] https://github.com/Icenowy/openc906/tree/fpga-optimization
=> [WIP] soc/cores/cpu: add initial OpenC906 support

litex/soc/software/bios/main.c
This eliminates a "defined but unused" warning on the
`boot_sequence()` function if `main.c` is compiled with
`#define CONFIG_BIOS_NO_BOOT`
=> bios/main: Wrap CONFIG_NO_BOOT around boot_sequence()

litex/build/gowin/gowin.py
When copying from `impl/pnr/project.fs`, we are _already_ in the `build` directory.
So including those path components in the `copyfile` function will point to nonexistent files. This PR fixes this.
I'm probably gonna keep this branch around locally and add a few quality of life fixes in addition to this PR.
=> Gowin: Fix `copyfile` paths

litex/build/xilinx/ise.py
The top name changed in 2016 but only XST was changed.
=> build/xilinx/ise: Fix yosys flow

litex/build/lattice/trellis.py
Add options for increasing the SPI config MCLK frequency for nextpnr_ecp5/trellis.
Because the frequencies are somewhat odd I've also added a basic assert that lists the valid options.
=> build/lattice/trellis: Add MCLK frequency option

litex/soc/software/liblitesdcard/spisdcard.c
The initialization of my 64GB SDXC card was failing/timing out at:
[if (spi_xfer(0xff) == 0xff)](https://github.com/enjoy-digital/litex/blob/87bd29fec2de3a2a825b242e7cbc69160c9bf5a6/litex/soc/software/liblitesdcard/spisdcard.c#L95)
```
at spisdcard.c-->spisdcard_select()
at spisdcard.c-->spisdcardsend_cmd(CMD0, 0)
at spisdcard.c-->spisdcard_init()
at spisdcard.c-->spisd_disk_initialize()
at ff.c-->mount_volume()
at ff.c-->f_mount()
at boot.c-->sdcardboot_from_json()
```
The return value of spi_xfer(0xff) was always 0 instead of 0xff.
Reading this [SPISD introduction](http://elm-chan.org/docs/mmc/mmc_e.html) it seems that after setting CS High for >74 cycles a CMD0 needs to be submitted immediately after that. It is not mentioned that the card needs to be deselected and selected before …
=> Do not call spisdcard_select for CMD0.

litex/build/xilinx/ise.py
The GenericToolchain merge introduced new bugs for the ISE Backend.
Testable with: `scarabhardware_minispartan6.py --build`
=> build/xilinx/ise: Fix XST/Yosys flow

litex/build/microsemi/libero_soc.py
With the move to `GenericToolchain` some reference to `_format_io_constraint` and `tcl_name` have not been updated to reference to the class instance.
This PR fix these errors by adding `self` each time it's required.
=> build/microsemi/libero_soc: fix missing self for _format_io_constraint and tcl_name

litex/soc/cores/clock/lattice_ecp5.py
`nextpnr-ecp5` always picks the PLL BEL that is closest to the clock input pin, which in my design is on the left side.  However, all my high-speed I/Os are on the right side, and I need to use the right side PLL BEL in order to satisfy timing constraints on ECLK.  (The delay from the input clock on the other hand is completely irrelevant, it's just a frequency reference.)  The easiest way I have found to accomplish this is to hardcode the BEL name `X70/Y49/EHXPLL_LR`.  So I need a way for Litex to let me do that.
=> cores/clocks/lattice_ecp5: Allow manual placement

litex/soc/cores/cpu/neorv32/irq.h, litex/soc/cores/cpu/neorv32/system.h
This PR add cache flush functions to `system.h` and interrupt management functions to `irq.h` (using same function names as [`litex/soc/cores/cpu/ibex`](https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/cpu/ibex/irq.h)).
=> [cores/neorv32] add CPU cache and interrupt management functions

litex/soc/cores/cpu/openc906/core.py
There is no axi_lite_if, it's axi_if instead.
=> cpu/openc906: fix bus name

litex/build/xilinx/yosys_nextpnr.py
During migration to `GenericToolchain` `_run_make` as not been adapted as `run_script` method.
This PR fix this missing adaptation.
=> build/xilinx/yosys_nextpnr: _run_make -> run_script

litex/build/sim/core/Makefile
This is required for example to simulate openc906 which uses verilog includes at relative paths with litex_sim.
=> sim: enable relative include paths for verilator

litex/soc/cores/cpu/cva6/core.py
Because of the problem with native AXI bus width conversion (https://github.com/enjoy-digital/litex/pull/1386) I propose to have this optional conversion to wishbone and enable it by default for now.
In addition I fixed add_jtag() and removed a bunch of 'self's.
=> cpu/cva6: add optional peripheral bus conversion +

test/test_axi.py
After looking at https://github.com/enjoy-digital/litex/issues/1313 and other issues caused by AXI width conversion I wrote these minimal tests that demonstrate problems with the existing AXIDownConverter and AXIUpConverter. The validity of the tests can be checked by using DUT_ref instead of DUT which replaces axi64->axi32->wb32 with axi64->wb64->wb32 configuration - that works fine.
One of the problems with the width converters is here:
https://github.com/enjoy-digital/litex/blob/b9a1fec30fd1f0691f9c6463bac24ea1da75355a/litex/soc/interconnect/axi/axi_full.py#L210
Because AXI awlen/arlen=0 means 1 transfer, 1 means 2 transfers, 2 means 3 transfers and so on (https://developer.arm.com/documentation/ihi0022/c/Addressing-Options/Burst-length) it is not correct to bit-shift the signal to …
=> test: add axi 64b to 32b conversion test

litex/tools/litex_json2renode.py
This PR adds support for generating the Renode `LiteX_Framebuffer_CSR32` peripheral based on the `video_framebuffer` node in csr.json. It also updates interrupt configuration to match changes in the `PlatformLevelInterruptController` peripheral and makes a few cosmetic improvements to the generated Renode platform file.
=> tools/litex_json2renode: Add video_framebuffer support, vexriscv interrupt fixes

litex/soc/cores/cpu/vexriscv_smp/core.py
This prevents needing to install `sbt` etc. for the demos in linux-on-litex-vexriscv which use the Wishbone interface and the L2 cache.
=> cores/cpu/vexriscv_smp: add default cores used by linux with l2 cache

litex/build/sim/verilator.py
Fst tracing stopped working since: https://github.com/enjoy-digital/litex/pull/1381 
It added a new variable but missed to add an extra placeholder on the formatted string.
=> build/sim/verilator: fixed missing placeholder

litex/soc/cores/cpu/vexriscv_smp/core.py
This fixes issues along the lines of `Verilog HDL Unsupported Feature error at ***.v(14192): system function "$urandom" is not supported for synthesis`.
I tested that this issue is fixed on with Quartus 20.1.1 building the `de10nano` example of `linux_on_litex_vexriscv`. I also checked that Vivado 2020.1 building `arty_a7` and Yosys 0.16 building `butterstick` don't need a similar fix. I also tested that the regular `vexriscv` CPU doesn't seem to need a similar fix.
This partially addresses https://github.com/litex-hub/linux-on-litex-vexriscv/issues/295
=> cores/cpu/vexriscv_smp: define SYNTHESIS in Quartus

litex/soc/integration/soc.py
The first argument to `self.irq.add()` should match the name of the
`EventManager()` object being added, i.e., "sata_irq" rather than
just plain "sata". This is necessary for interrupt signals to be
asserted as intended.
=> integration/soc: fix sata irq initialization

litex/soc/integration/builder.py, litex/soc/software/bios/Makefile, litex/soc/software/bios/command.h, litex/soc/software/bios/main.c
The first commit adds the bios-console option to the argparser of the builder.
I decided to call it bios-console in the hope that more options can be added to the argparser in the future. Different bios options could get their own argument with a specific help text and finally be merged into the bios_options list (in the builder_argdict function).
The second commit adds the option to remove the cmd handlers together with the serial parsing code.
If this option is selected, the target system can still be booted using the boot_sequence methods, but the user cannot interact with the bios if this fails.
All options were tested with litex_sim:
**no option:**
ROM usage: 22.91KiB     (17.90%)
RAM usage: 1.61KiB      (20.12%)
**no option + lto:**
ROM usage: 20.45KiB     (15.97%)
RAM usage: …
=> integration/builder: Make bios console configurable + add no console option

litex/build/generic_platform.py
This PR try to provides a solution to comments in [PR](https://github.com/litex-hub/litex-boards/pull/418).
- the first commit add a serie of method, similar to `add_extension`, to allows extending connectors dictionary dinamicaly
- second commit add, when a connector reference another connector, a recursive way to retrieve pin name.
=> Improve connectors

litex/build/xilinx/f4pga.py
Some modules/functions were reorganised in f4pga (see https://github.com/chipsalliance/f4pga/pull/620). This PR updates the imports.
=> litex/build/xilinx/f4pga: update imports

litex/soc/cores/video.py
This PR adds specific HDMI Phy implementation for Gowin devices.
This class is similar to `VideoHDMIPHY` but use **OSER10** as 10:1 serializer and **ELVDS_OBUF** for output differencial buffer.
Tested with @sipeed tangNano4K and tangPrimer20K
=> soc/cores/video: adding Gowin HDMI Phy

litex/soc/cores/dma.py
I'd like to use the `WishboneDMAWriter` to receive packets from a stream, and this PR addresses two issues I were having:
The first is that originally `sink.ready` were set while idle, effectively blackholing data until the DMA is enabled. I think in general it's more reasonable to apply backpressure until DMA is enabled, so I changed this.
The second is that I've got a packetized stream and would like to preserve the packet boundaries, so I added the ability to stop early when the `last` flag is set. For applications where this behavior is not desired, the `last` flag can be stripped from the stream before passing it to `WishboneDMAWriter`.
=> Improve DMA

litex/build/lattice/icestorm.py, litex/build/lattice/oxide.py, litex/build/lattice/trellis.py, litex/build/nextpnr_wrapper.py, litex/build/yosys_nextpnr_toolchain.py, litex/build/yosys_wrapper.py
Toolchains based on *yosys+nextpnr+packer* have more or less same options: in this [PR](https://github.com/enjoy-digital/litex/pull/1435)  3 toolchains have to be updated to add the same option.
*packer* part is target dependant and it make sense to keep tihis at toolchain level, but only a subset of *yosys* and *nextpnr* are hardware dependants: consequently having those at the wrapper level is more logical.
This PR move *yosys* args to `YosysWrapper`, *nextpnr* args to `NextPNRWrapper` and keep only specifics options (primarely packer) at toolchain level. Since *icestorm*, *trellis* and *oxyde* toolchains uses `YosysNextPNRToolchain`, this one is updated too to add an abstraction layer.
=> build/yosys,nextpnr, lattice: refactor args

litex/build/xilinx/vivado.py
+ add option to limit vivado threads.
I'm a big fan of the argparser choice field, but sadly the directives change depending on the vivado version, so the options now accept everything. This change should also not change any defaults!
=> Vivado: Make directives configurable via argparser

litex/soc/software/demo/demo.py
Fixes a couple minor issues with the bare metal software demo encountered under Nix.
1. Programs are stored without write permissions. The demo data copied to the build directory is made writable after the copy so the linker script can be modified and it can be built.
2. The Python executable is a wrapper which also sets up library paths and so forth. The current Python executable is reused to generate the final output binary instead of whichever Python `python3` is to ensure the version of LiteX used is consistent.
=> demo: fix minor build issues

litex/build/efinix/ifacewriter.py, litex/soc/cores/jtag.py
This PR add efinix user jtag instruction support into litex.
How to use : 
```
class BaseSoC(SoCCore):
...
self.submodules.jtag = jtag = EFINIX_JTAG(platform, 1)
jtag.bind_vexriscv_smp(self.cpu)
```
Here are a the openocd config files used : 
[openocd.zip](https://github.com/enjoy-digital/litex/files/9683304/openocd.zip)
The command for the vexriscv openocd fork : 
CPU_COUNT=1 openocd_riscv/src/openocd -c 'set CPU0_YAML cpu0.yaml' -f t20.cfg -f soc.cfg 
@enjoy-digital 
One question is about getting the name of a Subsignal, i'm doing it as : 
pins.mySubSignal.backtrace[-1][0]
Not sure that's realy the good way XD
=> Add Efinix JTAG support, with vexriscv-smp binding function

litex/build/altera/quartus.py
This fixes two issues that prevented clock constraints (e.g. "add_false_path_constraint") from working properly in Quartus.
The first fix passes the "keep" synthesis attribute through to the generated Verilog in a way Quartus can understand.
The second fix tells Quartus to name PLL clocks according to their net instead of the physical pin name by passing the "use_net_name" flag to "derive_pll_clocks" in the .sdc file. Combined with the above, PLL clocks will now be named according to the kept net.
This fix has been verified on Quartus Prime Lite 20.1.1.720.
=> build/altera: fix clock constraints

litex/soc/cores/clock/intel_common.py, litex/soc/cores/clock/intel_cyclone10.py, litex/soc/cores/clock/intel_cyclone4.py, litex/soc/cores/clock/intel_cyclone5.py
Fix some issues and do some cleanup around the logic to compute appropriate PLL values for Intel FPGAs and Quartus.
The big one is to properly respect the limitations on PFD input frequency to avoid generating values Quartus will refuse to synthesize. The appropriate frequency values have been confirmed against each device family's datasheet.
But there are also tweaks to reduce the time taken to compute the configuration (on my machine with my design) from about 6.6s to about 270ms which is helpful particularly when just loading the design.
=> soc/cores/clock: improve Intel PLL calculation

litex/soc/cores/cpu/cv32e41p/csr-defs.h, litex/soc/cores/cpu/cv32e41p/irq.h, litex/soc/software/libbase/isr.c
I have added the right values of  CSR_IRQ_PENDING and CSR_IRQ_MASK (based on cv32e41p documentation). and fixed irqs handling functions(irq_setmask, irq_pending and irq_getmask) in irq.h (inspired from ibex interrupts support PR:#1070).
- Machine Interrupt Pending Register (mip): CSR_IRQ_MASK: 0x344
- Machine Interrupt Enable Register (mie): CSR_IRQ_PENDING: 0x304
Tested on Digilent arty a7 100T.
```
(c) Copyright 2012-2022 Enjoy-Digital
BIOS built on Oct 19 2022 14:26:40
BIOS CRC passed (59910ade)
Migen git sha1: 639e66f
LiteX git sha1: a0853d15
CPU:		CV32E41P @ 100MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR: …
```
=> Fix IRQS handling for cv32e41p

litex/build/generic_toolchain.py, litex/build/lattice/icestorm.py, litex/build/nextpnr_wrapper.py, litex/build/xilinx/f4pga.py, litex/build/yosys_nextpnr_toolchain.py
- Second commit adapts `edam` dictionnary according to backend used: With the recent integration of **edaflow** (used for **f4pga**) `edam` is currently a bit different between `f4pga` and `icestorm` This why toolchain return a dict with key == `flow_options` for backend using `eda_flow` or `tool_options` for classic backend
- third commit fix a second typo: **edalize** search for a constraints with `file_type` equal to `xdc` (lower case)
- fourth commit add **edalize** support for **f4pga** toolchain.
- last 2 commits adds getter for PNR options to nextpnr to have access to the complete PNR configuration
Tested with **icebreaker** and **arty_a35t** (after disabling `DNA` and `XADC`).
=> F4pga edalize

litex/soc/cores/cpu/cv32e40p/core.py, litex/soc/cores/cpu/cv32e41p/core.py, litex/soc/cores/cpu/cva5/core.py, litex/soc/cores/cpu/femtorv/core.py, litex/soc/cores/cpu/firev/core.py, litex/soc/cores/cpu/ibex/core.py, litex/soc/cores/cpu/neorv32/core.py, litex/soc/cores/cpu/picorv32/core.py, litex/soc/cores/cpu/serv/core.py
The csr opcodes are no longer part of the i instruction set, and must be enabled separately. This can be done by adding _zicsr to the march string, eg. -march=rv32i_zicsr. However this is not recognised by older toolchains, so we can't change over until everyone is using binutils 2.28 or later.
An alternate fix was merged for Vexriscv by patching .S files in https://github.com/enjoy-digital/litex/pull/1292. This only fixes the problem for .S files, so the usage of csr instructions in c files was still broken.
Later it was fixed for all source files for Vexriscv in https://github.com/enjoy-digital/litex/pull/1321 by telling the compiler to target the 2.0 ISA, where the csr instructions were still present.
Make the same change to all riscv cpus that specify -march=rv32. This should allow …
=> riscv: Fix compilation with new binutils

litex/soc/software/demo/Makefile
Defines WITH_CXX to the C compiler when including hello.cpp in the demo. This fixes a bug wahere the the menu did not include the hellocpp item even when --with-cpp was passed to demo.py
Signed-off-by: Alan Green <alan.green@gmail.com>
=> soc/software/demo/Makefile: define WITH_CXX

litex/soc/cores/video.py
An earlier patch fixed the swapped red and blue channels on the HDMI PHYs. This exposed the fact that the framebuffer readout was swapped too.
The framebuffer readout is fixed by this patch to match the r5g6b5 and a8b8g8r8 color format definitions documented in the Linux kernel's simplefb driver and used by LiteX:
https://www.kernel.org/doc/Documentation/devicetree/bindings/display/simple-framebuffer.txt
This has been tested using 16 bit SDRAM in both supported color formats.
Additionally the green color used by the video terminal is swapped. It now matches the color used by LiteX on Ubuntu's terminal, from which it was probably originally sourced.
=> soc/cores/video: fix framebuffer color output

litex/soc/cores/cpu/openc906/core.py, litex/soc/cores/cpu/openc906/crt0.S, litex/soc/cores/cpu/openc906/system.h
This PR contains some fixes and enhancements for OpenC906.
Hardware side, it fixes AXI characteristics and added an integrated AXI2WB bridge as workaround like CVA6 does.
Software side, cache flushing is fixed and some other performance-related options are enabled.
=> misc openc906 fixes and enhancements

litex/soc/software/bios/cmds/cmd_i2c.c, litex/soc/software/bios/cmds/cmd_litedram.c, litex/soc/software/libbase/i2c.c, litex/soc/software/libbase/i2c.h
Add another parameter to i2c_read/write to specify the size (in bytes) of the addresses.
i2c_read/writes with 2-byte addresses were tested with a OV5647 camera.
=> soc/software: Support non 8bit i2c memory addresses

litex/soc/integration/soc.py, litex/soc/interconnect/wishbone.py
Provides an alternate API to some functions of the SoCBusHandler and bus Arbiter classes to allow users of the API to avoid the terms 'master' and 'slave' in certain situations.
See discussion at #1025
=> litex/soc: update API to avoid unfortunate terms

litex/soc/integration/soc.py, litex/soc/interconnect/csr_bus.py
Currently the code uses the SoC bus width to calculate the alignment of CSR banks.
However when we get AXI-Lite interconnect support, the CSR bus is not directly converted from SoC bus now, instead an intermediate bus with default parameter (which means 32-bit) is created, CSR bus is converted from it, and finally this bus is attached to the main interconnect with auto converter if needed. In this case the intermediate bus is always of 32 bit bus width, eliminating the need of caring the SoC bus width when handling CSR banks.
Tested on 64-bit SoC bus width now; to make the bus further wider, other codes need to be changed either.
=> soc/interconnect/csr: Fix CSR on 64-bit SoC bus width

litex/soc/integration/common.py, litex/soc/integration/soc.py
OpenC906 core has a 128-bit data width bus, which could benefit from a wider SoC bus.
This PR includes two commits, one adding support for ROM initialization of a wider bus, the other attaching LiteDRAM to the SoC bus with a wider data port, allowing to utilize the full SoC bus width.
This increases sequential DRAM read speed of openC906 in LiteX from 110MB/s to 190MB/s when using a 128-bit SoC bus.
=> Misc changes for a wider SoC

litex/soc/software/common.mak
Some builds may default to creating position independent executables with a .dynamic section containing symbols that must be relocated at runtime. This section appears after .data section and is included in the output .bin, causing it to be included in the build time CRC calculation. The runtime CRC calculation stops after .data, so there was always a mismatch.
The litex bios has no support for relocating the dynamic symbols, so disable pie on all platforms. This will improve compatibility with distro toolchains.
Tested with:
marocchino / or1k-elf-gcc (GCC 12.1.0-2 Debian 1.0.3) 12.1.0
vexriscv / riscv64-linux-gnu-gcc (Debian 12.2.0-3) 12.2.0
microwatt / powerpc64le-linux-gnu-gcc (Debian 12.2.0-3) 12.2.0
=> Do not build software as PIE

litex/build/altera/platform.py, litex/build/anlogic/platform.py, litex/build/argument_parser.py, litex/build/efinix/platform.py, litex/build/generic_platform.py, litex/build/gowin/platform.py, litex/build/lattice/__init__.py, litex/build/lattice/icestorm.py, litex/build/lattice/oxide.py, litex/build/lattice/platform.py, litex/build/lattice/radiant.py, litex/build/lattice/trellis.py, litex/build/microsemi/platform.py, litex/build/osfpga/platform.py, litex/build/quicklogic/platform.py, litex/build/sim/platform.py, litex/build/xilinx/__init__.py, litex/build/xilinx/platform.py
Currently toolchains args are managed at targets level. This imply code dupplication and sometime missed args for a toolchain (for example with lattice nexus). FPGAs may have one toolchain (**ice40**, **efinix**), two (**ecp5**, **nexus**) or more (*xilinx* serie7 with **vivado**, **nextpnr** and **f4pga**).
This approach mean, when one wish to add a new toolchain for an existing device, an update must be done at **litex-boards** level to reflect alternate toolchain, with potential forget.
The idea of this PR is to add a two functions, at `build/xxx/platform.py` level, taking family model:
- first: fills argparse by calling all supported toolchain for family FPGAs and, when necessary, adds `toolchain` argument
- second: according to `family` and `toolchain` arguments fills the dict with …
=> build/lattice/platform: lattice_args, lattice_argdict: refactorize toolchains args

litex/build/parser.py
When the platform is None `add_target_group` is never called and consequently `_target_group` is None.
If a call is done to `add_target_argument` an error appear.
This may appear with `simple.py` where the plaform is known at `parse_args` time so after adding **toolchain** argument.
This PR updates `add_target_argument` to first test `_target_group`, create the group if required before using `_target_group.add_argument`
=> litex/build/parser: check if self._target_group is not None before calling add_argument

litex/soc/cores/cpu/openc906/core.py
This PR adds a debug variant, which behaves like the VexRiscv debug variant, that maps the DM onto the system bus.
The DM itself is RV Debug Spec 0.13-compliant.
=> cpus/openc906: add debug variant like vexriscv

litex/tools/litex_sim.py
The LiteX OpenC906 core currently uses 0x0 as the base of main memory.
Hack to allow this when preloading a binary in litex_sim by adding a command line argument.
=> tools/litex_sim: hack to allow memory base other than 0x40000000

litex/soc/cores/cpu/naxriscv/core.py
The use of os.system together with cd is a problem because it changes the CWD for the whole python process. This breaks for example --csr-csv.
--> The csr.csv will be written to the wrong directory
=> core/naxriscv: Don't use os.system to execute sbt

litex/soc/interconnect/axi/axi_full.py
This patch allows the AXICrossbar to absorb non-default datawidths when the crossbar is built.
e.g. in the case of a 64-bit AXICrossbar, without this patch the crossbar was only connecting the bottom 32 bits.
=> AXICrossbar: absorb data width setting when building crossbar

.github/workflows/ci.yml, test/test_cpu.py
Add GHDL to the build image to convert VHDL to Verilog, and use the distro compiler for ppc64le.
The Microwatt design caused verilator to be killed when compiling, which was probably due to the memory requirements of a large number of compiler jobs. Limit the number of jobs used by the test harness when running verilator.
=> Add Microwatt CI

litex/soc/interconnect/wishbone.py
Right now, when multiple masters want to access the bus, access is granted to one of them, and is not revoked until selected master has finished all of its transactions (cyc goes low).
This state causes master starvation if access is granted to high bandwidth master, like cpu in busy loop.
This commit makes it so access to bus is revoked when pending transaction is finished (ack and cyc are high) or when selected master is idle.
=> Fix Wishbone arbiter

test/test_cpu.py
With CI supporting GHDL to convert VHDL to Verilog the neorv32 simulation can be tested.
Fixes https://github.com/enjoy-digital/litex/issues/1320
=> test_cpu: Add NeoRV32 to tested CPUs

litex/soc/cores/cpu/zynq7000/core.py
I implemented the add_axi_gp_slave function of the zynq7000 to use it with this [puil request](https://github.com/litex-hub/litex-boards/pull/453). The goal is to access the DDR and the IOPs of the processing system from a soft CPU on the PL.
The implementation is quite similar to the  existing `add_axi_gp_master` and `add_axi_hp_slave` functions, but I added the clock domain as an argument, because one might not want to use the ps7 clock in every case.
=> Zynq7000: Implement function to add axi gp slave

litex/soc/integration/soc.py
CPUs with a dedicated memory port (bus) can be connected directly to the LiteDRAM port. Some models (e.g., Rocket) have otherwise equivalent variants specifically pre-generated to fit the various "standard" LiteDRAM port widths (so far, 64, 128, and 256 bits).
This patch introduces a warning when the CPU variant's dedicated memory bus width doesn't exactly match the width of LiteDRAM, requiring explicit Up- or Down-conversion.
The goal is to inform the user and give them the opportunity to pick a more suitable CPU variant (of a matching MemBus width), if available.
=> integration/soc: Warn on MemBus <-> LiteDRAM AXI width conversion

litex/soc/software/demo/linker.ld
When using printf in the demo application, gcc emits .got and .toc sections which are placed in SRAM by default. This breaks printf and other functions relying on the GOT if the demo is loaded into flash or ROM. This pull request matches the demo's .rodata section to that of the BIOS.
=> software/demo: Add .got and .toc to .rodata in linker script

litex/soc/software/liblitedram/sdram.c
This PR covers some small fixes to liblitedram, one about using the longest 1 for read-leveling, one about scale up values in clk/cmd delay calibration, and the last about an off-by-1 error when write leveling.
=> Some small changes to liblitedram

litex/soc/cores/cpu/openc906/crt0.S
Copy all feature and performance related CSR configuration from sun20i_d1_spl, which are values Allwinner suggests for D1 SoC.
=> cpu/openc906: set extended CSRs based on D1 configuration

litex/build/sim/core/Makefile, litex/build/sim/core/modules/gmii_ethernet/Makefile, litex/build/sim/core/modules/rules.mak, litex/build/sim/core/modules/xgmii_ethernet/Makefile
Homebrew on arm64 Mac is now in /opt/homebrew by default.
=> Fix sim module build on MacOS arm64

litex/soc/integration/builder.py
Recently PyPi version of meson changed to 1.0.0 which uncovered this bug which caused the error condition to triggger falsely.
=> builder: Fix logic for determining meson version compatibility

litex/soc/interconnect/axi/axi_full.py
There is no WID in AXI4, its there only in AXI3.
Probably was a typo in the first place
=> Fix WID in axi versions

litex/soc/cores/jtag.py
This pull request adds more part numbers to the JTAG primitive dictionary. It also changes `get_primitive` to return the closest match to the beginning of a part number.
This is required for parts such as `EP2S`, which shares the same signature as `EP2SGX` while using different JTAG primitives.
=> cores/jtag: Add more Altera part numbers

litex/build/xilinx/vivado.py
a286d77e introduced a bug, where `-include_dirs` parameter is incorrectly defined.
Following TCL code is being generated:
```tcl
synth_design -directive default -top digilent_arty -part xc7a35ticsg324-1L -include_dirs \{.join(self.platform.verilog_include_paths)}\}
```
Below is an explanation why it didn't work:
Python's f-strings escape curly braces using double curly braces like so `{{` instead of using backslash `\{`.
What's more, you need to alternate single and double quotations marks when using strings in curly braces expression otherwise two string objects are being generated and errors like this one can happen.
Signed-off-by: Michal Sieron <msieron@antmicro.com>
=> build/xilinx/vivado: fix verilog include paths

litex/soc/integration/builder.py, setup.py
The current check compares the integers split out from `meson --version` one by one. This is an ad-hoc version comparison algorithm with a few flaws, notably that it doesn't truly understand how version components fit together, and that broke once Meson bumped the major version. There are other potential issues that could show up but haven't yet, such as versions with words in them (release candidates).
The packaging module is a high-quality library that provides a standard version parsing algorithm, with which you can simply say "is this version object greater than that one". Use it instead.
Fixes #1545
=> replace Meson version check with a specification-compliant version comparator

litex/soc/integration/builder.py, litex/soc/software/bios/cmds/cmd_litedram.c, litex/soc/software/bios/main.c, litex/soc/software/liblitedram/Makefile, litex/soc/software/liblitedram/sdram_spd.c, litex/soc/software/liblitedram/sdram_spd.h, litex/soc/software/liblitedram/utils.c, litex/soc/software/liblitedram/utils.h
- add generic `sdram_read_spd` function, that automatically changes SPD pages
- make `sdram_spd` command read entire SPD
- print memory sizes using `print_size` function, which selects appropriate unit (`B/KiB/MiB/GiB`)
- make printed SDRAM size match, actually supported memory size by litedram. Read module size from the SPD and multiply it by the number of modules defined by litedram.
- do not choose between printing either main RAM size or SDRAM size, as they might differ. Rather print both if available
This PR requires changes in litedram from PR https://github.com/enjoy-digital/litedram/pull/320:
- definition of `SDRAM_PHY_SUPPORTED_MEMORY` as a fallback when SPD is not available
- definition of `SDRAM_PHY_[DDR3|DDR4|...]` to select appropriate code paths when reading and parsing the …
=> liblitedram: SPD read improvements

litex_setup.py
The current setup script does not install the needed dependencies for Arch Linux machines (such as Risc-V and OpenRISC).
This PR adds support, installing these packages:
- riscv : https://archlinux.org/packages/community/x86_64/riscv64-linux-gnu-gcc/
- openrisc : https://archlinux.org/packages/community/x86_64/or1k-elf-gcc/
I also found [this](https://aur.archlinux.org/packages/powerpc-linux-gnu-gcc) AUR package for the PowerPC toolchain, but since its AUR, I'm not sure if I should include it.
=> Add Arch Linux setup support for RISC-V and OpenRISC toolchains

litex/soc/software/liblitedram/sdram.c
When using x4 modules, their response makes up only half a byte. We need to extract the nibble and then test it.
Signed-off-by: Michal Sieron <msieron@antmicro.com>
=> software/liblitedram: fix write leveling for x4 modules

litex/soc/software/liblitedram/sdram_spd.c
Fix a silly error with indexing output buffer. The first version of this function was supposed to read the entire SPD and after adding `len` parameter I forgot to edit the used index.
What's unlucky is that its current two uses (reading from the first page and reading the entire SPD) didn't expose this bug.
Signed-off-by: Michal Sieron <msieron@antmicro.com>
=> liblitedram/sdram_spd: fix invalid buffer index

litex/soc/software/liblitedram/utils.c
Use format constants for fixed width integer types to make it work on both 32-bit and 64-bit CPUs without warnings.
Fixes #1573
Signed-off-by: Michal Sieron <msieron@antmicro.com>
=> liblitedram/utils: fix format warnings

litex/soc/software/bios/cmds/cmd_litedram.c, litex/soc/software/liblitedram/bist.c, litex/soc/software/liblitedram/bist.h, litex/tools/litex_sim.py
This PR adds `sdram_hw_test` command, which uses BIST modules that are enabled when `with_bist=True` in `add_sdram` method.
It allows performing a memtest (similar to `sdram_test`), but using DMAs and bypassing system bus. This way, one can test ranges above 4 GiB, which was the limit with `sdram_test` due to address_width being limited to 32 bits.
Additionally I reworked already existing BIST functions a little bit:
- fixed `SDRAM_TEST_DATA_BYTES` definition
- extracted code to `sdram_bist_[write|read]` functions
- made global variables static
- fixed formatting
It would be best if https://github.com/enjoy-digital/litedram/pull/321 would be merged as well, although they should be independent.
=> Add `sdram_hw_test` command

litex/soc/software/libbase/memtest.h, litex/soc/software/libbase/progress.h, litex/soc/software/libbase/spiflash.h, litex/soc/software/liblitedram/bist.h, litex/soc/software/liblitedram/sdram.h, litex/soc/software/liblitedram/sdram_dbg.h, litex/soc/software/liblitedram/sdram_spd.h, litex/soc/software/liblitedram/utils.h, litex/soc/software/libliteeth/inet.h, litex/soc/software/libliteeth/mdio.h, litex/soc/software/libliteeth/tftp.h, litex/soc/software/libliteeth/udp.h, litex/soc/software/liblitesata/sata.h, litex/soc/software/liblitesdcard/sdcard.h, litex/soc/software/liblitesdcard/spisdcard.h, litex/soc/software/liblitespi/spiflash.h
I'm trying to use LiteX libraries with a cpp code (a simulation using verilator), but at link step compilation fails with error like:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/11/../../../../x86_64-pc-linux-gnu/bin/ld: top_tb.o: in function `main':
top_tb.cpp:(.text.startup+0x1ca): undefined reference to `sdram_init()'
collect2: error: ld returned 1 exit status
make[1]: *** [Vtop_tb.mk:66: Vtop_tb] Error 1
```
This is due to a different naming between C and CPP
by adding, before functions declaration in headers:
```C
#ifdef __cplusplus
extern "C" {
#endif
```
And, these lines, at the header end
```
#ifdef __cplusplus
}
#endif
```
The problem is fixed and cpp code may be linked to LiteX libraries.
=> soc/software/libXX/YY.h: adding extern C (required to link with cpp code)

litex/soc/cores/clock/gowin_gw1n.py
I'm doing some simulations for Gowin *gw2a* using *verilator* but it complains about wrong size for some PLL's signals like:
```
%Warning-WIDTH: build/gateware/test_oserdese2.v:10451:3: Input port connection 'ODSEL' expects 6 bits on the pin connection, but pin connection's CONST '1'h0' generates 1 bits.
: ... In instance top_tb.dut
10451 |  .ODSEL(1'd0),
|   ^~~~~ 
``` 
This is, also, confirmed by Gowin's tool:
```
WARN  (EX3670) : Actual bit length 1 differs from formal bit length 6 for port 'ODSEL'("/somewhere/build/sipeed_tang_primer_20k/gateware/sipeed_tang_primer_20k.v":11651)
```
This patch replace *int* values by a `Constant` to explicitly specify signals size.
=> soc/cores/clock/gowin_gw1n: fix size for ODSEL, FBDSEL, IDSEL, PSDA, DUTYDA, FDLY

litex/soc/software/bios/cmds/cmd_litedram.c, litex/soc/software/liblitedram/Makefile, litex/soc/software/liblitedram/accessors.c, litex/soc/software/liblitedram/accessors.h, litex/soc/software/liblitedram/sdram.c, litex/soc/software/liblitedram/sdram.h
This PR introduces a number of changes that clean up existing liblitedram code.
It extracts existing functions like `write_rst_dqs_delay` or `write_inc_dq_delay` to separate file - `accessors.h`.
As all those functions are used in the same way:
- select module (and optionally specific line)
- increment or reset current delay
- deselect module and line
a new function was added `sdram_leveling_action`, which abstracts this away.
Support for x4 IC configuration was fixed and ability to train individual DQ lines was added.
Additionally, comments were added to `#endif`s, which indicate conditions of their `#if`s.
All changes were tested on Digilent Arty A7 board and [Antmicro Data Center DRAM Tester](https://github.com/litex-hub/litex-boards/blob/master/litex_boards/targets/antmicro_datacenter_ …
=> Liblitedram cleanup

litex_setup.py
Has mentioned in issue #1589, `litex_setup`'s message about `PATH` env variable is limited to the temporary update (current terminal only).
This PR update this message to explains  how to add *~/.local/bin* permanently into `PATH`.
=> litex_setup: explain how to update permanently PATH env variable (#1589)

litex/soc/cores/usb_ohci.py
Hi. This PR adds support for multiple host ports to the usb_ohci module. It has been tested with [this PMOD](https://github.com/machdyne/usb_host_dual_socket_pmod).
I had to change `sbt "lib/runMain ..."` to `sbt "runMain ..."` in order to generate the Verilog.
Usage example:
```
("usb_host", 0,
Subsignal("dp", Pins("PMODB:0 PMODB:2")),
Subsignal("dm", Pins("PMODB:1 PMODB:3")),
IOStandard("LVCMOS33")
),
```
=> support multiple usb_ohci ports

litex/soc/software/bios/cmds/cmd_litedram.c, litex/soc/software/liblitedram/sdram_spd.c, litex/soc/software/liblitedram/sdram_spd.h, litex/soc/software/liblitedram/utils.c
This PR provides two fixes for the `sdram_spd` interface.
The most important one is f84ecaf707d2102dc2e2572b45ded465a236c19b, which disables sending STOP signal after setting address counter during the read operation. Turns out, some SPDs allow operation when STOP is being sent, but spec specifies that the STOP symbol shouldn't be sent.
I removed the option to select `send_stop` value from the API and the BIOS command.
[The second fix](cdc1152162d5c2bdb773dd31915a7aef4de8f1f0) is not that impactful. When implementing `sdram_spd` interface for the first time, by mistake, I made it so that in one loop iteration `len` bytes are being read instead of `temp_len`. This worked, because we never read more bytes total than requested and `len - temp_len` extra bytes that were being read in one …
=> SDRAM SPD fixes

litex/tools/litex_term.py
Like commit 460fada3acbc6626f15388e4259bec0058b4a2d6, multiprocessing breaks on Windows and macOS due to pickle failures.
=> tools/litex-term: completely eliminate multiprocessing

litex/soc/cores/gpio.py
Hello, in relation to this issue (#1612)  I suggest a fix for other people who may have the same problem.
It seems that the generation of CSR for GPIOIN with IRQ enable is changed with the updates.
I hope I helped.
=> Fix GPIO IRQ CSR generation

litex/build/efinix/efinity.py
The first time an efinix's target is executed `iface.py` produces errors like:
```
Efinity project file does not exists : ../gateware/efinix_titanium_ti60_f225_dev_kit.xml
File error : Efinity project file does not exists : ../gateware/efinix_titanium_ti60_f225_dev_kit.xml
Efinity project file does not exists : ../gateware/efinix_titanium_ti60_f225_dev_kit.xml
File error : Efinity project file does not exists : ../gateware/efinix_titanium_ti60_f225_dev_kit.xml
```
The second time these errors disapears.
This is due to the order where scripts are build. Currently:
- `peri.xml` is build by `build_io_constraints()`, `iface.py` is also called here
- `project.xml` is build by `build_project()`
But since `build_io_constaints()` is called before `build_project()` `iface.py` can't have access to …
=> build/efinix/efinity: delays iface.py execution after project xml was written

litex/build/altera/platform.py, litex/build/anlogic/platform.py, litex/build/efinix/platform.py, litex/build/generic_platform.py, litex/build/gowin/platform.py, litex/build/lattice/platform.py, litex/build/microsemi/platform.py, litex/build/osfpga/platform.py, litex/build/quicklogic/platform.py, litex/build/xilinx/platform.py, litex/soc/integration/builder.py
When getting bitstream's filename the current behaviour for *soc/integration/builder* is to use directly `soc.platform.bitstream_ext` for **sram** mode and returning **bin** for flash. This imply, at **targets** level, for flash mode, to use `get_bitstream_filename`'s *ext* parameter to force correct extension.
This PR add, at *build/generic_platform* a method to return extension according to `mode` (may be the same extension for both case when *build/vendor/platform.py* declare `_bitstream_ext` as a string or two different extension when `_bitstream_ext` is a dict).
This also fix extension for anlogic (*fs* is for *gowin* FPGA).
=> add a proxy method to access bitstream extension

litex/soc/cores/cpu/vexriscv_smp/core.py
Fix: VexRiscvSMP core variants for external incoming values and remove default timer0 and uart in standard mode.
=> soc/cores/cpu/vexriscv_smp/core.py: fix variants for external incoming values and remove default timer0 and uart in standard mode.

litex/soc/cores/clock/gowin_gw2a.py
Gowin GW2AR is just GW2A with co-packaged external RAM.
Enable using GW2APLL for GW2AR.
=> soc/cores/clock/gowin_gw2a: enable GW2AR support

litex/soc/cores/bitbang.py
Hi,
I asked on the discord how to add documentation to litex, and the suggestion was to start by adding some docstrings. I have had a go at a small file here (`bitbang.py`), and I would appreciate any feedback on this. I would also like to know if the following would be accepted:
- Changes to whitespace to bring the files in line with PEP8
- Inline typehints where possible
Thanks.
=> add docstrings to bitbang

litex/tools/litex_term.py
The static delay in the current implementation is not always long enough for OpenOCD to start up and find the target. This adds simple retry logic, waiting up to five seconds but still connecting as quickly as possible.
=> litex_term: improve connection setup

litex/soc/cores/clock/gowin_gw1n.py
*Gowin*'s PLL has 4 outputs:
- `CLKOUT` directly connected to `VCODIV` (no phase and a 50% duty cycle)
- `CLKOUTP` is connected to `PS&DCA` (the phase is configurable between 0° and 337.5° by 22.5° step, duty cycle is also configurable
- `CLKOUTD` may be connected to `CLKOUT` or `CLKOUTP` and has a even divisor between 2 and 128
- `CLKOUTD3` may be connected to `CLKOUT` or `CLKOUTP` and has a fixed /3 divisor
Current *Gowin*'s `PLL` support is limited to `CLKOUT` output. Phase, divisors and three others output aren't supported.
This PR complete this support by adding 3 last `CLKOUTx`, phase and divisor computation.
=> soc/cores/clock/gowin_gw1n: add support for CLKOUTP, CLKOUTD, CLKOUTD3, phase and divisor

litex/soc/cores/cpu/cva6/boot-helper.S, litex/soc/cores/cpu/cva6/core.py, litex/soc/cores/cpu/cva6/crt0.S, litex/soc/cores/cpu/cva6/cva6_wrapper/Flist.cva6_wrapper, litex/soc/cores/cpu/cva6/cva6_wrapper/cva6_wrapper.sv
Marking this as a draft for now because:
- ~~the most invasive change was around the debug AXI integration (removing the Xilinx IP cores and replacing them with a Pulp one where needed), which I haven't got a setup to test yet (ideally we could have a way of testing JTAG in sim?)~~ tested and confirmed working using jtagremote, also fixing for 64-bit configs at the same time
- in general it hasn't seen much testing beyond booting the BIOS
- for some strange reason (suspected stack corruption) the compiled verilator binary segfaults when using g++/gcc as compiler; when using clang for the verilated source it works fine
=> CVA6: Adding RV32 support

litex/soc/software/libbase/i2c.c
commit 3fa3080e introduced an additional address length paramater to i2c_write to support non 8bit memory addresses.
But the parameter wasn't added to the call of i2c_write in i2c_send_init_cmds.
This commit fixes the issue by adding the address length parameter to the call of i2c_write.
=> soc/software: fix i2c_write

litex/soc/software/bios/cmds/cmd_spiflash.c, litex/soc/software/liblitespi/spiflash.c, litex/soc/software/liblitespi/spiflash.h
When shipping MNT RKX7, I pre-flash the SPI flash with a LiteX bitfile
for testing. cmd_spiflash had regressed because of changed SPIFLASH defines
and didn't offer the write functions anymore. This commit fixes that, and
adds convenience functions:
- `flash_erase_range <offset> <count (bytes)>`
- `flash_from_sdcard <filename>`
The latter reuses some boot code to copy the contents of the specified
file from the boot FAT partition on the SD card to SPI flash (i.e.
a bitstream).
Some of the code is based on @norbertthiel's comment https://github.com/litex-hub/litespi/issues/52
But edited to work with W25Q128JVS flash used in MNT RKX7.
=> bios/spiflash: fix write/ erase, add write from sdcard and range erase

litex/soc/interconnect/avalon/avalon_mm_to_wishbone.py, test/test_avalon_mm.py
=> AvalonMM2Wishbone: use same addressing on avalon and wishbone, leave address translation to the user

litex/soc/interconnect/avalon/avalon_mm_to_wishbone.py
I just realized this was missing
=> Avalon2Wishbone: Burst can only advance if write is high and waitrequest low

litex/soc/interconnect/avalon/avalon_mm.py, litex/soc/interconnect/avalon/avalon_mm_to_wishbone.py
Also the changes to continue_read_burst are essential for the LiteDRAM frontend.
=> AvalonMM/AvalonMM2Wishbone: fix read bursts (readdatavalid one cycle too short)

litex/soc/software/liblitedram/sdram.c
VCU128 uses clam shell topology for its DRAM components. This pull request adds support for VCU128 clam shell topology.
The pr depends on https://github.com/enjoy-digital/litedram/pull/332.
See https://github.com/litex-hub/litex-boards/issues/496 for background.
=> Add support for clam shell topology

litex/soc/cores/cpu/microwatt/core.py
Fixes: 45b96369021a ("integration/soc: Avoid soc_region_cls workaround and update CPUs.")
=> microwatt: Correct SoCRegion typo

litex/build/lattice/radiant.py
=> fix radiant bug 'Mal-formed command line - please check for extra quotes in macro'

litex/soc/software/bios/cmds/cmd_litesata.c, litex/soc/software/liblitesata/sata.c
Please only apply after https://github.com/enjoy-digital/litesata/pull/25 
Once the LiteSATA gateware is updated to accept a sector-count register, we can issue multi-sector read and write requests in a single DMA operation.
This PR also adds a pair of multi-sector SATAdisk - to - Memory transfer commands to the bios.
=> Update bios for LiteSATA multi-sector read/write changes

litex/tools/litex_json2renode.py
I ran into trouble trying to generate renode config from the json file generated with `python3 -m litex_boards.targets.digilent_arty`.
It simply crashes on various items.
I have worked around the issues to make the script complete and it now generates usable .repl and .resc files now.
=> Make litex_json2renode work with default arty target SOC .json file

litex/soc/integration/soc.py, litex/soc/interconnect/wishbone.py
Allow liteeth txslots to be write only. Enable it in case the firmware does not need to read back the buffer. This can save a substantial amount of resources. Tested on Spartan6. Without it, txbuffers are implemented as distributed RAM, probably due to the 2 read ports. With this patch, it is implemented as BRAM.
Needs to be pulled in conjunction with the corresponding litex patch.
=> Tx write only

litex/soc/cores/cpu/zynqmp/boot-helper.c
This pull request fixes a regression where the computed goto causes an error when compiling the boot helper with newer versions of GCC. The behavior of goto has changed since GCC 12 (see https://gcc.gnu.org/gcc-12/porting_to.html).
=> cores/zynqmp: Fix boot helper

litex/soc/cores/cpu/cortex_m1/boot-helper.c, litex/soc/cores/cpu/cortex_m3/boot-helper.c, litex/soc/cores/cpu/eos_s3/boot-helper.c, litex/soc/cores/cpu/gowin_emcu/boot-helper.c, litex/soc/cores/cpu/zynq7000/boot-helper.c
This pull request fixes the computed goto of all ARM boot helpers. The issue is identical to #1724.
=> cores/arm: Fix computed goto in boot helpers

litex_setup.py
Starting with ubuntu 22.04, when a target is configured with ethernet and/or sata the sofware build fails with:
```
/usr/lib/gcc-cross/riscv64-linux-gnu/12/../../../../riscv64-linux-gnu/bin/ld: ../libc/libc.a(libc_ssp_chk_fail.c.o): in function `__chk_fail':
/somewhere/litex-boards/litex_boards/targets/build/digilent_arty/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/ssp/chk_fail.c:13: undefined reference to `write'
collect2: error: ld returned 1 exit status
make: *** [/somewhere/litex/litex/soc/software/bios/Makefile:72: bios.elf] Error 1
```
By switching to *gcc-riscv64-unknown-elf* (bare-metal toolchain) build end successfully
Fix:
- https://github.com/enjoy-digital/litex/issues/1624
- …
=> litex_setup: fix software build when liteeth or/and litesata is set (riscv toolchain issue)

litex/build/gowin/common.py
The DDRInput of Gowin seems to be never used and contains a typo that prevents it from being really used.
Fix this typo.
=> build/gowin/common: Fix DDRInput

litex_setup.py
To allow offline installation, the "liteiclink" package has to be installed before the "liteeth" package. Otherwise, to satisfy the dependency requirements, the setup will attempt to download the "liteiclink" package from the internet and will consequently fail.
=> Litex offline installation fix

litex/soc/interconnect/stream.py
`BufferizeEndpoints` params now includes whether to pipeline the `valid`/`data` or `ready` path.
=> soc/interconnect/stream: BufferizeEndpoints params

litex/soc/cores/clock/gowin_gw5a.py
GW5A has a different PLL with GW1N/GW2A, with multiple individual ODIV's.
Add basic support for it.
=============
Phase tweaking not tested yet because I have no oscilloscope.
=> soc/cores/clock: initial GW5A support

litex/build/altera/platform.py, litex/build/altera/quartus.py, litex/build/anlogic/anlogic.py, litex/build/efinix/efinity.py, litex/build/generic_platform.py, litex/build/generic_toolchain.py, litex/build/gowin/gowin.py, litex/build/lattice/diamond.py, litex/build/lattice/icestorm.py, litex/build/lattice/radiant.py, litex/build/lattice/trellis.py, litex/build/microsemi/libero_soc.py, litex/build/osfpga/osfpga.py, litex/build/xilinx/f4pga.py, litex/build/xilinx/ise.py, litex/build/xilinx/vivado.py
This PR allows to specify explicitly a clock name instead of using net/port name.
Note: most of toolchains uses a really similar method to produces sdc -> a refactoring may make sense
=> build/xx/toolchains: allows override clock naming

litex/soc/cores/spi/spi_mmap.py
This change ensures clk_divider represents the true divider. Alternately could test: clk_count == self.clk_divider and document that the actual divide is 2x clk_divider.
=> soc/cores/spi_mmap: Fix clock divider

litex/soc/cores/cpu/vexriscv_smp/core.py, litex/soc/integration/soc.py
An attempt to fix #1761
Also includes a fix for cpu name being replaced with an irq name in the logging.
=> proof of concept coherent dma fix

litex/build/lattice/radiant.py
Under WSL, it is possible to execute `.exe` files.
This patch allows to use Windows-side Radiant from WSL, so that Radiant does not need to be installed inside WSL if it already there outside.
I got feedback that this patch works from who tested it.
=> Allow use of Windows-side (.exe) Radiant toolchain

litex/build/lattice/radiant.py
My bad for breaking it in https://github.com/enjoy-digital/litex/pull/1763
=> build/lattice/radiant: fix uname() not prefixed by 'os.'

litex/soc/cores/clock/gowin_gw5a.py
When targeting GW5A-25 ES, the Gowin IDE has a more strict frequency range.
Change the range when GW5A- is matched to this.
=> clock/gowin_gw5a: change allowed frequency range for GW5A- prefix

litex/soc/cores/cpu/naxriscv/boot-helper.S, litex/soc/cores/cpu/naxriscv/core.py, litex/soc/cores/cpu/naxriscv/crt0.S, litex/soc/integration/soc.py, litex_setup.py
Support multi core / coherent dma, can run doom on debian.
=> core/naxriscv provide a deployable NaxRiscv SMP

litex/soc/cores/cpu/neorv32/core.py
- Update NEORV32 to verion 1.8.9 to fix debugger support
- Moved _io_regions_ to a non cached memory address space. This is due to the new NEORV32 memory layout.
- Add cpu variants with _debug_ 
- Add jtag debugger signals. Example code added in SoC class to connect debug pins:
```
self.comb += [
self.cpu.i_jtag_trst.eq(1),
self.cpu.i_jtag_tck.eq(platform.request("tck")),
self.cpu.i_jtag_tdi.eq(platform.request("tdi")),
platform.request("tdo").eq(self.cpu.o_jtag_tdo),
self.cpu.i_jtag_tms.eq(platform.request("tms")),
]
```
=> Add Debug support for NEORV32

litex/tools/litex_json2renode.py
--bios-binary is reverted to loading the bios into _rom_ as per the documentation and litex defaults --opensbi-binary is added to load the openSBI binary into the opensbi memory region
The examples documented in the wiki now work again
Fixes #1785
The [Generate Renode simulation](https://github.com/enjoy-digital/litex/wiki/Generate-Renode-simulation) wiki page should also have one more section:
Finally, you can ~~run~~ load the simulation by executing the command:
```
renode litex.resc
```
Then in the renode terminal window execute the `start (or s)` command to boot the bios
```
(litex_vexriscv) start
```
@MateuszKarlic I think this change makes sense but as you have done more significant changes in the past maybe you can confirm this approach.
=> litex_json2renode: fix --bios-binary and add --opensbi-binary

litex/soc/cores/clock/colognechip.py
This PR adds the `CC_PLL` primitive for the **CologneChip GateMate* 
- the  input clock may be a clock compatible pin or an internal signal
- 4 output clocks are available: first has a 0° phase shift, second has a 90° phase, third a 180° phase and the last 270°. First and second output provides a signal at the frequency fixed by `OUT_CLK`, last two clocks may be x1 or x2 `OUT_CLOCK`
- `CC_PLL` may or not provides a signal before DCO is locked
\cc @pu-cc
=> soc/cores/clock: adding CologneChip CC_PLL

litex/build/anlogic/platform.py, litex/build/colognechip/platform.py, litex/build/generic_platform.py, litex/build/gowin/platform.py, litex/build/microsemi/platform.py, litex/build/parser.py, litex/build/quicklogic/platform.py, litex/build/xilinx/platform.py, litex/soc/integration/soc_core.py
- `--with-jtagbone` and `--with-uartbone` are now integrated in SoCCore arguments. This class also handle `add_jtagbone` and `add_uartbone`
- when a target try to add one of this option a warning is displayed and insertion is bypassed
- `crossover+uartbone` is deprecated -> `--uart-name=crossover --with-uartbone`
- jtag capability ((un)supported) is now handled at platform level
=> soc/integration/soc_core: add new parameters --with-uartbone and --with-jtagbone, deprecate crossover+uartbone

litex/soc/cores/clock/lattice_ecp5.py
Disclaimer:  I am not a Lattice employee and do not have access to internal documentation -- anything below regarding internal workings of the PLL should be taken as conjecture.  PLLs are not complicated things though, so it's not that difficult to suss out how they work.  :smile:
The current phase calculation for ECP5 EHXPLLL has two problems:
1) It doesn't set FPHASE at all.  This value is a phase offset in eighths of a VCO cycle added to CPHASE, so the calculation of CPHASE should be done as fix-point with three fractional bits.  Diamond also performs correct rounding based on the fourth fractional bit.
2) The CPHASE calculation uses `div+1` as the scale factor for a complete clock period.  This is obviously wrong as a complete period is `div` VCO cycles, not `div+1`.  I believe the …
=> cores/clocks/lattice_ecp5: Fix phase calculation to match Diamond output

test/test_csr.py
'status' reads as 0 in simulation when CSRStatus has fields that are assigned in the design. This test case demonstrates the issue  but is wrapped in a try/catch so the rest of the tests can run without a CI failure.
I'm not sure how to fix the underlying issue, but can work around it in my core tests that discovered this issue.
=> test_csr: test cases to demonstrate a CSRStatus() issue

litex/soc/cores/uart.py, litex/soc/integration/soc.py
This PR contains 3 commits:
- `Stream2Wishbone`: update allowed address_width list to support 64bits (since number of iterations is based on this parameter any size multiple of 8bits may works)
- `UARTBone`: now it's possible to pass address_width to the constructor (this param is used for Stream2Wishbone)
- soc: `self.bus.address_width` is now used at `UARTBone` constructor time
=> UARTBone addr width

litex/tools/litex_client.py, litex/tools/litex_server.py, litex/tools/remote/comm_uart.py, litex/tools/remote/csr_builder.py, litex/tools/remote/etherbone.py
This PR has for goal to remove all hardcoded address width.
- For `litex_client` the address width is obtained from *csr.csv*
- For `litex_server` a new argument is added to select addr_width (default: 32bits)
=> tools: litex_server, litex_client and remote: don't hardcode bus address

litex/soc/interconnect/wishbone.py
Allows to have masters and slaves with an address_bus != 32bits.
=> soc/interconnect/wishbone: InterconnectShared,Crossbar: using master adr_width for Interface constructor

CHANGES.md, litex/soc/cores/cpu/kianv/__init__.py, litex/soc/cores/cpu/kianv/boot-helper.S, litex/soc/cores/cpu/kianv/core.py, litex/soc/cores/cpu/kianv/crt0.S, litex/soc/cores/cpu/kianv/irq.h, litex/soc/cores/cpu/kianv/system.h
litex_sim --cpu-type=kianv:
(c) Copyright 2012-2023 Enjoy-Digital
BIOS built on Nov  8 2023 11:14:03
BIOS CRC passed (6984e675)
LiteX git sha1: c1e4b3a8
CPU:		KianV-STANDARD @ 1MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR:		32-bit data
ROM:		128.0KiB
SRAM:		8.0KiB
--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
Timeout
No boot medium found
--============= Console ================--
litex> ident
Ident: LiteX Simulation 2023-11-08 11:14:00
litex>
=> cores/cpu: Add KianV CPU (RV32IMA) initial support.

litex/build/gowin/common.py, litex/build/gowin/gowin.py
This PR contains 2 commits:
- an `common.py` update to adds support for Tristate (required for SDRAM phy)
- an comestic update to have a `file` file with same aspect of gowin generated files (IO_TYPE and misc in one line, only _p pins with pair instead of one line for _p and another one for _n).
=> Tang mega138k

litex/soc/integration/soc.py, litex/soc/software/include/irq.h, litex/soc/software/libbase/isr.c, litex/soc/software/libbase/uart.c
cleaner mechanism for other software to use interrupts
NOTE: uart_isr(void) not changed to uart_isr(int) for compatibility with cpus that don't implement this interface yet.
This is a different approach to #1807 and #1735
=> soc/software: add irq_attach() / irq_detach()

litex/soc/integration/soc.py, litex/tools/litex_sim.py
Tighter integration of Ethernet with etherbone. litex_sim updated to use this interface, siglent_sds1104xe will need this update:
```
index dbf8fa4..b473d0e 100755
--- a/litex_boards/targets/siglent_sds1104xe.py
+++ b/litex_boards/targets/siglent_sds1104xe.py
@@ -111,20 +111,7 @@ class BaseSoC(SoCCore):
ip_address  = "192.168.1.51",
mac_address = 0x10e2d5000001,
data_width  = 8,
-                interface   = "hybrid",
-                endianness  = self.cpu.endianness
-            )
-
-            # Software Interface.
-            self.ethmac = ethmac = self.get_module("ethcore_etherbone").mac
-            ethmac_region_size = (ethmac.rx_slots.constant + ethmac.tx_slots.constant)*ethmac.slot_size.constant
-            ethmac_region = SoCRegion(origin=self.mem_map.get("ethmac", None), …
```
=> Hybrid Etherbone simplification

litex/build/efinix/ifacewriter.py, litex/soc/cores/clock/efinix.py
Efinix python API has a bug when feedback is different than "INTERNAL" with, as a result, a wrong configuration. *LOCAL* or *CORE* mode is required for LVDS/serdes rx to align input clk and clk used by LVDS blocks.
This PR currently  only address Trion devices
=> Efinix PLL calc when feedback != INTERNAL

litex/soc/software/bios/boot.c
When using *jtag_uart* with a big file, `serialboot` fails due to a timeout. since JTAG is slower than classic UART, the timeout delay must increased to avoid this failure.
Tested with an arty, femtorv and 1.2MB file
=> soc/software/bios/boot: serialboot: increase CMD_TIMEOUT_DELAY

litex/build/openocd.py
This patch increases the JTAG UART upload speed by switching to nonblocking read mode in the OpenOCD Tcl script, then reading and writing up to 512 byte blocks instead of 1 byte at a time.
On my setup, this increases the LiteX terminal upload speed from 74 bytes per second (assuming I patch out the BIOS's command timeout so uploads are even possible) to about 18.3KB/s. As a quick measure of download speed, the FPS of the donut demo has increased by ~50% as well.
It's not clear to me why blocking mode was used before. I would suggest testing other setups to make sure there aren't any regressions in other scenarios.
My setup:
* Ubuntu 18.04
* OpenOCD 0.11.0
* Altera USB Blaster (not the II)
* Cyclone V
* 75MHz VexRiscv SoC
=> Increase JTAG UART upload speed

litex/soc/integration/soc.py
=> soc: fix typo in cpu mem_bus axi-via-wb downconvert

litex/soc/cores/cpu/vexriscv_smp/core.py
As mentioned in issue #1875 with too many CSR this region overlap clint region.
This commit provides two way to move csr and clint region:
by overriding default value from the target with:
```
from litex.soc.cores.cpu.vexriscv_smp import VexRiscvSMP
VexRiscvSMP.clint_base = 0xf0100000
```
or by using arguments with
```
./Target.py [options] --clint-base=0xf0100000
```
=> soc/cores/cpu/vexriscv_smp/core: allowing configure CSR/CLINT base address by overriding default value or using args

litex/build/openfpgaloader.py, litex/soc/integration/soc.py, litex/soc/software/bios/cmds/cmd_bios.c, litex/soc/software/liblitespi/spiflash.c
This is a set of several changes to fix various issues identified when debugging why the mmap
spiflash data read with the bios did not match the data written with openfpgaloader.
Example boot with the fixes on a Efinix Ti60 based design:
```
litex> reboot
(c) Copyright 2012-2024 Enjoy-Digital
BIOS built on Feb  1 2024 15:12:36
BIOS CRC passed (0adc116a)
LiteX git sha1: 8678b7af
CPU:            VexRiscv SMP-LINUX @ 200MHz
BUS:            WISHBONE 32-bit @ 4GiB
CSR:            32-bit data
ROM:            128.0KiB
SRAM:           8.0KiB
FLASH:          16.0MiB
MAIN-RAM:       32.0MiB
--========== …
```
=> Spiflash fixes for issues exposed by sys_clk = 200MHz and L2 cache

litex/soc/integration/soc.py
It's a convenient way to get more CSR locations without changing the whole address space layout (i.e. more space for CSR).
It still leaves 256 full 32b registers in each location which I've never encountered a device even coming close to this, so it should be fairly safe to do.
This doesn't change the default, just allow the user to select it.
=> soc/integration: Allow 0x400 CSR paging

litex/soc/integration/soc.py, litex/soc/software/bios/boot.c
As mentionned in #1882 when `add_etherbone` is used in *hybrid* mode etherbone and ethernet must have 2 distinct MACs
This PR contains 3 commits:
1. new constants to overrides ethernet mac address at build time
2. `add_ip_constant` is moved as an helper (to be used by `add_ethernet` and `add_etherbone`) and a new helper is added to define `MACADDRx` constant
3. `add_etherbone` signature is updated to allows user to specify local/remote IP and mac address. 2 assert are used to check if etherbone and ethernet IPs/MACs are different. This commits also add constants for ethernet configuration
=> Etherbone hybrid ip mac

litex/soc/cores/cpu/vexriscv_smp/core.py, litex/tools/litex_sim.py
This PR mostly merge previously made work to add jtagremote support into litex_sim.py
Here is a simple way to test it : 
Terminal 1 : 
```shell
litex_sim --cpu-type=vexriscv_smp --with-sdram --sdram-init boot.json --with-rvc  --with-privileged-debug --hardware-breakpoints 4 --jtag-tap --with-jtagremote
```
Terminal 2 :
```shell
cd openocd
src/openocd  -f ???/jtag_remote.cfg -f ???/riscv_jtag_tunneled.tcl 
```
jtag_remote.cfg and riscv_jtag_tunneled.tcl being [openocd_scripts.zip](https://github.com/enjoy-digital/litex/files/14258979/openocd_scripts.zip).
You should get something like : 
```
Open On-Chip Debugger 0.11.0+dev-04033-g058dfa50d (2023-11-27-14:31)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; …
```
=> tools/litex_sim support for remote_bitbang (openocd) 

litex/build/sim/core/modules/serial2console/serial2console.c
This prevents that characters are lost in case of back pressure on sim UART RX.
=> Send serial data to sim uart only if rx_ready is set.

litex/build/lattice/trellis.py
Hello. I had to add this in order to use the TQFP144 ECP5 package, with the [Vanille](https://github.com/machdyne/vanille) board.
This detects if the device is set to "LFE5U-12F-6TG144", etc. I don't think there is a 144-pin BGA package for ECP5.
=> support TQFP144 ECP5 package

litex/build/generic_programmer.py, litex/build/openocd.py
Hi all,
This PR fixes some issues preventing litex_server being connected to Zynq 7000 series JTAG.
Here is the working log now:
```
(.venv) ➜  rv litex_server --jtag-config /usr/share/openocd/scripts/board/digilent_zedboard.cfg --jtag 
Open On-Chip Debugger 0.12.0
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
zynqpl_program
jtagstream_serve
Info : clock speed 1000 kHz
Info : JTAG tap: zynq_pl.bs tap/device found: 0x23727093 (mfg: 0x049 (Xilinx), part: 0x3727, ver: 0x2)
Info : JTAG tap: zynq.cpu tap/device found: 0x4ba00477 (mfg: 0x23b (ARM Ltd), part: 0xba00, ver: 0x4)
Info : zynq.cpu0: hardware has 6 breakpoints, 4 watchpoints
Info : …
```
=> Zynq7000 litex_server OpenOCD JTAG fixes

litex/soc/cores/ram/lattice_nx.py
The large block ram is pretty slow as is, so avoid the conditional assignment of dataout. 
I'm new to migen so apologies if this isn't correct; but the change does generate the verilog I expected and relieved some timing pressure so I think it should be good.
=> Avoid extra timing delays for NXLRAM path

litex/soc/cores/cpu/neorv32/core.py
This updates the NeoRV32 CPU to the latest (current) version.
This also fixes a constant issue with Whishbone that I have been having where the data is always corrupted.
I have tested this update on my ULX3S using the latest oss-cad-toolchain build.
=> Update NeoRV32 CPU to v1.9.7

litex/build/sim/core/modules/video/sim_fb.c, litex/tools/litex_sim.py
The framebuffer gets filled out in RGB order (https://github.com/enjoy-digital/litex/blob/master/litex/build/sim/core/modules/video/video.c#L156-L159), but the texture format was set to BGR, swapping the colour channels.
I also added a `--with-video-colorbars` option to `litex_sim` to make this easier to test.
Before:
After:
Note that the order is supposed to be (https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/video.py#L341-L348):
White Yellow Cyan Green Purple Red Blue Black
=> sim/video: Change pixel format to RGBA

litex/soc/integration/builder.py, litex/soc/integration/soc_core.py
Allows the target soc to override memory initialization:
rom and/or ram.
Includes documentation for example usage to compile soc target specific software and load it to main_ram. This mechanism
can also be used to load a custom bios into ROM instead of the standard Litex bios.
=> soc/builder: add initialize_memory()

litex/build/efinix/platform.py
get_pin_name did not include the resource index, so additional core instances were generated with identical pin names. See below for examples.
Also only adds slice index for slices with more than one io for cleaner naming.
("i2c", 0,
Subsignal("scl", Pins(...)),
Subsignal("sda", Pins(...)),
),
("i2c", 1,
Subsignal("scl", Pins(...)),
Subsignal("sda", Pins(...)),
),
Before:
output wire          i2c0_oe,
input  wire          i2c0_scl,
input  wire          i2c0_sda,
input  wire          i2c1_scl,
input  wire          i2c1_sda,
input  wire          i2c_scl0_IN,
input  wire          i2c_scl0_IN_1,
input  wire          i2c_scl0_IN_2,
output wire          i2c_scl0_OE,
output wire          i2c_scl0_OE_1,
output wire          i2c_scl0_OE_2,
input  wire          i2c_sda0_IN,
input  wire …
=> build/efinix/platform: fix get_pin_name()

litex/build/sim/core/modules/video/video.c, litex/tools/litex_sim.py
By default the video simulator renders a single scanline at a time, which throttles the speed of the simulation quite a lot in cases where it would otherwise be capable of rendering multiple frames per second. This adds an argument that allows it to render only full frames, improving performance (and reducing tearing). I've left the default behaviour unchanged as I can see that would be useful for more complex designs that take multiple seconds to simulate each frame.
=> sim/video: Add option to render only on frame vsync

litex/tools/litex_json2dts_linux.py
This PR is intended to add support in the litex_json2dts_linux tool for multiple Ethernet interfaces, hopefully it doesn't break anything. I have tested this with [Vivaldi](https://github.com/machdyne/vivaldi) and it appears to work.
=> litex_json2dts_linux: Add support for multiple Ethernet interfaces

litex/soc/software/libbase/uart.c
This follow RX path. Handle interrupt before releasing it, otherwise will stuck at loop if cannot handle interrupts fast enough.
=> Uart tx irq handling fix

litex/build/efinix/dbparser.py, litex/build/efinix/ifacewriter.py
According to the documentation, Trion T8 have a V1 PLL in BGA packages, but a V2 PLL in TQFP package.
The DB files varies accordingly.
Thus, LiteX doesn't properly reference the PLL source.
Example when using pin 75 'GPIOR_157' as clock input:
Currently (doesn't build):
```python
design.gen_pll_ref_clock("pll0", pll_res="PLL_BR0", refclk_src="EXTERNAL", refclk_name="clk25", ext_refclk_no="3")
```
Fixed:
```python
design.gen_pll_ref_clock("pll0", pll_res="PLL_BR0", refclk_src="EXTERNAL", refclk_name="clk25", ext_refclk_no="1")
```
This fix has been validated to work properly on a custom hardware.
=> [fix] T8Q144 PLL input instance reference

litex/tools/litex_term.py
litex/litex/tools/litex_term.py:557: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
self.reader_thread.setDaemon(True)
litex/litex/tools/litex_term.py:586: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
self.writer_thread.setDaemon(True)
=> tools/litex_term: fix DeprecationWarning

litex/soc/integration/export.py
Disable access functions with -DLITEX_ACCESS_FUNCTIONS=0 when compiling. Useful when using litex generated headers in an environment where the access functions generate warnings and are not used.
=> soc/export: add guard for access_functions

litex/soc/software/libbase/isr.c
Hi, 
I would like to execute a program in main_ram using CV32E41P core on Digilent Arty A7 100t and Digilent Genesys 2 boards. However, the program does not boot in both boards and whatever the system frequency. Sometimes, I had an issue coming from the libbase/isr.c code.
So, I include the isr's piece of code made for cv32e40p to be used for 41p too. It works for both boards at 75 MHz (don't test other frequencies yet).
_fyi, as cv32e41p is blocked ([issue](https://github.com/enjoy-digital/litex/issues/1914#issuecomment-2043008534)), I checkout the python-cpu-41p_
=> Support isr for cv32e41p core

litex/soc/cores/cpu/__init__.py
I had to waste another 10-15 minutes building a `riscv64-none-elf` GCC instead after LiteX didn't like my `riscv32-none-elf` one, so I thought I'd quickly add it. (I was using that target triple because it's what Nix's `pkgsCross.riscv32-embedded` package set uses).
I also added 32-bit variants of the rest of the target triples which didn't have them.
=> Add missing 32-bit variants of RISC-V target triples

litex/soc/cores/cpu/cv32e41p/crt0.S, litex/soc/cores/cpu/cv32e41p/csr-defs.h
This pull request corrects the CSR register definition for the CV32E41P core based on the official manual ([link](https://docs.openhwgroup.org/projects/cv32e41p-user-manual/control_status_registers.html#machine-interrupt-enable-register-mie) and [link](https://docs.openhwgroup.org/projects/cv32e41p-user-manual/control_status_registers.html#machine-interrupt-pending-register-mip)).
=> Fix CSR register definition for the CV32E41P core

litex/soc/cores/cpu/cv32e40p/core.py, litex/soc/cores/cpu/cv32e40p/crt0.S, litex/soc/cores/cpu/cv32e40p/csr-defs.h, litex/soc/cores/cpu/cv32e40p/irq.h, litex/soc/cores/cpu/cv32e40p/system.h
This pull request addresses issue #1854 by updating the CV32E40P core to be based on the original OpenHW Group's repository ([link](https://github.com/openhwgroup/cv32e40p)). Another pull request (litex-hub/pythondata-auto#37) has also been created in the pythondata-auto repository to update the core source code. 
This pull request follows the implementation of the CV32E41P and Ibex core. It has been tested on both the simulator and the PYNQ-Z2 FPGA board with the bios and demo example code.
=> Update CV32E40P to be based on the OpenHW Group's repo

litex/soc/cores/cpu/naxriscv/core.py, litex/soc/cores/cpu/naxriscv/crt0.S, litex/soc/cores/cpu/naxriscv/irq.h, litex/soc/cores/cpu/openc906/core.py, litex/soc/cores/cpu/openc906/irq.h, litex/soc/cores/cpu/rocket/core.py, litex/soc/cores/cpu/rocket/irq.h, litex/soc/cores/cpu/vexriscv_smp/core.py, litex/soc/cores/cpu/vexriscv_smp/crt0.S, litex/soc/cores/cpu/vexriscv_smp/irq.h, litex/soc/software/libbase/isr.c
- Add `__risc_plic__` define for CPUs using PLIC.
- Move `PLIC_EXT_IRQ_BASE` definition to CPUs.
- Add baremetal IRQ support to VexRiscv-SMP.
- Add baremetal IRQ support to NaxRiscv.
=> Add baremetal IRQ support to VexRiscv-SMP and NaxRiscv.

litex/soc/cores/cpu/naxriscv/crt0.S
The IRQ routine for NaxRiscv was only supporting 32 bits cpu. Now it is ok for 64 bits aswell.
=> cores/cpu/naxriscv: fix 64 bits IRQ support

litex/soc/cores/cpu/zynqmp/core.py
This serie address a some improvement / new features for zynqMP:
- a new method `set_preset` to fix the *PSU* default with a tcl script (from Vivado bd)
- a rework to the `add_axi_gp_master` method, similar to zynq7000 way. All signals are explicitly connected instead of using a layout
- zynqMP contains peripherals (ethernet, i2c, uart, ...) able to be connected to PS_MMIO pins (dedicated to PSU) or available at PL side (EMIO mode). This PR contains a serie of commit to enable to activate and route ethernet, i2c, and uart to the logic
=> Zynqmp aximaster eth i2c uart

litex/tools/litex_json2dts_zephyr.py
include ctrl, needed to implement rebooting in zephyr.
PR in zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/73199
=> litex_json2dts_zephyr.py: include ctrl

litex/build/efinix/ifacewriter.py
On T20Q144C4, for some reason, `3` is not a valid output load, and in order for the pt tool to complete successfully, all LVDS PHYs need to be at least `5`.  And anyway, this is the sort of thing that does need to be tuned by board in applications in the field!  We add a configuration parameter to specify `TX_OUTPUT_LOAD`.
=> efinix: be able to specify TX_OUTPUT_LOAD on a LVDS PHY on Trion

litex/tools/litex_json2dts_zephyr.py
include cpu, to share the clock-frequency with zephyr through the dts.
Works together with https://github.com/zephyrproject-rtos/zephyr/pull/73327
=> litex_json2dts_zephyr.py: include cpu

litex/soc/software/liblitespi/spiflash.c
Make liblitespi independent from field_access_functions, since they were removed in 46911d5078b81038dceb010b0b786bcb07a7a4d1
=> liblitespi: Fix #1967

litex/soc/cores/cpu/eos_s3/core.py
F4PGA uses new clock names which differ from names used in QORC SDK.
=> Change EOS S3 clock names

litex/tools/litex_json2dts_linux.py
Adds clocks for a downstream iclink soc, for example when builder.add_json() has imported soc clocks.
Node names are as per devicetree fixed-clock.yaml bindings.
This PR implements a feature we need for our dts usage with the changes in https://github.com/enjoy-digital/litex/issues/1960.
=> tools/litex_json2dts_linux: add all soc sys_clk

litex/soc/integration/soc.py, litex/soc/integration/soc_core.py, litex/tools/litex_json2dts_linux.py
This fixes several linux schema validation issues. Closes #1905, see #1960
This branch is on top of the branch for #1972 but that is not a dependency.
=> Dts schema compliance

litex/tools/litex_json2renode.py
- add option for elf bios file
- correct vexriscv variants
for the linux variant I also removed `'privilegeArchitecture: PrivilegeArchitecture.Priv1_10'` as that is already the default value in https://github.com/renode/renode-infrastructure/blob/5904a437c60ea376b679e8de92b71b29a62c8f8a/src/Emulator/Cores/RiscV/VexRiscv.cs#L20
=> litex_json2renode.py: add option for elf bios file and correct vexriscv variants

litex/soc/cores/cpu/zynq7000/core.py, litex/soc/cores/cpu/zynqmp/core.py
By default and unlike others CPUs, for zynq (7000 and MP) based board, CSR and corresponding bus  are added at target level.
Also, for these CPU family, a converter between AXI and wishbone is added: this is no more required: LiteX is now able to convert between native bus type and `bus_standard`.
This PR has for goal to change this behavior: csr base address is now directly added at CPU level and the corresponding bus is added in peripheral_buses: no more to add these hook at board level.
Targets update is done with this [PR](https://github.com/litex-hub/litex-boards/pull/590).
=> soc/cores/cpu/zynqmp/core.py: added csr into mem_map, added M_AXI_HPM0_FPD by default

litex/soc/integration/builder.py
In add_json() the interrupt numbers from a downstream SOC are not relevant to the main SOC so filter them out by default.
=> Add json excludes

litex/soc/integration/export.py
MockCSR in the downstream SOC are not related to csr_base in the main SOC. This fixes the addresses in generated csr files.
=> integration/export: Fix MockCSRRegion base definition.

litex/soc/integration/soc.py
convert spi_clk_freq to an int. this way the constant is also an int.
this is important as that constant is used in the dts converters and there it should not end with a `.0`
=> soc: add_spi_master: make spi_clk_freq an int

litex/build/parser.py
Improvements to LiteXArgumentParser when using set_defaults() in a target to ensure args_fill() for the new cpu_type is called and to report using set_default(arg=default) for an argument that doesn't exist.
=> Parser set defaults improvements

litex/build/sim/core/modules/jtagremote/jtagremote.c, litex/soc/cores/cpu/naxriscv/core.py, litex/soc/cores/cpu/vexiiriscv/core.py, litex/soc/cores/cpu/vexriscv_smp/core.py, litex/tools/litex_sim.py
Hi all,
This series expanded litex_sim JTAG support to any CPU with `add_jtag` hook.
It is tested against naxriscv, cortex_m0, and gs232 in #1990.
Please review.
Thanks
=> Expand litex_sim JTAG support to more CPUs

litex/soc/integration/soc.py
For data_width converter we need to ensure that adapted interface have same properties as it's parent interface, so that id and user signals for AXI will be propagated properly from parent to adapted interface.
=> integration/soc: data_width_convert: Inherit more bus properties

litex/soc/integration/soc.py, litex/soc/interconnect/ahb.py
Don't do bus_addressing_convert as it's being handled in AHB2Wishbone logic.
Add addressing parameters for AHBInterface constructor as required by soc code.
This is split from #1990, I would like to get those independent features merged first.
=> soc/integration/soc.py: Fix creation of AHB2Wishbone bridge

litex/soc/software/liblitespi/spiflash.c
This fixes the following:
when `CSR_SPIFLASH_CORE_MASTER_PHYCONFIG_MASK_SIZE = 8`
`tmp = mask & ((2 ^ CSR_SPIFLASH_CORE_MASTER_PHYCONFIG_MASK_SIZE) - 1);`
using GCC 13 and 14 (Im not sure of the compiler version relationship to the bug here) gave `tmp` the result of 9.
This is because 2 ^(xor) 8 is 10.
This patch makes the shift explicit to fix the bug and avoid confusion.
=> liblitespi: fix xor-used-as-pow bug

litex/soc/interconnect/axi/axi_lite.py, litex/soc/interconnect/axi/axi_lite_to_csr.py, litex/soc/interconnect/csr_bus.py, litex/soc/interconnect/wishbone.py, test/test_csr.py
Currently CSR bus assumed that ~we means reading, that created a problem that when for a CSR if reading has side effects and adr parked unintentionally at that CSR, the reading side effect will be triggered.
For SoCs, this happened when upstream bus issued a write transaction with wishbone.sel, then on CSR bus it will be translated as adr = addr, we = 0, which will be interpreted as a read to such address, and trigger undesired side effect for such CSR.
Such upstream transaction will be generated by our bus width converter.
Given that we signal already presents in CSR Interface, the easiest way to handle such situation is to generate re signal at bus bridges and propagate it all the way down to the Interface.
=> csr_bus: Honour re signal from the upstream bus

litex/tools/litex_json2dts_zephyr.py
Remove all configs, that are enabled by default
in zephyr based on the devicetree.
In zephyr drivers are automatically enabled based on status of device in the devicetree.
=> litex_json2dts_zephyr.py: Remove unnessesary configs

litex/build/efinix/efinity.py, litex/build/efinix/platform.py
As mentioned in #1971, synthesis options like `--mode` may be adapted/configured at build time instead of hardcoded.
Solution proposed in #1971 imply to modify target and/or platform to set these options.
This PR address this issue by adding arguments to configure `efx_map` at build time.
*Note*: add `efx_map` aren't updated to use argument approach and it may make sense to have the same thing, at least, `efx_pgm`.
=> build/efinix: added argument to change synthesis options configurations

litex/soc/cores/i2c.py, test/test_i2c.py
This PR imports the I2CMaster from misoc and adapts it to Litex.
It also includes the history of the various fixes that were required to make it actually work for READ: it appeared from our testing that while read was implemented it had never been used...
This core has limitations but it works and is far better than bitbang.
=> Add i2c master

litex/soc/cores/video.py
This PR adds rgb332, mono8 and mono1 color formats.
This may be useful for improving video performance when more color depth isn't required.
Related to litex-hub/linux-on-litex-vexriscv#396
=> soc/cores/video: Add additional color formats

litex/build/altera/common.py, litex/build/altera/platform.py
For *Agilex5* **ALTDDIO_OUT** and **ALTDDIO_IN** are not supported, and replaced by **tennm_ph2_ddio_out** and **tennm_ph2_ddio_in** (according to plaform designer generated code).
This PR is not fully tested due to errors at build time:
```
Error (23098): One or more blocks are configured incorrectly and will not have the desired functionality. --BCM instance name: hvio_0_1                                                                                                                                                                                        
Error (12274): A critical error occurred while the periphery placement was committed to the atom netlist. The atom netlist is now invalid and the Fitter must be restarted. …
```
=> build/altera/common,platform: added ddrinput/ddrout primitives

litex/build/altera/common.py
`SDRTristate` is required to have SDCard in SDIO Mode working.
=> build/altera/common.py: implement SDRTristate for Agilex5 family

litex/build/gowin/common.py, litex/build/gowin/platform.py
This PR adds some GW5A primitives for SDRInput/SDROutput and SDRTristate.
Input/Output are simple `DFFSE` (no clocked in / out for arora) and may (or not) be inferred for sync blocks but without these SDRAM are not working.
Tested with @sipeed Tang Primer 25k and Tang Mega 138k pro
=> build/gowin/common.py: re-add tristate impl and SDRxxx for GW5A/Arora family (required for SDRAM use)

litex/build/gowin/__init__.py
This fixes the empty `__init__.py` in `litex.build.gowin`: https://github.com/enjoy-digital/litex/blob/6309f30e0b3ff807249a6003730d3920bc88d0c0/litex/build/gowin/__init__.py / https://github.com/enjoy-digital/litex/blob/master/litex/build/gowin/__init__.py
=> Fix litex.build.gowin's __init__.py; closes #2034

litex/build/gowin/apicula.py, litex/build/gowin/gowin.py, litex/build/gowin/platform.py, litex/build/nextpnr_wrapper.py
This PR:
- Adds GowinApiculaToolchain by using yosys + nextpnr
- Moves constraints generation from GowinToolchain.build_io_constraints to _build_cst to be reuseable
- Modifies NextPNRWrapper.get_call so command only contains flag for constraint fmt if it is non-empty. This is necessary as the `nextpnr-himbaechel` needs to be used, where the constaints file needs to be specified via `--vopt cst=file`, so the intended way of NextPNRWrapper for constraint-passing does not work anymore.
=> Adds apicula toolchain to gowin platform

litex/build/gowin/apicula.py
In the Gowin platforms these options are set to use dual-use pins.
In Apicula these are passed as command line arguments.
Counterpart to https://github.com/litex-hub/litex-boards/pull/603
=> Gowin: add dual use gpio options

litex/tools/litex_json2dts_zephyr.py
omit disable handler for the sdcard peripherals,
as they still don't have a driver in zephyr and are not in the board dts.
This way the build in zephyr will not fail.
Currently you had to manually remove the parts for the sdcard in the overlay, because the build in zephyr fails if there are overlays for unknown peripherals.
=> json2dts_zephyr: omit disable handler

litex/soc/cores/hyperbus.py, litex/soc/software/bios/main.c, litex/soc/software/libbase/Makefile, litex/soc/software/libbase/hyperram.c, litex/soc/software/libbase/hyperram.h, test/test_hyperbus.py
- Make Rst/Clk/CS synchronous.
- Prepare for use of SDRTristate.
- Avoid waiting for clk_phase in IDLE state.
- Move HyperRAM init to libbase/hyperram.c.
=> Improve HyperRAM core to allow IO Reg inference.

litex/soc/cores/hyperbus.py, litex/soc/software/libbase/hyperram.c, test/test_hyperbus.py
Allow running the HyperRAM 2X faster (so reducing latency/increasing throughput). Requires a sys2x generated in CRG.
=> HyperRAM: Add 2:1 ratio support in addition of 4:1 ratio.

litex/build/gowin/apicula.py, litex/soc/cores/clock/gowin_gw1n.py
This maps Gowin IDE device families to Apicula database names, and updates the PLL generator to use the "revised PLL" primitive, which is basically the same as the PLL primitive but I guess they made some breaking changes to the implementation.
Stand by while I test more Gowin boards on Apicula in https://github.com/litex-hub/litex-boards/pull/603/files
=> fixes for apicula support

litex/build/colognechip/colognechip.py, litex/soc/cores/clock/colognechip.py
This PR fix and simplify colognechip's FPGA support:
The PLL's `locked` signal must be connected to `USR_PLL_LOCKED` instead of `USR_PLL_LOCKED_STDY`. `xx_STDY` signals are for debug purpose: `USR_PLL_LOCKED_STDY` is set to high at boot time when PLL is locked, goes low if lock is lost and remains low until `USER_LOCKED_STDY_RST` is asserted. An intermediate signal is added to have `locked` signal driven by both PLL and input reset: PLL has no input reset signal.
With latest toolchain release `Pin_in`, `Pin_out` and `Pin_inout` become obsolete and replaced by `Net`: `p_r` is now able to detect direction thanks to verilog top module: *build/colognechip/colognechip.py* is simplified to use this new behavior.
=> Colognechip improve

litex/build/efinix/ifacewriter.py, litex/soc/cores/clock/efinix.py
Efinity tool was complaining of bad pin voltage for the PLL clock input.
The issue was only comming up when the pll input clock was using a different bank voltage than the default.
In practice this PR will add pin definition to the generated iface.py : 
```
design.gen_pll_ref_clock("pll0", pll_res="PLL_BL0", refclk_src="EXTERNAL", refclk_name="clk100", ext_refclk_no="1")
design.set_property("clk100","IO_STANDARD","3.3_V_LVCMOS")
```
=> efinix: Fix PLL with external clock input ifacewriter

litex/build/gowin/apicula.py
This PR as for goal to deal with options only required by:
- Gowin's toolchain for sanity check
- Apicula/Yosys toolchain to deal with FPGA's models specificities.
As mentioned in this [PR](https://github.com/litex-hub/litex-boards/pull/603) it's more easy to deal with this aspect at the LiteX build level to avoid adding complecities at platform/target level. Thanks to that users contributing boards doesn't have to worry about options only required for one toolchain and others required by other toolchain.
=> Gowin apicula fix

litex/soc/cores/usb_ohci.py
Fix USB OHCI SDRTristate using the wrong clock.
Wasn't always noticable, but when it does, this were going quite bad ^^
=> core/usb_ohci: fix SDRTristate clock

litex/soc/software/bios/main.c, litex/soc/software/liblitespi/Makefile, litex/soc/software/liblitespi/spiram.c, litex/soc/software/liblitespi/spiram.h
add spiram in bios, so it can enable QPI for the spiram.
Its partially copied from `spiflash.c`, with things removed that are not needed.
For the freq_int it uses the memtest_data() function instead of the crc, as we can also write over mmap.
=> bios: add spiram

litex/soc/cores/cpu/vexiiriscv/core.py
The clock rework allows the CPU to work with a different clock than litex (higher fmax)
the video support add a memory coherent video output (will need to add more parametrization later, currently it is ycbcr 4:2:2 800x600@60hz
=> soc/cores/vexiiriscv: update clocks + add video framebuffer support

litex/build/efinix/common.py, litex/build/efinix/efinity.py, litex/build/efinix/ifacewriter.py, litex/build/efinix/platform.py, litex/soc/cores/clock/efinix.py
add a few IO primitives, IO constraints, but mainly it rework how the SDC are handled.
The main issue with how the efinix flow was handled, is that the constraints for the syncronous IO were missing. This break stuff for high frequency design in large FPGA (Ti375)
The efinity tool generate a template outflow/xxx.pt.sdc. With this patch, this xxx.pt.sdc is combined with the one generated from litex.
!!! WARNING !!! 
There is one dirty thing is this PR.
This is the changes in efinix.py. when you setup a clock domain with a pll, this replace the clock domain "clk" with the new one created by the PLL.
This is done to ensure the constraints match with the efinix pll toplevel IO.
An alternative would be to provide a way to specify that a given litex clock domain should use the given name in the …
=> build/efinix: add a few IO primitives, IO constraints, sdc rework

litex/soc/integration/soc.py
add mac addr constant to add_ethernet,
so it matches the one from add_etherbone.
=> soc.py: add_ethernet: add mac addr constant

litex/tools/litex_sim.py
This fixes the behavior of `ethernet_phy_model` `"sim"`. As the preamble is automatically attached by the tap, there is no need to add it from the BIOS. To let the BIOS know, `HW_PREAMBLE_CRC` needs to be set.
Fixes #2067
=> sim: add HW_PREAMBLE_CRC for ethernet

litex/tools/litex_json2dts_zephyr.py
This PR improves the support for indentation so those functions can be reused to generate a nicer Linux DTS. See #1960.
It also changes the formatting of the reg in dts_reg() to be dts schema compliant but I haven't tested if the old format is mandated by zephyr. Can someone please confirm, maybe @maass-hamburg or @trabucayre?
=> DTS zephyr updates

litex/build/efinix/common.py, litex/build/efinix/ifacewriter.py
`ClkInput` specials is currently only uses as PLL's clkin. The current approach is to uses a string for `create_clkin`. This way is valid because both `ClkInput`'s o name and PLL's `clkin` must match at *iface* level and nothing is known in a generated verilog file. But when this specials is used for a `ClockDomain` this way is no more valid and it's requires to connect `.o` to the `ClockSignal`.
The first commit address this limitation by allowing the use of a `ClockSignal`, converted to a signal when the class contructor is called. In this situation, the constructor adopt the same approach done for PLL's `create_clkout` method. string is kept as backward compatibility to avoid breaking all existing code.
Second commit address another issue: when a gpio out (ddio f.i.) is used through …
=> build/efinix/common.py: ClkInput: added ClockSignal support

litex/build/efinix/common.py, litex/build/efinix/efinity.py
Allow the Migen/LiteX build elaboration to resolve signal names and just use it in blocks to avoid name_override workaround.
=> Efinix iface signal names.

litex/build/efinix/common.py
=> build: efinix: common.py; add `SDRInput`

litex/build/efinix/common.py, litex/build/efinix/ifacewriter.py
a few fixes for the efinix interfacewriter
=> build: efinix: ifacewriter: some fixes

litex/build/efinix/common.py, litex/build/efinix/platform.py
use the gpio bus for Efinix Tristate implemenation.
=> build: efinix: EfinixTristateImpl: use GPIO Bus

litex/build/io.py
don't use mutable object (here: ClockSignal()) as default value, because they will be the same object.
Leeds to problems, when for example two `SDRInput` are used in two different Modules and one of them is used with a `ClockDomainsRenamer()`, then both are changed.
more infos: https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil
=> build: io: don't use mutable object as default value

litex/build/efinix/efinity.py, litex/build/efinix/ifacewriter.py
use efinix python api to set bank voltage,
instead of editing the peri.xml file.
=> build: efinix: use ifacewriter to set bank voltage

litex_setup.py
This PR adds support for installing RISC-V GCC in Alpine Linux environments, which is useful for creating Docker development containers based on Alpine images.
**WARNING**: To test the fix, you must run the command **litex_setup.py** with the _--dev_ option to prevent the script from auto-updating (the checksum is validated against the main branch of the original repository):
`./litex_setup.py --gcc=riscv --dev`
=> Fixes #2092: provides support for riscv gcc installation on Alpine Linux.

litex/soc/cores/cpu/zynqmp/core.py
GEM controler may be used via PL (FPGA) and connected to RGMII, GMII or SGMII.
This PR adds required code + module needed for SGMII.
=> soc/cores/cpu/zynqmp/core.py: added support for SGMII via PL with optional PTP support

CHANGES.md, litex/soc/cores/cpu/urv/__init__.py, litex/soc/cores/cpu/urv/boot-helper.S, litex/soc/cores/cpu/urv/core.py, litex/soc/cores/cpu/urv/crt0.S, litex/soc/cores/cpu/urv/irq.h, litex/soc/cores/cpu/urv/system.h, litex/soc/integration/builder.py
uRV is used in White Rabbit project and being able to do some tests with it directly in LiteX could be useful to do some verifications or try to replace it with another CPU in White Rabbit Core (in the aim to reduce resource usage, especially BRAM usage for ROM by moving code execution to SPIFlash (XIP) or HyperRAM).
=> Add initial uRV CPU support.

litex/soc/cores/cpu/vexiiriscv/core.py
- have opensbi things behind a condition
=> vexiiriscv: add options and conditions

litex/soc/cores/led.py, test/test_led.py
This fixes #2103 .
When `Memory` depth is 1, a register should be used. In this fix, use memory of depth 2 to simplify this situation.
See-also: https://github.com/m-labs/migen/pull/295
=> Fixes #2103: calculate  memory depth for WS2812

litex/soc/cores/cpu/vexiiriscv/core.py
This PR bring improve the VexiiRiscv core with : 
- Better timings
- all RV32/64  x   RVF RVD legal combination supported
- VexiiRiscv SoC now support the ethernet rgmii with DMA accesses. 
The ethernet RGMII driver can be found here : 
- https://github.com/Dolu1990/litex-linux/tree/spinal-sgmac/drivers/net/ethernet/spinal
- Getting around 766 Mbits/s RX and 621 Mbits/s TX in linux with iperf3
=> Vexiiriscv update

litex/build/lattice/diamond.py, litex/build/lattice/platform.py
With the current diamond support all timings constraints are written into .lpf
This mean it's no possible to assign constraints to internal OSC or PLL outputs.
As a Workaround this PR allows users to provides one or more sdc files to integrate to the project.
Future work is to integrate sdc generation as done for radiant.
=> litex/build/lattice/diamond, platform: allows users to add custom sdc files

litex/build/sim/core/veril.cpp
During my testing of LiteX simulations using Verilator, I discovered that when the BIOS executes the `finish` command to properly terminate the simulation, the FST files were not being closed correctly. This resulted in `sim.fst` and `sim.fst.hier` not being merged properly.
- Fixed the logic to ensure FST files are correctly closed when the `finish` command is executed.
- Verified that after executing the `finish` command, the FST files close correctly and the waveform files merge as expected.
Thank you to the authors for designing such an excellent project with LiteX! I hope this fix can be accepted upstream.
=> Fixes: Fix not close trace file when the sim is finished

litex/build/vhd2v_converter.py
`VHD2VConverter` is used to convert one or more VHDL file to one verilog file. It is more or less similar to `Instance` with a dict of parameters, input, ouput,  inout signals and the list of files.
Based on **p_xx** a ghdl command is build and the result is one file verilog file without parameters, and with all signals with a fixed size based on generic.
In most of the case this behavior is fine, at least for generic IPs where no hardware primitives or vendor's blackbox are used.
When primitives are present, *ghdl* fails to convert sources because it don't know entity structures. To fix this use case vendor's libraries must be compiled as `.o` before conversion step.
This PR fix this issue by adding a list of libraries (the file path or a tuple(work, file path), and a first step before …
=> build/vhd2v_converter.py: allows users to pass a list of libraries files to compile before convert HDL.

litex/soc/cores/clock/xilinx_usp.py
Split PR #2111 into 3 parts as requested in[ #2111#issuecomment-2454519454](https://github.com/enjoy-digital/litex/pull/2111#issuecomment-2454519454)
Part 1/3: Update USPMMCM to use MMCME4_ADV for finer clock output control
- Enables 0.125 step size for clock division/multiplication
- Main change: replace MMCME2_ADV with MMCME4_ADV
=> Use MMCME4_ADV in USPMMCM to enable finer-grained clock output ctrl

litex/build/openfpgaloader.py
Split PR https://github.com/enjoy-digital/litex/pull/2111 into 3 parts as requested in https://github.com/enjoy-digital/litex/pull/2111#issuecomment-2454519454
Part 2/3: Add FTDI serial number option to openfpgaloader, useful when multiple similar boards are connected for CI/CD
=> Add FTDI serial number option to openfpgaloader

litex/soc/software/liblitespi/spiflash.c, litex/soc/software/liblitespi/spiram.c
clear rx queue at the end of spiflash_master_write().
=> bios: litespi: clear rx queue after write Beta

litex/soc/cores/uart.py, litex/soc/integration/soc.py, litex/soc/integration/soc_core.py
In our application, we would like our default UART to have a configurable baud rate based on other system parameters.  Sample code to drive this:
```c
static uint32_t current_uart_baudrate = 921600;
static struct tuning {
uint32_t baudrate;
uint32_t tuning;
} predefined_tunings[] = {
{ 1500000, 85899346 },
{ 921600, 52776558 },
{ 115200, 6597070 }
};
static void update_uart_baudrate(uint32_t desired_baudrate) {
uint32_t new_tuning = 0;
for (int i = 0; i < sizeof(predefined_tunings) / sizeof(predefined_tunings[0]); i++) {
if (predefined_tunings[i].baudrate == desired_baudrate) {
new_tuning = predefined_tunings[i].tuning;
}
}
if (new_tuning == 0) {
uint64_t new_baudrate = (uint64_t)desired_baudrate << 32;
new_tuning = new_baudrate / 75000000l;
}
if (new_tuning) { …
```
=> feat: add uart_with_dynamic_baudrate to SoCCore

litex/build/efinix/common.py, litex/build/efinix/ifacewriter.py, litex/build/io.py
use constant output option, when the output is a `Constant`
=> efinix: gpio: use constant output option

litex/build/lattice/common.py
Unlike nextpnr/Trellis specials implementation, ECP5 has no dedicated implementation for Tristate Special.
This PR adds this special by using `BB` primitive.
=> build/lattice/common.py: added Tristate support for ECP5 when build with diamond

litex/build/efinix/efinity.py
With Efinity 2024.2, the path of the vdb file has changed from `work_syn` to `outflow`. To fix this, first check if the file exists in `work_syn`. If it doesn't `outflow` is used.
(Fixes half of #2126)
=> Fix vdb path for Efinity 2024.2

litex/soc/software/liblitespi/spiram.c
Currently spiram cannot be built due to typo in liblitespi. This PR fixes building spiram.
=> liblitespi: fix typo

litex/soc/software/liblitespi/spiflash.c, litex/soc/software/liblitespi/spiflash.h
Currently, only range erase is supported. In some cases, it might be necessary, to erase blocks with a finer granularity than 64k. With this function, erasing individual 4k blocks is possible.
=> liblitespi: add 4k erase function

litex/soc/cores/cpu/vexiiriscv/core.py
The RISC-V PMP feature can now be enabled via --vexii-args="--pmp-size=8" for instance.
TOR support can be disabled via --pmp-tor-disable to save area / timings
=> cores/cpu/vexiiriscv: Add PMP support

litex/build/xilinx/platform.py
specials_overrides are present and used by most of the Ultrascale devices but not for ZynqMP Ultrascale.
this PR adds required lines to enable this support.
=> build/xilinx/platform: added xilinx_us_special_overrides for xczu devices

litex/soc/integration/soc.py, litex/soc/interconnect/axi/axi_lite_to_csr.py, litex/soc/interconnect/wishbone.py, test/test_axi_lite.py
Wishbone2CSR and AXILite2CSR bridges are incapable for performing bus width conversion, which means it's Bus slave port must have same width as CSRs.
Use CSR width to create slave bus to allow width adaptar to be inserted by add_slave. Also add relevant assertion.
This fixes `--bus-data-width 64` build.
=> soc/integration/soc: Fix CSRBridge Bus Width conversion

litex/soc/cores/clock/intel_common.py
`self.reset` is not connected in `IntelClocking` PLLs.
I think it was simply missed, or is there some reason for it? 
It makes declared reset input in some current Intel board definitions not effective (like [here](https://github.com/litex-hub/litex-boards/blob/a3b38163e82c14348fdfbd2adbc0a26b96c70952/litex_boards/targets/sitlinv_a_e115fb.py#L36)) and `soc_rst` that works via CRG ignored.
=> cores/clock/intel: add reset to Intel PLLs

litex/build/vhd2v_converter.py
Current approach with VHD2VConverter is to pass a dict with parameters, input/output signals and the top_entity name.
For a existing code using Instance this imply to rework code to replace `instance` by `dict`.
This PR allows VHD2VConverter to receive by CTOR an instance. In this mode it will be able to extract entity name and parameters from Instance and create a new one with only port
This PR also do build_dir optional: When not provided at constructor time build_dir will be filled with build/platform_name/vhd2v
=> build/vhd2v_converter: allows using an instance instead of entity_name + params

test/test_integration.py
This is a follow up of #2143 which added relevant tests to our CI, spin off from #2144.
Note, some bus option combinations are still failing, I blacklisted them for now.
```
blacklists = [
[
("--bus-standard", ["axi-lite"]),
("--bus-data-width", [64]),
("--bus-interconnect", ["crossbar"])
],
[
("--bus-standard", ["axi"]),
("--bus-data-width", [64])
]
]
```
=> test: Include more bus option tests

litex/soc/cores/clock/xilinx_usp.py, litex/tools/litex_json2dts_linux.py
https://github.com/enjoy-digital/litex/pull/2117 broke my linux-on-litex-vexriscv build as the f4pga conda environment still uses python3.7 and the new (python3.8) [assignment expression](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions)  got used in `if specific_div_range := getattr(self, f"clkout{n}_divide_range", None):`.
For the sake of backwards compatibility, and not unnecessarily breaking the build for other people, this PR gets rid of the assignment expression.
Edit: Same issue with building versa_ecp5 in linux-on-litex-vexriscv as the nextpnr-ecp5 install (`conda install litex-hub::yosys litex-hub::nextpnr-ecp5`) requires python>=3.7,<3.8 but some script is using the python3.9's str removesuffix method.
=> backwards compatibility with python3.7

litex/build/gowin/programmer.py
- Use devname info for automatic operation mode selection
- Allow customizing operation mode for advanced usage
- Supports exflash, verified on Sipeed Tang Primer 25K, Primer 20K, and [LCKFB LJPI](https://lckfb.com/project/detail/lckfb-ljpi-fpga-g1)
- For Sipped Nano 9K and 4K, it seems that the BL702 chip is not stable.
- Use GAO Bridge operations for exflash
- Accepts cable type in `__init__`, more flexible cable type handling
- Backward compatibility is maintained(actually all current usage of GowinProgrammer is marked as "FIXME" or broken)
=> build/gowin/programmer: refactor GowinProgrammer for enhanced functionality

litex/build/lattice/common.py
Everything is in the title.
Validated on ice40up5k pin 32
=> [enh] Added differential input for ICE40

litex/build/altera/quartus.py
There is an reported issue with Quartus toolchain, that fails to infer memories with multiple write enable signals.
It is a problem for liteeth module with large buffers (https://github.com/enjoy-digital/liteeth/issues/63) which was fixed and later changed  to configurable `full_memory_we`  option in https://github.com/enjoy-digital/liteeth/pull/72, because of regression on other FPGAs.
However, this option/problem is not documented and not used in existing codebase, and leads to unexpected, difficult to trace problems with high device utilization.
Because of that, I think it would be a good idea to enable this option by default if Quartus toolchain is detected.
The second place where `full_memory_we` option is defined is L2 Cache, where it is enabled by default for all targets.
=> soc/ethernet: enable full_memory_we by default for Quartus toolchain

litex/build/altera/common.py, litex/build/colognechip/common.py, litex/build/efinix/common.py, litex/build/gowin/common.py, litex/build/io.py, litex/build/lattice/common.py, litex/build/sim/common.py, litex/build/xilinx/common.py
add bus variants of SDR and DDR, which
support more than one pin.
=> build: io: add multibit/bus variants of SDR and DDR

litex/soc/cores/cpu/openc906/core.py, litex_setup.py
Use RTL from pythondata-openc906, remove unused file lists, remove outdated bus conversion logic, remove "riscv-dm" and "ethmac" from mem_map as they can be allocated automatically, use DTM to implement add_jtag.
Get the core working.
=> cores/cpu/openc906: Align with pythondata RTL

litex/soc/cores/cpu/ibex/core.py, litex/soc/cores/cpu/ibex/crt0.S, litex/soc/cores/cpu/ibex/system.h, litex_setup.py
Fix up file path and workaround verilator limitation on parameter type.
Also fix crt0 and system.h to reflect RTL changes.
=> cores/cpu/ibex: Align with latest RTL

litex/gen/fhdl/expression.py, litex/gen/fhdl/verilog.py
resolve slice completly, to reduce complexity
in the verilog files.
=> gen: fhdl: expression: resolve slice completly

litex/build/altera/quartus.py
With `FullMemoryWE()(fragment)` call the build fails with:
```script
Error (14703): Invalid internal configuration mode for design with memory initialization
```
This failure may be related to the use of  *dual_boot* IP core or because project is configured with `INTERNAL_FLASH_UPDATE_MODE "DUAL IMAGES"`. But In as first time simpliest way is to disable this call for max10 targets
=> build/altera/quartus.py: don't call FullMemoryWE when target is based on max10 FPGA

litex/build/altera/common.py, litex/build/lattice/common.py, litex/build/xilinx/common.py
make sure the the lenght of the o2 Signal is
the same lenght of o1, when a DDRImput implementation is used
for a SDRInput. This is needed for multibit io.
This was forgotten in https://github.com/enjoy-digital/litex/pull/2105
=> build: common: make sure Signal lenght is right

litex/gen/fhdl/verilog.py
bring back lower_complex_slices() as it is sometimes needed.
for example, when a Slice of a Cat() is done.
migen: https://github.com/m-labs/migen/pull/301
=> litex: gen: fhdl: verilog.py: resolve slice in lower_complex_slices()

litex/build/efinix/common.py, litex/build/gowin/common.py, litex/build/lattice/common.py
support setting a different oe for every line in
the Tristates.
this is also needed for the multibit io, where oe has the same lenght
as the io., because some platforms use the generic implementation
of the SDR/DDRTristate, that uses a Tristate internally.
=> build: common: TristateImpl: support longer oe

litex/soc/integration/soc.py, litex_setup.py
add a i2c master similar to LiteSPI.
This has the big benefit by using crossbar, that the i2c bus can be used at the same time by drivers, that are in logic, and from the CPU.
The driver for zephyr can be found here: https://github.com/zephyrproject-rtos/zephyr/pull/76554
=> core: i2c: add i2c master

litex/soc/cores/clock/gowin_gw5a.py
As for *GW5A-*, *GW5AT* uses PLLA. Without this fix synthesis fails because no PLL is found.
=> soc/cores/clock/gowin_gw5a.py: GW5AT uses PLLA

litex_setup.py
Updates to the following migen commit, which incudes support for the bytecodes in python 3.13 https://github.com/m-labs/migen/commit/4c2ae8dfeea37f235b52acb8166f12acaaae4f7c
The [changes to the current commit](https://github.com/m-labs/migen/compare/ccaee68e14d3636e1d8fb2e0864dd89b1b1f7384..4c2ae8dfeea37f235b52acb8166f12acaaae4f7c) don't look to egregious and in my (admittedly limited) testing no issues occured.
Fixes https://github.com/enjoy-digital/litex/issues/2152
=> Update migen version to work with python3.13

litex/build/lattice/programmer.py
While trying to program the ULX3S 85F variant board I got an error when trying to use `ujprog`.
I came across[ this issue](https://github.com/emard/ulx3s-bin/issues/7) where it says that using `ujprog` is outdated and that `fujprog` should be used instead. So I added the fujprog command in the lattice `programmer.py` file. 
Now the ULX3S board programs nicely with the `--load` command.
=> Added fujprog in Lattice progammer for ULX3S

litex/soc/software/libbase/memtest.c
The random memspeed test uses modulo to bounds-check reads. The modulo operator is [rather heavy](https://mastodon.social/@cr1901/114015524022352658) on cores without division, and the time spent calculating it can dwarf the amount of time actually reading from memory.
By default, the memtests seem to use power-of-two sizes. If BIOS LTO is enabled (which is _not_ default), then the compiler should optimize modulo to an AND mask. However, since memtest is by default part of a static lib without LTO, the compiler can't do this optimization. This patch adds a dynamic check for power-of-two size and manually does the optimization if it applies.
After this patch, I've seen LiteX go from reporting a 4KiB/s random access read on QSPI flash to ~150KiB/s!
=> Optimize memspeed test for cores with slow modulo.

litex/soc/cores/cpu/cv32e40p/core.py, litex/soc/cores/cpu/cv32e41p/core.py, litex/soc/cores/cpu/cva6/core.py, litex/soc/cores/cpu/openc906/core.py, litex/soc/integration/export.py
Otherwise, there will warnings like:
```
./litex/soc/cores/cpu/cv32e40p/core.py:68: SyntaxWarning: invalid escape sequence '\$'
res = re.search('\$\{DESIGN_RTL_DIR\}/(.+)', l)
```
=> Use Python's raw string in regex pattern.

litex/soc/cores/cpu/sentinel/__init__.py, litex/soc/cores/cpu/sentinel/boot-helper.S, litex/soc/cores/cpu/sentinel/core.py, litex/soc/cores/cpu/sentinel/crt0.S, litex/soc/cores/cpu/sentinel/csr-defs.h, litex/soc/cores/cpu/sentinel/irq.h, litex/soc/cores/cpu/sentinel/sentinel-pep-723.py, litex/soc/cores/cpu/sentinel/system.h, litex_setup.py
Self-expanatory. [Sentinel](https://github.com/cr1901/sentinel) is my RISC-V CPU in a sea of RISC-V CPUs :D.
I assume before merging, this requires https://github.com/litex-hub/pythondata-auto/pull/40 to be merged, and making a `pythondata-cpu-sentinel` repository that LiteX can reference. Naturally, CI won't pass until then either :).
Sentinel is written in Amaranth and requires Python 3.11 and up. Because LiteX users aren't guaranteed to have Python 3.11 installed, I delegate Verilog code generation to a [PEP-723](https://peps.python.org/pep-0723/)-compatible script. Consequently, users will need to install a PEP-723-compatible tool like [pipx](https://github.com/pypa/pipx) or [pdm](https://github.com/pdm-project/pdm). Either of these tools will install Python 3.11 and Sentinel's …
=> Add support for the Sentinel RISC-V CPU.

litex/gen/fhdl/hierarchy.py
On Windows, this fixes a good ol' `UnicodeEncodeError: 'charmap' codec can't encode characters in position... character maps to <undefined>` error.
Btw, do you still check IRC/Matrix :P? Don't worry, I think I have tentatively one more PR to make and that's it for a while.
=> Use CP1252-compatible chars for hierarchy on Windows.

litex/build/efinix/dbparser.py
Since Efinity 2024.2.294, the `/pt/db/device_*.xml` files are no longer shipped with the IDE. While it was possible to copy the files over from an older version, this likely will limit support for newer FPGAs.
With this change, those files are not required anymore.
This fixes the other (remaining) half of #2126
=> Fix Efinity 2024.2 missing device_*.xml files

litex/soc/software/bios/boot.c, litex/soc/software/libliteeth/tftp.c
- add option to skip trying to boot from boot.json
- add error message if ARP failed
=> bios: add option to skip json netboot

litex/soc/cores/cpu/vexiiriscv/core.py
This update VexiiRiscv, fixing the very long reset hold happening on boot.
=> cores/cpu/vexiiriscv : Fix #2202 long boot time

litex/soc/cores/cpu/naxriscv/core.py
Hello,
I found in the now resolved #2200 that the mapping of some JTAG instruction ports in [litex/litex/soc/cores/cpu/naxriscv/core.py](http://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/cpu/naxriscv/core.py#L428) are not matching the name of the actual NaxRiscv's JTAG instruction ports.
Following the discussion in #2200, here is how it could be adressed.
Best regards,
=> PR following enjoy-digital#2200 closure

litex/soc/software/libliteeth/tftp.c
This change fixes an issue in the TFTP client where the OACK (Option Acknowledgment) from the server was not fully handled during a file upload (tftp_put). When the server sends an OACK in response to a WRQ with options (like a non-standard block size), the client only sent an ACK(0) without updating its state (e.g., last_ack and data_port). This prevented the client from proceeding with sending data blocks, resulting in a 0-byte file on the server. The fix ensures that upon receiving an OACK, the client sets last_ack to 0 and captures the server's data port, allowing the data transfer to continue as expected.
=> Fix TFTP PUT: Properly Handle OACK for Option Negotiation

litex/soc/cores/cpu/cva5/boot-helper.S, litex/soc/cores/cpu/cva5/core.py, litex/soc/cores/cpu/cva5/crt0.S, litex/soc/cores/cpu/cva5/irq.h, litex/soc/software/libbase/isr.c, litex_setup.py
This pull request introduces key changes to enable Linux support on the CVA5 core, including the addition of PLIC and CLINT, which required modifications to isr.c. It also resolves the original interrupt issue and includes initial changes necessary for running an operating system on multicore CVA5.
Key Updates:
- Full support for the 20240411 RISC-V privileged architecture (previously, only a draft spec from ~2017-2019 was supported).
- New separate TLBs for instructions and data.
- Sv32 virtual memory support.
- Significant bug fixes for interrupt and exception handling. This resolves issue #19 (Interrupts can lead to MEPC inconsistent with register state).
- RISC-V atomic extension (AMO) support, resolving issue #21 (State of AMO support).
- Simulation support for the latest Verilator …
=> Add Linux support for CVA5, including PLIC and CLINT and major bug fixes

litex/soc/software/libc/Makefile
While trying to make a reproducible LiteX build using Nix I found that `libc` `Makefile` copies CPU family files to `$PICOLIBC_DIRECTORY/newlib/libc/machine/$(CPUFAMILY)/`. This directory is a package directory and should not be altered during build (what was the cause of build failure due to insufficient permissions in my case).
This PR suggests a walk around that copies all contents of `$PICOLIBC_DIRECTORY` to `picolibc_src` in current build directory and copies `libc` CPU family files there.
=> Fixed for eliminating picolibc in package writing

litex/soc/software/bios/Makefile
Without the proposed change, crt0.o is marked by Make as an intermediate file and removed: 
```
Must remake target 'all'.
python3 -m litex.soc.software.memusage bios.elf {file path}/litex/mor1kx_standard_32_F
alse/software/bios/../include/generated/regions.ld or1k-elf
Putting child 0x55a2098374e0 (all) PID 41438 on the chain.
Live child 0x55a2098374e0 (all) PID 41438
ROM usage: 36.54KiB     (57.09%)
RAM usage: 1.74KiB      (21.78%)
Reaping winning child 0x55a2098374e0 PID 41438
Removing child 0x55a2098374e0 PID 41438 from chain.
Successfully remade target file 'all'.
Removing intermediate files...
rm crt0.o
```
crt0.o is potentially valuable for building software for a LiteX sim target (I'm currently working on a script to run Embench on a simulated target), so it would be nice to keep it …
=> add crt0.o to BIOS target list

litex/soc/integration/soc.py
The `add_controller` alias for `add_master` incorrectly includes self in the method call, which causes a runtime error complaining if a user runs `self.bus.add_controller(name="x", controller=controller)`It just needs a simple fix to work correctly.
=> Fix add_controller() call

.github/workflows/ci.yml, litex/build/vhd2v_converter.py
fixes https://github.com/enjoy-digital/litex/issues/2107 by feeding the ghdl output to yosys to flatten it to avoid naming conflicts
This is still a kinda dumb way to have more than one VHDL instance but it works...
=> flatten ghdl output with yosys to avoid conflicts

litex/build/gowin/apicula.py, litex/build/nextpnr_wrapper.py
Recent `nextPNR`'s evolutions have introduces *himbaechel* architecture. This one supports FPGAs like **gowin**, **gatemate**, **xilinx**, ...
For *apicula* toolchain current solution is to force nextPNR name in `finalize` method.
But since `nextpnr-gowin` is now deprecated it make more sense to moves this logic in `nextpnr_wrapper.py`: `apicula.py` know informations about gowin devices, `nextpnr_wrapper.py` know for gowin architecture the executable is called `nextpnr-himbaechel`.
A second `nextPNR` evolution is the introduction of `HIMBAECHEL_SPLIT` option:
- when unset, or set to OFF, all selected `uarch` are included into a single executable
- when set each `uarch` is supported by a specific executable (`nextpnr-himbaechel-XXX`) where XXX is the `uarch` name
This PR:
- adapts the code …
=> build/nextpnr_wrapper.py: directly handles himbaechel architecture

litex/build/colognechip/colognechip.py, litex/build/colognechip/peppercorn.py, litex/build/colognechip/platform.py, litex/build/nextpnr_wrapper.py
A new opensource toolchain is available for CologneChip GateMate FPGAs. This one is based on Yosys/nextPNR and Project Peppercorn.
This PR adds support to this alternate toolchain.
Note: nextPNR and peppercorn is under development and consequently GateMate FPGAs are not fully supported (`no-mult` option is passed to Yosys, because `CC_MULT` aren't supported.
Tested with both CologneChip GateMate eval board and Olimex GateMate EVB
=> Gatemate himbaechel toolchain

litex/soc/interconnect/axi/axi_full.py
According to the [AMBA AXI and ACE Protocol Specification](https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/IHI0022H_amba_axi_protocol_spec.pdf) (page 49), the burst size width is fixed at 3 and remains unchanged between AXI3 and AXI4.
=> Burst Size Width Consistency in AXI3 and AXI4

litex/soc/software/bios/cmds/cmd_litedram.c
Partially fixes issue with https://github.com/litex-hub/litex-boards/pull/658
=> soc/software/bios/cmds/cmd_litedram.c: disabled sdram_rst_cmd_delay_handler and sdram_force_cmd_delay_handler when write_leveling isn't supported

litex/soc/cores/cpu/minerva/core.py, litex/soc/cores/cpu/sentinel/core.py
This one fixes GCC flags parameter to be inline with those used on the other CPU cores.
=> Fix gcc march parameter for minerva and sentinel cores

litex/build/anlogic/anlogic.py, litex/build/anlogic/platform.py, litex/build/anlogic/programmer.py
This introduces enhancements to the Anlogic platform:
1. Fix typo Dinasty to  Dynasty.
2. Fix Tang Dynasty not exiting problem after running `run.tcl`.
3. Add DR1V90MEG484 device support, which has built-in FPGA with 94464 LUTs and a UX900 RISC-V CPU hardcore from Nuclei System Technology. The dr1_90 architecture is only supported in Tang Dynasty version 5.9.
4. Introduced a new `TangDynastyProgrammer`, supporting `load_bitstream()` function for Anlogic platform. Since I don't have the Sipeed Tang Primer board, it's only tested on the dr1v90 platform.
=> Add DR1V90MEG484 device and load_bitstream function support for Anlogic platform

litex/soc/cores/cpu/coreblocks/__init__.py, litex/soc/cores/cpu/coreblocks/boot-helper.S, litex/soc/cores/cpu/coreblocks/core.py, litex/soc/cores/cpu/coreblocks/crt0.S, litex/soc/cores/cpu/coreblocks/csr-defs.h, litex/soc/cores/cpu/coreblocks/irq.h, litex/soc/cores/cpu/coreblocks/system.h, litex_setup.py, test/test_integration.py
Hi,
This PR adds [Coreblocks](https://github.com/kuznia-rdzeni/coreblocks/) cpu core support.
Coreblocks is an experimental RISC-V Out-of-Order core generator written in Amaranth.
Core elaboration requires python 3.11, but it is solved similar to recent Sentinel core by PEP-723 script. Wrapper script is placed in `pythondata-cpu-coreblocks` instead, because of dynamically changing dependencies. `pipx` is the only dependency installed by default in pythondata package and it is used to run the wrapper.
Coreblocks with LiteX runs Zephyr [zephyr-on-litex-coreblocks](https://github.com/kuznia-rdzeni/zephyr-on-litex-coreblocks) and (currently) no-mmu Linux [linux-on-litex-coreblocks](https://github.com/kuznia-rdzeni/linux-on-litex-coreblocks) !
I added the core to the CI and simulation boot …
=> soc/cores/cpu: Add Coreblocks RISC-V cpu

litex/gen/fhdl/verilog.py
- lower specials, that got overwritten, too.
- support resolving slices with invert in it.
=> fhdl: verilog: slice_lowerer: support invert

litex/soc/integration/soc.py, litex/soc/interconnect/axi/axi_full.py, litex/soc/interconnect/axi/axi_lite.py, litex/soc/interconnect/wishbone.py
add logic to set a offset to bus slaves.
=> soc: interconnect: add logic to set a offset to bus slaves

litex/soc/integration/soc.py
Makes it easier/more readable to override existing IP/MAC address constants, for example, you could do:
```python
add_ip_address_constants(self, "REMOTEIP", remote_ip, check_duplicate=False)
```
instead of ([source](https://github.com/litex-hub/linux-on-litex-vexriscv/blob/55c2f4aa1cf96924f6e64e6896755dce08aa7f7f/soc_linux.py#L60-L72)):
```python
try: # FIXME: Improve.
self.constants.pop("REMOTEIP1")
self.constants.pop("REMOTEIP2")
self.constants.pop("REMOTEIP3")
self.constants.pop("REMOTEIP4")
except:
pass
self.add_constant("REMOTEIP1", int(remote_ip[0]))
self.add_constant("REMOTEIP2", int(remote_ip[1]))
self.add_constant("REMOTEIP3", int(remote_ip[2]))
self.add_constant("REMOTEIP4", int(remote_ip[3]))
```
=> Expose 'check_duplicate' argument in 'add_ip_address_constants' and 'add_mac_address_constants'

litex/soc/cores/cpu/vexiiriscv/core.py, test/test_integration.py
This PR adds vexiiriscv to the test_integration unit test.
While working on this, I noticed the following issues:
- The log output was broken when a CPU failed to boot. This was due to incorrect file mode settings when opening the log file.
- The previously recommended commit for vexiiriscv fails to compile (at least with default settings) due to the following error:
> Error:  Note: the super classes of <$anon: spinal.lib.bus.amba4.axi.sim.Axi4WriteOnlyMonitor> contain the following, non final members named onWriteStart:
> Error:  def onWriteStart(address: BigInt,id: Int,size: Int,len: Int,burst: Int,cache: Int): Unit
> Error:          override def onWriteStart(address: BigInt, id: Int, size: Int, len: Int, burst: Int): Unit = {
- To fix this, I updated the recommended commit to the …
=> Tests/test_integration: Fix log output on failure + Add vexiiriscv to unit tests

litex/soc/cores/cpu/ibex/core.py, test/test_integration.py
This PR fixes #2258.
Vivado require files that define modules to be explicitly added to the project.
I also re-enabled the boot test for ibex CPU.
=> cpu/ibex: Fix #2258

litex/soc/software/libliteeth/udp.c, litex/soc/software/libliteeth/udp.h
This adds support for UDP broadcasts and a helper function to get the
currently set IP. These changes are required for BOOTP support.
now protected with a ifdef, so if its nat activated its not compiled in
=> bios: add broadcast support to libliteeth/udp

litex/build/xilinx/platform.py, litex/build/xilinx/vivado.py
Added for Spartan UltraScale+ (and perhaps future Versal) support
Tested with enclosed files using 2025.1
[test.tar.gz](https://github.com/user-attachments/files/21008683/test.tar.gz)
=> litex/build/xilinx : Add Device Image (pdi) generation support to Vivado builds

litex/build/efinix/common.py, litex/soc/cores/ram/efinix_hyperram.py
This PR:
- updates `HyperRAM` module call with missing parameters
- Fix `EfinixTristateImpl`: this class fails when signal is `TSTriple`
- updates PLL uses according to current usage
Note: This PR fix build, but has not being tested since it requires a board based on ti60f100
=> Fix efinix hyperram

litex/build/lattice/trellis.py
Some ECP5 differs by the name but the die is the same. For example the 12F and 25F have same die.
It's thus possible to build (`nextpnr-ecp5`) a bitstream targeted for a 25F and load/write it to a 12F.
The only limitation is to have the correct IDCODE in the bitstream, otherwise the ECP5 will reject it.
`ecppack` with `--idcode` is able to overrides IDCODE when `.json` is converted to `.bit` allowing the bitstream to be accepted by the FPGA.
This PR adds `--ecppack-idcode` argument to allows user to specify the targeted FPGA IDCODE.
=> build/lattice/trellis.py: added argument to overrides bitstream's IDCODE

litex/soc/interconnect/axi/axi_full.py
In the AXIInterconnectShared and AXICrossbar classes AXIInterfaces are always initialized with id_width = 1, which causes id errors.
Fixed by initializing them with the biggest id_width of all master Interfaces (like data_width and address_width).
=> interconnect:axi_full: Initialize AXIInterfaces with correct id_width

litex/build/lattice/common.py
Required for reliable litesdcard on ECP5 in SD mode; fixes #2201
=> build/lattice: Add SDR tristate specialisation for ECP5

litex/soc/software/libbase/isr.c
remove warning for
"no previous prototype for 'plic_init' [-Wmissing-prototypes]" when building bios
=> bios: isr: remove warning

litex/build/altera/quartus.py, litex/build/generic_toolchain.py, litex/soc/cores/clock/intel_agilex.py
Added a new object for PLL SDC statements that gets applied earlier in the generated SDC file as a replacement for the "derive_pll_clocks" command which are no longer supported in the Agilex family.
Also some cleanups/fixes related to clock naming in the SDC file and false path statements.
=> More quality of life improvements for Agilex family of devices
